/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/account/discord": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["detachDiscord"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/account/email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["changeUnverifiedEmail"];
    trace?: never;
  };
  "/v1/account/handle": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["renameHandle"];
    trace?: never;
  };
  "/v1/account/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["setPassword"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/account/nsfw-visibility": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["setNsfwVisibility"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/sign-up": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signUp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/sign-in": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signIn"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/discord": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["beginDiscord"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/discord/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["completeDiscord"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/sign-out": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signOut"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/verify-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["verifyEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/password-reset": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["requestPasswordReset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/password-reset/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["completePasswordReset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/link/requests": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Start linking a client application to a creator's account. Anyone may call this: LumiHub authenticates the creator and the individual installation, never the software vendor, so there is no registration step, no client id and no client secret. */
    post: operations["startLinkRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/link/poll": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Ask whether the creator has approved yet. Wait at least the interval the link request came with between calls. */
    post: operations["pollLinkRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/link/requests/{userCode}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description What the client behind a user code is asking for. */
    get: operations["getLinkRequest"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/link/requests/{userCode}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Approve a link request. A link request may be approved once and redeemed once. */
    post: operations["approveLinkRequest"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/instances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Every instance linked to the signed-in account, live ones first, then the record of the ones they revoked. */
    get: operations["listInstances"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/instances/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description The instance the bearer credential belongs to. Every authenticated request updates lastSeenAt, and this one exists so a client can check its credential without sending anything. */
    get: operations["getInstance"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/instances/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** @description Cut an instance off. Its credential stops working immediately and the state it held here is discarded. A record that it was linked and revoked stays. */
    delete: operations["revokeInstance"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profiles/{handle}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getProfile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listAssets"];
    put?: never;
    /** @description Two ways to make an asset. Send form data to bring a file in, or send JSON naming a kind to start from nothing. The kind is asked for once, before any blocks exist, and never changes afterwards. */
    post: operations["createAsset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description One asset by id. Unlisted assets answer normally, because unlisted is discovery rather than authorization. Withheld, deleted and never-existed all answer 404. */
    get: operations["getAsset"];
    put?: never;
    post?: never;
    delete: operations["deleteAsset"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/revisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Replace an asset's source bytes. A revision is the file only: name, blurb, tags and the NSFW flag stay as the creator left them. A file that reads as a different kind is refused and the asset is left untouched. */
    post: operations["addAssetRevision"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/blocks/{blockId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** @description Save one block without rewriting any other block on the asset. Draft content may be empty, but it must still be structurally valid and obey the kind catalog's builder constraints. */
    put: operations["saveAssetBlock"];
    post?: never;
    /** @description Remove one optional block and its elements. Required blocks are refused. Remaining positions are rewritten into one gapless page order. */
    delete: operations["removeAssetBlock"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/blocks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** @description Rewrite the whole page order and save visibility and width choices in the same transaction. Every current block must appear exactly once. */
    put: operations["arrangeAssetBlocks"];
    /** @description Add one optional section to the foot of the page, holding the element the creator chose. A required section, and a section already present that cannot repeat, are both refused. */
    post: operations["addAssetBlock"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/blocks/{blockId}/move-and-remove": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Move every unpinned element into a section with enough free slots, then remove the emptied optional section. Both changes commit together. */
    post: operations["moveAssetBlockContent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/file-patch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** @description Replace the creator's semantic changes to the file. Omitted fields are removed from the patch. Catalog metadata is a separate concern and is never written into the artifact. */
    put: operations["setFilePatch"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["restoreAsset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/identity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** @description Save the header fields that sit above an asset's blocks. The adult content answer may be null only while the asset is a draft, so nothing answers it on the creator's behalf. An edit is live when it saves. */
    put: operations["setAssetIdentity"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Publish a draft. Publishing is one-way: unlisted is the reversible retreat and deletion is the exit. A draft that does not meet the floor is refused with the whole readiness list rather than the first thing missing. */
    post: operations["publishAsset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/discovery": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["setAssetDiscovery"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profiles/{handle}/deleted": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listDeletedAssets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/withhold": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["withholdAsset"];
    post?: never;
    delete: operations["clearAssetWithhold"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/download/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["downloadSource"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/download/{id}/{target}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["downloadExport"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/media": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listMedia"];
    put?: never;
    post: operations["addMedia"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/media/{media_id}/{variant}/{derivative_version}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getMediaVariant"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/ingests/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getIngest"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["completeIngest"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description asset:receive lets an instance receive assets sent to it. library:sync lets it report what it has installed.
     * @enum {string}
     */
    Scope: "asset:receive" | "library:sync";
    StartLinkRequest: {
      /** @description What the creator sees on the approval screen. Name the installation, not the product, so somebody with two of them can tell which is which. */
      name: string;
      scopes: components["schemas"]["Scope"][];
    };
    LinkRequest: {
      /** @description Kept private by the client and sent when polling. */
      deviceCode: string;
      /** @description Shown to the creator, who enters it on LumiHub. */
      userCode: string;
      /** @description Where the creator enters the user code. */
      verificationUrl: string;
      /** @description The same page with the code already filled in. A client running on the creator's own machine may open it. */
      verificationUrlComplete: string;
      /** Format: date-time */
      expiresAt: string;
      /** @description Seconds to wait between polls. */
      interval: number;
    };
    PollLinkRequest: {
      deviceCode: string;
    };
    LinkPollResult: {
      /** @enum {string} */
      status: "pending" | "linked";
      /** @description The instance credential, sent once and never again. It does not expire and there is nothing to refresh. */
      token?: string;
      instance?: components["schemas"]["LinkedInstance"];
    };
    PendingLink: {
      name: string;
      scopes: components["schemas"]["Scope"][];
      /** Format: date-time */
      expiresAt: string;
    };
    LinkedInstance: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @description The start of the credential, so two links are told apart. */
      prefix: string;
      scopes: components["schemas"]["Scope"][];
      /** Format: date-time */
      linkedAt: string;
      /** Format: date-time */
      lastSeenAt: string | null;
      /** Format: date-time */
      revokedAt: string | null;
    };
    LinkedInstanceList: {
      items: components["schemas"]["LinkedInstance"][];
    };
    Account: {
      /** Format: uuid */
      id: string;
      handle: string;
      /** Format: email */
      email: string | null;
      emailVerified: boolean;
      discordLinked: boolean;
      hasPassword: boolean;
      /** @enum {string} */
      role: "user" | "moderator" | "admin";
    };
    ChangeEmailRequest: {
      /** Format: email */
      email: string;
    };
    SessionState: {
      user: components["schemas"]["Account"] | null;
    };
    Profile: {
      /** Format: uuid */
      id: string;
      handle: string;
    };
    RenameHandleRequest: {
      handle: string;
    };
    SignUpRequest: {
      /** Format: email */
      email: string;
      password: string;
      handle: string;
    };
    SignInRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    PasswordRequest: {
      password: string;
    };
    NsfwVisibilityRequest: {
      /** @enum {string} */
      visibility: "hidden" | "blurred" | "shown";
    };
    PasswordResetRequest: {
      /** Format: email */
      email: string;
    };
    CompletePasswordResetRequest: {
      token: string;
      password: string;
    };
    VerifyEmailRequest: {
      token: string;
    };
    /** @description The kind an asset is built as. Only kinds Illarin can build are accepted, so a creator is never handed an empty page. */
    StartAssetRequest: {
      kind: string;
    };
    /** @description A titled container. Required, hideable, the layouts it allows and its default width are read from the kind catalog at render time, so this is what the catalog says today rather than what was true when the block was made. */
    AssetBlock: {
      /** Format: uuid */
      id: string;
      definition: string;
      /** @description The creator's wording, or the definition's default where they wrote none. */
      title: string;
      titleIsDefault: boolean;
      position: number;
      hidden: boolean;
      /** @enum {string} */
      layout: "single" | "duo" | "main-aside" | "trio" | "stack-2" | "stack-3";
      /** @enum {string} */
      width: "full" | "two_thirds" | "half" | "third";
      /** @description The layouts this block's current definition offers. */
      allowedLayouts: (
        | "single"
        | "duo"
        | "main-aside"
        | "trio"
        | "stack-2"
        | "stack-3"
      )[];
      required: boolean;
      hideable: boolean;
      /** @description Whether every element in the block carries nothing. Computed for display and never stored. */
      isEmpty: boolean;
      elements: components["schemas"]["AssetElement"][];
    };
    SaveAssetBlockRequest: {
      /** @description Null keeps the definition's current default wording. */
      title: string | null;
      /** @enum {string} */
      layout: "single" | "duo" | "main-aside" | "trio" | "stack-2" | "stack-3";
      /** @enum {string} */
      width: "full" | "two_thirds" | "half" | "third";
      elements: components["schemas"]["SaveAssetElement"][];
    };
    ArrangeAssetBlocksRequest: {
      blocks: {
        /** Format: uuid */
        id: string;
        hidden: boolean;
        /** @enum {string} */
        width: "full" | "two_thirds" | "half" | "third";
      }[];
    };
    MoveAssetBlockContentRequest: {
      /** Format: uuid */
      destinationBlockId: string;
    };
    SaveAssetElement: {
      /** Format: uuid */
      id: string;
      type: components["schemas"]["ElementType"];
      /** @description Absent where the element has no import or export meaning. */
      role?: string;
      slot: string;
      /** @enum {string} */
      display?: "rich" | "verbatim";
      itemSize?: components["schemas"]["ItemSize"];
      /** @description The element type's own body. */
      content:
        | components["schemas"]["ProseContent"]
        | components["schemas"]["TextSetContent"]
        | components["schemas"]["FieldListContent"]
        | components["schemas"]["DialogueSampleContent"]
        | components["schemas"]["ImageSetContent"]
        | components["schemas"]["LinkListContent"]
        | components["schemas"]["EntryTableContent"];
    };
    /** @description One piece of content. Its role is what import and export read, and it travels with the element wherever the creator moves it. */
    AssetElement: {
      /** Format: uuid */
      id: string;
      type: components["schemas"]["ElementType"];
      /** @description Absent where the element has no import or export meaning. */
      role?: string;
      slot: string;
      label: string;
      /** @description A pinned element can be neither removed nor moved out of its block. */
      pinned: boolean;
      /** @enum {string} */
      display?: "rich" | "verbatim";
      itemSize?: components["schemas"]["ItemSize"];
      isEmpty: boolean;
      /** @description What the element says about its own data, such as how many entries a book holds and how many are switched on. Worked out on the way out and never stored, and never a token count. */
      facts: string[];
      /** @description The element type's own body. A reader switches on type to read it. */
      content:
        | components["schemas"]["ProseContent"]
        | components["schemas"]["TextSetContent"]
        | components["schemas"]["FieldListContent"]
        | components["schemas"]["DialogueSampleContent"]
        | components["schemas"]["ImageSetContent"]
        | components["schemas"]["LinkListContent"]
        | components["schemas"]["EntryTableContent"];
    };
    ProseContent: {
      text: string;
    };
    TextSetContent: {
      texts: {
        name?: string;
        text: string;
      }[];
    };
    DialogueSampleContent: {
      turns: {
        speaker: string;
        text: string;
      }[];
    };
    /** @description An ordered list of images. An item carries its image and one optional free-text name, and its position is where it sits in the list. */
    ImageSetContent: {
      images: {
        /** Format: uuid */
        mediaId: string;
        name?: string;
      }[];
    };
    FieldListContent: {
      fields: {
        name?: string;
        value: string;
      }[];
    };
    LinkListContent: {
      links: {
        label?: string;
        url: string;
        note?: string;
      }[];
    };
    /** @description A lorebook. An entry is switched on by its keys, and how it behaves on the passes after the first is its own setting. */
    EntryTableContent: {
      entries: {
        name?: string;
        keys: string[];
        secondaryKeys?: string[];
        selective?: boolean;
        caseSensitive?: boolean;
        constant?: boolean;
        enabled: boolean;
        order?: number;
        /**
         * @description Unset where the book leaves the choice to whatever reads it.
         * @enum {string}
         */
        position?: "before_character" | "after_character";
        recursion?: {
          exclude?: boolean;
          prevent?: boolean;
          delayUntil?: boolean;
        };
        text: string;
      }[];
    };
    /**
     * @description What an element's data structure is, from the global vocabulary.
     * @enum {string}
     */
    ElementType:
      | "prose"
      | "text_set"
      | "field_list"
      | "dialogue_sample"
      | "image_set"
      | "link_list"
      | "entry_table";
    /**
     * @description How large the images inside an element are drawn. It names what it controls, and no element type declares a measurement of its own.
     * @enum {string}
     */
    ItemSize: "small" | "medium" | "large";
    AddAssetBlockRequest: {
      definition: string;
      elementType: components["schemas"]["ElementType"];
    };
    /** @description One section the add tray offers. Where the content ends up is what the tray groups by, so a creator arrives at it by destination. */
    AddableSection: {
      definition: string;
      title: string;
      summary: string;
      /** @enum {string} */
      group: "file" | "reader" | "work" | "other";
      groupTitle: string;
      repeatable: boolean;
      /** @description The elements a creator may start the section with. One choice needs no question asking. */
      choices: components["schemas"]["AddableSectionChoice"][];
    };
    AddableSectionChoice: {
      type: components["schemas"]["ElementType"];
      label: string;
    };
    Asset: {
      /** Format: uuid */
      id: string;
      kind: string;
      passthroughPlatform?: string | null;
      format: string;
      name: string;
      blurb: string;
      tags: string[];
      isNsfw: boolean | null;
      /** @enum {string} */
      discovery: "listed" | "unlisted";
      /** Format: date-time */
      createdAt: string;
    };
    AssetDetail: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      kind: "character" | "lorebook" | "preset" | "theme";
      name: string;
      /** @description The catalog blurb the creator wrote for a person. Never the file's own description, which is a prompt written for a model. */
      blurb: string;
      tags: components["schemas"]["AssetTag"][];
      creator: string;
      /** @description Null while a draft has not been asked the adult content question. Nothing answers it on the creator's behalf. */
      isNsfw: boolean | null;
      /** @enum {string} */
      discovery: "listed" | "unlisted";
      /**
       * @description A draft resolves for its owner alone. Discovery applies to a published asset only.
       * @enum {string}
       */
      lifecycle: "draft" | "published";
      /** @description Whether the reader owns the asset. The owner's page is the reader's page with its editing affordances, not a second visual state. */
      isOwner: boolean;
      /** @description Whether the asset carries a file a reader can download. An asset built from nothing carries none. */
      hasSourceFile: boolean;
      /** Format: date-time */
      createdAt: string;
      /** @description The asset's blocks in page order. */
      blocks: components["schemas"]["AssetBlock"][];
      /** @description The asset's images, cover first. Variant URLs already reflect the reader's preference, so a blurred reader is never handed a clear one. */
      media: components["schemas"]["AssetImage"][];
      /** @description The composed social preview for link unfurling. Null on a draft, which nothing unfurls. */
      preview: string | null;
      /** @description What publication is waiting on. Present only while the owner is reading their own draft. */
      readiness?: components["schemas"]["ReadinessItem"][];
      /** @description The sections this kind can still be given, in catalog order. Present only while the owner is reading their own asset. */
      addableSections?: components["schemas"]["AddableSection"][];
      /** @enum {string} */
      visibility: "hidden" | "blurred" | "shown";
      withhold?: components["schemas"]["AssetWithhold"];
    };
    AssetDiscoveryRequest: {
      /** @enum {string} */
      discovery: "listed" | "unlisted";
    };
    AssetIdentityRequest: {
      name: string;
      /** @description Null is the unanswered state, which only a draft may be in. */
      isNsfw: boolean | null;
    };
    /** @description One thing publication waits on, and whether the asset carries it. */
    ReadinessItem: {
      id: string;
      label: string;
      detail: string;
      met: boolean;
      /**
       * Format: uuid
       * @description The block a creator fills this in. Absent for a header field.
       */
      blockId?: string;
    };
    PublishRefusal: {
      error: string;
      /** @description The whole floor, so a refusal names every missing item at once. */
      readiness?: components["schemas"]["ReadinessItem"][];
    };
    FileFieldPatch: {
      description?: string;
      personality?: string;
      scenario?: string;
      first_mes?: string;
      system_prompt?: string;
      post_history_instructions?: string;
      creator_notes?: string;
      character_version?: string;
    };
    DeletedAssetList: {
      items: components["schemas"]["DeletedAsset"][];
    };
    DeletedAsset: {
      /** Format: uuid */
      id: string;
      name: string;
      /** @enum {string} */
      kind: "character" | "lorebook" | "preset" | "theme";
      /** Format: date-time */
      deletedAt: string;
      /** Format: date-time */
      recoverableUntil: string;
    };
    WithholdAssetRequest: {
      reason: string;
    };
    AssetWithhold: {
      reason: string;
      actor: string;
      /** Format: date-time */
      at: string;
    };
    AssetTag: {
      /** @description The creator's own text, shown as written. */
      label: string;
      /** @description The normalized form browse matches on. */
      value: string;
    };
    AssetImage: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      role:
        | "avatar"
        | "expression"
        | "gallery"
        | "avatar_alt"
        | "perspective_layer";
      isCover: boolean;
      detailUrl: string;
      thumbUrl: string;
      width: number;
      height: number;
    };
    AssetList: {
      items: components["schemas"]["BrowseAsset"][];
      total: number;
      suppressed: number;
      /** @enum {string} */
      visibility: "hidden" | "blurred" | "shown";
      nextCursor?: components["schemas"]["BrowseCursor"] | null;
      platforms: components["schemas"]["BrowseOption"][];
      facets: components["schemas"]["BrowseFacet"][];
      /** @enum {string|null} */
      emptyState: "catalog" | "no_matches" | "suppressed" | null;
    };
    BrowseAsset: {
      /** Format: uuid */
      id: string;
      name: string;
      creator: string;
      /** @enum {string} */
      kind: "character" | "lorebook" | "preset" | "theme";
      /** @description Null on a draft whose creator has not answered the adult content question. */
      isNsfw: boolean | null;
      /**
       * @description Present only on the owner's own listing.
       * @enum {string}
       */
      ownerState?: "draft" | "unlisted" | "withheld";
      withhold?: components["schemas"]["AssetWithhold"];
      cover: components["schemas"]["BrowseCover"] | null;
    };
    BrowseCover: {
      url: string;
      width: number;
      height: number;
    };
    BrowseCursor: {
      /** Format: date-time */
      before: string;
      /** Format: uuid */
      beforeId: string;
    };
    BrowseOption: {
      value: string;
      label: string;
      count: number;
      selected: boolean;
    };
    BrowseFacet: {
      key: string;
      label: string;
      options: components["schemas"]["BrowseOption"][];
    };
    CreateAssetRequest: {
      confirmed: boolean;
      name?: string;
      blurb?: string;
      tags?: string[];
      isNsfw?: boolean;
      /** @enum {string} */
      discovery?: "listed" | "unlisted";
    };
    AddMediaRequest: {
      /** @enum {string} */
      role:
        | "avatar"
        | "expression"
        | "gallery"
        | "avatar_alt"
        | "perspective_layer";
    };
    Media: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      assetId: string;
      /** @enum {string} */
      role:
        | "avatar"
        | "expression"
        | "gallery"
        | "avatar_alt"
        | "perspective_layer";
      width: number;
      height: number;
      derivativeVersion: number;
    };
    MediaList: {
      items: components["schemas"]["Media"][];
    };
    IngestOperation: {
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      status: "pending" | "processing" | "needs_kind" | "failed" | "success";
      url: string;
      asset?: components["schemas"]["Asset"] | null;
      needsKind?: components["schemas"]["NeedsKind"];
      failure?: components["schemas"]["IngestFailure"];
    };
    NeedsKind: {
      /** @enum {string|null} */
      kind: "character" | "lorebook" | "preset" | "theme" | null;
      name: string;
    };
    CompleteIngestRequest: {
      /** @enum {string} */
      kind: "character" | "lorebook" | "preset" | "theme";
      name: string;
    };
    IngestFailure: {
      /** @enum {string} */
      reason:
        | "malformed_input"
        | "unsupported_format"
        | "unsupported_version"
        | "safety_violation"
        | "wrong_kind"
        | "internal_failure";
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  detachDiscord: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The account with Discord detached */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Discord is absent or is the last usable sign-in method */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  changeUnverifiedEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeEmailRequest"];
      };
    };
    responses: {
      /** @description The account with a fresh verification link sent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The address is not valid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The address is verified here or elsewhere */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  renameHandle: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameHandleRequest"];
      };
    };
    responses: {
      /** @description The account under its new handle */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The handle is not valid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The handle is active or retired */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordRequest"];
      };
    };
    responses: {
      /** @description The account with a password set */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The password is empty */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The account already has a password */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setNsfwVisibility: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NsfwVisibilityRequest"];
      };
    };
    responses: {
      /** @description The reader's content preference is saved */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The visibility value is invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signUp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpRequest"];
      };
    };
    responses: {
      /** @description The new signed-in account */
      201: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The account details are not valid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The handle or verified address is already claimed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInRequest"];
      };
    };
    responses: {
      /** @description The signed-in account */
      200: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The credentials do not identify one account */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  beginDiscord: {
    parameters: {
      query?: {
        intent?: "sign-in" | "attach";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Continue on Discord */
      303: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Attaching Discord requires a signed-in account */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Attaching Discord requires a verified account */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Discord sign-in is not configured */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  completeDiscord: {
    parameters: {
      query: {
        state: string;
        code?: string;
        error?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Continue on LumiHub */
      303: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signOut: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The session no longer exists */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The account at this origin, when one is signed in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionState"];
        };
      };
    };
  };
  verifyEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyEmailRequest"];
      };
    };
    responses: {
      /** @description The account with its address verified */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The link is invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Another account verified the address first */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  requestPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    responses: {
      /** @description A reset is sent when the verified account exists */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The request is not valid JSON */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  completePasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompletePasswordResetRequest"];
      };
    };
    responses: {
      /** @description The password is set */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The link or password is invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  startLinkRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartLinkRequest"];
      };
    };
    responses: {
      /** @description The codes the client shows and the code it keeps */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LinkRequest"];
        };
      };
      /** @description The name or the requested scopes are not valid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  pollLinkRequest: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PollLinkRequest"];
      };
    };
    responses: {
      /** @description Still waiting, or linked and holding the credential */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LinkPollResult"];
        };
      };
      /** @description The link request has expired */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Polled faster than the interval */
      429: {
        headers: {
          "Retry-After"?: number;
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getLinkRequest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userCode: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The name and scopes to show before approving */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PendingLink"];
        };
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No unapproved link request has that code */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Too many codes were entered */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  approveLinkRequest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userCode: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description What was approved */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PendingLink"];
        };
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No unapproved link request has that code */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Too many codes were entered */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listInstances: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The creator's linked instances */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LinkedInstanceList"];
        };
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getInstance: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The instance holding the credential */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LinkedInstance"];
        };
      };
      /** @description The credential does not identify a live instance */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  revokeInstance: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The instance is revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The account has no live instance with that id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        handle: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The active public profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      /** @description No active profile uses the handle */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listAssets: {
    parameters: {
      query?: {
        kind?: "character" | "lorebook" | "preset" | "theme";
        platform?: string;
        /** @description Scope the listing to one creator's public profile. */
        creator?: string;
        /** @description One search expression. Bare text matches names, creator handles and blurbs. Repeat tag: to require every tag; one author: qualifier may narrow the creator. Quote qualifier values that contain spaces. */
        q?: string;
        facet?: string[];
        /** @description The reader's presentation preference. Browse page URLs keep this preference out of their own query string. */
        nsfw?: "hidden" | "blurred" | "shown";
        limit?: number;
        /** @description The made date of the last asset on the previous page. Send it with beforeId or not at all. */
        before?: string;
        /** @description The id of that same asset */
        beforeId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Assets a visitor may see */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetList"];
        };
      };
    };
  };
  createAsset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Send the metadata part before the file part. The file is read as it arrives, so the catalog fields have to be known by then. */
    requestBody: {
      content: {
        "multipart/form-data": {
          metadata: components["schemas"]["CreateAssetRequest"];
          /** Format: binary */
          file: string;
        };
        "application/json": components["schemas"]["StartAssetRequest"];
      };
    };
    responses: {
      /** @description The draft that was started, with the blocks its kind requires */
      201: {
        headers: {
          Location?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetDetail"];
        };
      };
      /** @description The durable ingest operation for the accepted upload */
      202: {
        headers: {
          Location?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestOperation"];
        };
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The uploaded bytes have been purged and cannot return */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAsset: {
    parameters: {
      query?: {
        /** @description The reader's presentation preference. Asset page URLs keep this preference out of their own query string. */
        nsfw?: "hidden" | "blurred" | "shown";
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The asset as a visitor may see it */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetDetail"];
        };
      };
      /** @description No asset a visitor may see */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteAsset: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The asset is recoverable from the creator's Deleted section */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld and cannot be deleted */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  addAssetRevision: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description The durable ingest operation for the accepted revision */
      202: {
        headers: {
          Location?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestOperation"];
        };
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld and cannot be changed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  saveAssetBlock: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        blockId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveAssetBlockRequest"];
      };
    };
    responses: {
      /** @description The saved block as it now appears on the page */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetBlock"];
        };
      };
      /** @description An optional block saved empty and returned to absent */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The block is malformed or breaks a builder constraint */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset or block does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld and cannot be changed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The uploaded bytes have been purged and cannot return */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  removeAssetBlock: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        blockId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The block and everything in it were removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset or block does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld and cannot be changed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  arrangeAssetBlocks: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ArrangeAssetBlocksRequest"];
      };
    };
    responses: {
      /** @description Every block in its saved page order */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetBlock"][];
        };
      };
      /** @description The arrangement is incomplete */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld and cannot be changed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  addAssetBlock: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddAssetBlockRequest"];
      };
    };
    responses: {
      /** @description The new section as it now appears at the foot of the page */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetBlock"];
        };
      };
      /** @description The section cannot be added to this asset */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld and cannot be changed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  moveAssetBlockContent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        blockId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MoveAssetBlockContentRequest"];
      };
    };
    responses: {
      /** @description Every remaining block in its saved page order */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetBlock"][];
        };
      };
      /** @description The source cannot be removed or the destination has no room */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset or either block does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld and cannot be changed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setFilePatch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FileFieldPatch"];
      };
    };
    responses: {
      /** @description The creator's file patch is saved */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The body is not a supported semantic patch */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld or its format cannot be patched */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  restoreAsset: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The existing asset and retained bytes are live again */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No recoverable asset belongs to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setAssetIdentity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssetIdentityRequest"];
      };
    };
    responses: {
      /** @description The header is saved */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The name is too long */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld and cannot be changed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  publishAsset: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The asset as its page now reads, published */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetDetail"];
        };
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The draft does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The draft is not ready, the asset is already published, or it is withheld */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublishRefusal"];
        };
      };
    };
  };
  setAssetDiscovery: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssetDiscoveryRequest"];
      };
    };
    responses: {
      /** @description The asset discovery state is saved */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The discovery value is invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld and cannot be changed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listDeletedAssets: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        handle: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The signed-in creator's assets still inside the recovery window */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DeletedAssetList"];
        };
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  withholdAsset: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WithholdAssetRequest"];
      };
    };
    responses: {
      /** @description The asset is withheld */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The reason is empty or invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account is not an admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No live asset has that id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  clearAssetWithhold: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The asset is no longer withheld */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account is not an admin */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No withheld asset has that id */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  downloadSource: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The current uploaded source file, byte for byte */
      200: {
        headers: {
          "Content-Disposition": "attachment" | "inline";
          "X-Content-Type-Options": "nosniff";
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
          "image/png": string;
          "image/jpeg": string;
          "image/webp": string;
          "image/gif": string;
        };
      };
      /** @description No such asset */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  downloadExport: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        /** @description A declared export target. Unsupported values fall back to raw. */
        target: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The current revision exported to the resolved target */
      200: {
        headers: {
          "Content-Disposition": "attachment" | "inline";
          "X-Content-Type-Options": "nosniff";
          "X-LumiHub-Export-Target": string;
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
          "application/json": string;
          "application/zip": string;
          "image/png": string;
        };
      };
      /** @description No such asset */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listMedia: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Media belonging to the asset */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MediaList"];
        };
      };
      /** @description No such asset */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  addMedia: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description Send the metadata part before the image file part. */
    requestBody: {
      content: {
        "multipart/form-data": {
          metadata: components["schemas"]["AddMediaRequest"];
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description A new immutable media record */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Media"];
        };
      };
      /** @description The role or image is not valid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset does not belong to the creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The asset is withheld and cannot be changed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getMediaVariant: {
    parameters: {
      query?: {
        /** @description When the signature runs out. A draft's images are served against a short-lived signature at the same address they keep once published. */
        expires?: string;
        signature?: string;
      };
      header?: never;
      path: {
        media_id: string;
        variant:
          | "grid"
          | "grid_blurred"
          | "detail"
          | "detail_blurred"
          | "thumb"
          | "thumb_blurred"
          | "og"
          | "og_blurred";
        derivative_version: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A named media variant */
      200: {
        headers: {
          "Cache-Control": string;
          "Content-Disposition": "inline";
          "X-Content-Type-Options": "nosniff";
          [name: string]: unknown;
        };
        content: {
          "image/png": string;
        };
      };
      /** @description No such media variant */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getIngest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The creator's ingest operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestOperation"];
        };
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No such ingest operation for this creator */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  completeIngest: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompleteIngestRequest"];
      };
    };
    responses: {
      /** @description The ingest operation queued again with its passthrough kind */
      202: {
        headers: {
          Location?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestOperation"];
        };
      };
      /** @description The kind or name is invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The signed-in account has not verified its email */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No such ingest operation awaiting a kind */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
