/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listAssets"];
    put?: never;
    post: operations["createAsset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/original": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["downloadOriginal"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Asset: {
      /** Format: uuid */
      id: string;
      kind: string;
      passthroughPlatform?: string | null;
      format: string;
      name: string;
      description: string;
      tags: string[];
      isNsfw: boolean;
      /** @enum {string} */
      discovery: "listed" | "unlisted";
      /** Format: date-time */
      createdAt: string;
    };
    AssetList: {
      items: components["schemas"]["Asset"][];
    };
    CreateAssetRequest: {
      kind?: string;
      filename: string;
      name: string;
      description?: string;
      tags?: string[];
      isNsfw?: boolean;
      /** @enum {string} */
      discovery?: "listed" | "unlisted";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listAssets: {
    parameters: {
      query?: {
        kind?: string;
        platform?: string;
        tag?: string[];
        facet?: string[];
        limit?: number;
        /** @description The made date of the last asset on the previous page. Send it with beforeId or not at all. */
        before?: string;
        /** @description The id of that same asset */
        beforeId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Assets a visitor may see */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetList"];
        };
      };
    };
  };
  createAsset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Send the metadata part before the file part. The file is read as it arrives, so the catalog fields have to be known by then. */
    requestBody: {
      content: {
        "multipart/form-data": {
          metadata: components["schemas"]["CreateAssetRequest"];
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description The asset that was created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Asset"];
        };
      };
    };
  };
  downloadOriginal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The uploaded file, byte for byte */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description No such asset */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
