/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/account/email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["changeUnverifiedEmail"];
    trace?: never;
  };
  "/v1/account/handle": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["renameHandle"];
    trace?: never;
  };
  "/v1/auth/sign-up": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signUp"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/sign-in": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signIn"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/sign-out": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["signOut"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getSession"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/verify-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["verifyEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/profiles/{handle}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getProfile"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listAssets"];
    put?: never;
    post: operations["createAsset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/assets/{id}/original": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["downloadOriginal"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Account: {
      /** Format: uuid */
      id: string;
      handle: string;
      /** Format: email */
      email: string | null;
      emailVerified: boolean;
    };
    ChangeEmailRequest: {
      /** Format: email */
      email: string;
    };
    SessionState: {
      user: components["schemas"]["Account"] | null;
    };
    Profile: {
      /** Format: uuid */
      id: string;
      handle: string;
    };
    RenameHandleRequest: {
      handle: string;
    };
    SignUpRequest: {
      /** Format: email */
      email: string;
      password: string;
      handle: string;
    };
    SignInRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    VerifyEmailRequest: {
      token: string;
    };
    Asset: {
      /** Format: uuid */
      id: string;
      kind: string;
      passthroughPlatform?: string | null;
      format: string;
      name: string;
      description: string;
      tags: string[];
      isNsfw: boolean;
      /** @enum {string} */
      discovery: "listed" | "unlisted";
      /** Format: date-time */
      createdAt: string;
    };
    AssetList: {
      items: components["schemas"]["Asset"][];
    };
    CreateAssetRequest: {
      kind?: string;
      filename: string;
      name: string;
      description?: string;
      tags?: string[];
      isNsfw?: boolean;
      /** @enum {string} */
      discovery?: "listed" | "unlisted";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  changeUnverifiedEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeEmailRequest"];
      };
    };
    responses: {
      /** @description The account with a fresh verification link sent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The address is not valid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The address is verified here or elsewhere */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  renameHandle: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenameHandleRequest"];
      };
    };
    responses: {
      /** @description The account under its new handle */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The handle is not valid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No account is signed in */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The handle is active or retired */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signUp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignUpRequest"];
      };
    };
    responses: {
      /** @description The new signed-in account */
      201: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The account details are not valid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The handle or verified address is already claimed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInRequest"];
      };
    };
    responses: {
      /** @description The signed-in account */
      200: {
        headers: {
          "Set-Cookie"?: string;
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The credentials do not identify one account */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  signOut: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The session no longer exists */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The account at this origin, when one is signed in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionState"];
        };
      };
    };
  };
  verifyEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyEmailRequest"];
      };
    };
    responses: {
      /** @description The account with its address verified */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description The link is invalid */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Another account verified the address first */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getProfile: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        handle: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The active public profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Profile"];
        };
      };
      /** @description No active profile uses the handle */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listAssets: {
    parameters: {
      query?: {
        kind?: string;
        platform?: string;
        tag?: string[];
        facet?: string[];
        limit?: number;
        /** @description The made date of the last asset on the previous page. Send it with beforeId or not at all. */
        before?: string;
        /** @description The id of that same asset */
        beforeId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Assets a visitor may see */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AssetList"];
        };
      };
    };
  };
  createAsset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Send the metadata part before the file part. The file is read as it arrives, so the catalog fields have to be known by then. */
    requestBody: {
      content: {
        "multipart/form-data": {
          metadata: components["schemas"]["CreateAssetRequest"];
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description The asset that was created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Asset"];
        };
      };
    };
  };
  downloadOriginal: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The uploaded file, byte for byte */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      /** @description No such asset */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
