// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AssetDiscovery.
const (
	AssetDiscoveryListed   AssetDiscovery = "listed"
	AssetDiscoveryUnlisted AssetDiscovery = "unlisted"
)

// Valid indicates whether the value is a known member of the AssetDiscovery enum.
func (e AssetDiscovery) Valid() bool {
	switch e {
	case AssetDiscoveryListed:
		return true
	case AssetDiscoveryUnlisted:
		return true
	default:
		return false
	}
}

// Defines values for CreateAssetRequestDiscovery.
const (
	CreateAssetRequestDiscoveryListed   CreateAssetRequestDiscovery = "listed"
	CreateAssetRequestDiscoveryUnlisted CreateAssetRequestDiscovery = "unlisted"
)

// Valid indicates whether the value is a known member of the CreateAssetRequestDiscovery enum.
func (e CreateAssetRequestDiscovery) Valid() bool {
	switch e {
	case CreateAssetRequestDiscoveryListed:
		return true
	case CreateAssetRequestDiscoveryUnlisted:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	Email         *openapi_types.Email `json:"email"`
	EmailVerified bool                 `json:"emailVerified"`
	Handle        string               `json:"handle"`
	Id            openapi_types.UUID   `json:"id"`
}

// Asset defines model for Asset.
type Asset struct {
	CreatedAt           time.Time          `json:"createdAt"`
	Description         string             `json:"description"`
	Discovery           AssetDiscovery     `json:"discovery"`
	Format              string             `json:"format"`
	Id                  openapi_types.UUID `json:"id"`
	IsNsfw              bool               `json:"isNsfw"`
	Kind                string             `json:"kind"`
	Name                string             `json:"name"`
	PassthroughPlatform *string            `json:"passthroughPlatform,omitempty"`
	Tags                []string           `json:"tags"`
}

// AssetDiscovery defines model for Asset.Discovery.
type AssetDiscovery string

// AssetList defines model for AssetList.
type AssetList struct {
	Items []Asset `json:"items"`
}

// ChangeEmailRequest defines model for ChangeEmailRequest.
type ChangeEmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// CreateAssetRequest defines model for CreateAssetRequest.
type CreateAssetRequest struct {
	Description *string                      `json:"description,omitempty"`
	Discovery   *CreateAssetRequestDiscovery `json:"discovery,omitempty"`
	Filename    string                       `json:"filename"`
	IsNsfw      *bool                        `json:"isNsfw,omitempty"`
	Kind        *string                      `json:"kind,omitempty"`
	Name        string                       `json:"name"`
	Tags        *[]string                    `json:"tags,omitempty"`
}

// CreateAssetRequestDiscovery defines model for CreateAssetRequest.Discovery.
type CreateAssetRequestDiscovery string

// Profile defines model for Profile.
type Profile struct {
	Handle string             `json:"handle"`
	Id     openapi_types.UUID `json:"id"`
}

// RenameHandleRequest defines model for RenameHandleRequest.
type RenameHandleRequest struct {
	Handle string `json:"handle"`
}

// SessionState defines model for SessionState.
type SessionState struct {
	User *Account `json:"user"`
}

// SignInRequest defines model for SignInRequest.
type SignInRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	Email    openapi_types.Email `json:"email"`
	Handle   string              `json:"handle"`
	Password string              `json:"password"`
}

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Token string `json:"token"`
}

// ListAssetsParams defines parameters for ListAssets.
type ListAssetsParams struct {
	Kind     *string   `form:"kind,omitempty" json:"kind,omitempty"`
	Platform *string   `form:"platform,omitempty" json:"platform,omitempty"`
	Tag      *[]string `form:"tag,omitempty" json:"tag,omitempty"`
	Facet    *[]string `form:"facet,omitempty" json:"facet,omitempty"`
	Limit    *int      `form:"limit,omitempty" json:"limit,omitempty"`

	// Before The made date of the last asset on the previous page. Send it with beforeId or not at all.
	Before *time.Time `form:"before,omitempty" json:"before,omitempty"`

	// BeforeId The id of that same asset
	BeforeId *openapi_types.UUID `form:"beforeId,omitempty" json:"beforeId,omitempty"`
}

// CreateAssetMultipartBody defines parameters for CreateAsset.
type CreateAssetMultipartBody struct {
	File     openapi_types.File `json:"file"`
	Metadata CreateAssetRequest `json:"metadata"`
}

// ChangeUnverifiedEmailJSONRequestBody defines body for ChangeUnverifiedEmail for application/json ContentType.
type ChangeUnverifiedEmailJSONRequestBody = ChangeEmailRequest

// RenameHandleJSONRequestBody defines body for RenameHandle for application/json ContentType.
type RenameHandleJSONRequestBody = RenameHandleRequest

// CreateAssetMultipartRequestBody defines body for CreateAsset for multipart/form-data ContentType.
type CreateAssetMultipartRequestBody CreateAssetMultipartBody

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody = SignInRequest

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = SignUpRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (PATCH /v1/account/email)
	ChangeUnverifiedEmail(c *gin.Context)

	// (PATCH /v1/account/handle)
	RenameHandle(c *gin.Context)

	// (GET /v1/assets)
	ListAssets(c *gin.Context, params ListAssetsParams)

	// (POST /v1/assets)
	CreateAsset(c *gin.Context)

	// (GET /v1/assets/{id}/original)
	DownloadOriginal(c *gin.Context, id openapi_types.UUID)

	// (GET /v1/auth/session)
	GetSession(c *gin.Context)

	// (POST /v1/auth/sign-in)
	SignIn(c *gin.Context)

	// (POST /v1/auth/sign-out)
	SignOut(c *gin.Context)

	// (POST /v1/auth/sign-up)
	SignUp(c *gin.Context)

	// (POST /v1/auth/verify-email)
	VerifyEmail(c *gin.Context)

	// (GET /v1/profiles/{handle})
	GetProfile(c *gin.Context, handle string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ChangeUnverifiedEmail operation middleware
func (siw *ServerInterfaceWrapper) ChangeUnverifiedEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ChangeUnverifiedEmail(c)
}

// RenameHandle operation middleware
func (siw *ServerInterfaceWrapper) RenameHandle(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RenameHandle(c)
}

// ListAssets operation middleware
func (siw *ServerInterfaceWrapper) ListAssets(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAssetsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", c.Request.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter kind: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "platform", c.Request.URL.Query(), &params.Platform, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", c.Request.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "facet" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "facet", c.Request.URL.Query(), &params.Facet, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter facet: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", c.Request.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter before: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "beforeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "beforeId", c.Request.URL.Query(), &params.BeforeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter beforeId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAssets(c, params)
}

// CreateAsset operation middleware
func (siw *ServerInterfaceWrapper) CreateAsset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAsset(c)
}

// DownloadOriginal operation middleware
func (siw *ServerInterfaceWrapper) DownloadOriginal(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DownloadOriginal(c, id)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSession(c)
}

// SignIn operation middleware
func (siw *ServerInterfaceWrapper) SignIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignIn(c)
}

// SignOut operation middleware
func (siw *ServerInterfaceWrapper) SignOut(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignOut(c)
}

// SignUp operation middleware
func (siw *ServerInterfaceWrapper) SignUp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignUp(c)
}

// VerifyEmail operation middleware
func (siw *ServerInterfaceWrapper) VerifyEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VerifyEmail(c)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "handle" -------------
	var handle string

	err = runtime.BindStyledParameterWithOptions("simple", "handle", c.Param("handle"), &handle, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter handle: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfile(c, handle)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.PATCH(options.BaseURL+"/v1/account/email", wrapper.ChangeUnverifiedEmail)
	router.PATCH(options.BaseURL+"/v1/account/handle", wrapper.RenameHandle)
	router.POST(options.BaseURL+"/v1/auth/sign-up", wrapper.SignUp)
	router.POST(options.BaseURL+"/v1/auth/sign-in", wrapper.SignIn)
	router.POST(options.BaseURL+"/v1/auth/sign-out", wrapper.SignOut)
	router.GET(options.BaseURL+"/v1/auth/session", wrapper.GetSession)
	router.POST(options.BaseURL+"/v1/auth/verify-email", wrapper.VerifyEmail)
	router.GET(options.BaseURL+"/v1/profiles/:handle", wrapper.GetProfile)
	router.GET(options.BaseURL+"/v1/assets", wrapper.ListAssets)
	router.POST(options.BaseURL+"/v1/assets", wrapper.CreateAsset)
	router.GET(options.BaseURL+"/v1/assets/:id/original", wrapper.DownloadOriginal)
}
