// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AddMediaRequestRole.
const (
	AddMediaRequestRoleAvatar           AddMediaRequestRole = "avatar"
	AddMediaRequestRoleAvatarAlt        AddMediaRequestRole = "avatar_alt"
	AddMediaRequestRoleExpression       AddMediaRequestRole = "expression"
	AddMediaRequestRoleGallery          AddMediaRequestRole = "gallery"
	AddMediaRequestRolePerspectiveLayer AddMediaRequestRole = "perspective_layer"
)

// Valid indicates whether the value is a known member of the AddMediaRequestRole enum.
func (e AddMediaRequestRole) Valid() bool {
	switch e {
	case AddMediaRequestRoleAvatar:
		return true
	case AddMediaRequestRoleAvatarAlt:
		return true
	case AddMediaRequestRoleExpression:
		return true
	case AddMediaRequestRoleGallery:
		return true
	case AddMediaRequestRolePerspectiveLayer:
		return true
	default:
		return false
	}
}

// Defines values for AssetDiscovery.
const (
	AssetDiscoveryListed   AssetDiscovery = "listed"
	AssetDiscoveryUnlisted AssetDiscovery = "unlisted"
)

// Valid indicates whether the value is a known member of the AssetDiscovery enum.
func (e AssetDiscovery) Valid() bool {
	switch e {
	case AssetDiscoveryListed:
		return true
	case AssetDiscoveryUnlisted:
		return true
	default:
		return false
	}
}

// Defines values for CompleteIngestRequestKind.
const (
	CompleteIngestRequestKindCharacter CompleteIngestRequestKind = "character"
	CompleteIngestRequestKindLorebook  CompleteIngestRequestKind = "lorebook"
	CompleteIngestRequestKindPreset    CompleteIngestRequestKind = "preset"
	CompleteIngestRequestKindTheme     CompleteIngestRequestKind = "theme"
)

// Valid indicates whether the value is a known member of the CompleteIngestRequestKind enum.
func (e CompleteIngestRequestKind) Valid() bool {
	switch e {
	case CompleteIngestRequestKindCharacter:
		return true
	case CompleteIngestRequestKindLorebook:
		return true
	case CompleteIngestRequestKindPreset:
		return true
	case CompleteIngestRequestKindTheme:
		return true
	default:
		return false
	}
}

// Defines values for CreateAssetRequestDiscovery.
const (
	CreateAssetRequestDiscoveryListed   CreateAssetRequestDiscovery = "listed"
	CreateAssetRequestDiscoveryUnlisted CreateAssetRequestDiscovery = "unlisted"
)

// Valid indicates whether the value is a known member of the CreateAssetRequestDiscovery enum.
func (e CreateAssetRequestDiscovery) Valid() bool {
	switch e {
	case CreateAssetRequestDiscoveryListed:
		return true
	case CreateAssetRequestDiscoveryUnlisted:
		return true
	default:
		return false
	}
}

// Defines values for IngestFailureReason.
const (
	InternalFailure    IngestFailureReason = "internal_failure"
	MalformedInput     IngestFailureReason = "malformed_input"
	SafetyViolation    IngestFailureReason = "safety_violation"
	UnsupportedFormat  IngestFailureReason = "unsupported_format"
	UnsupportedVersion IngestFailureReason = "unsupported_version"
)

// Valid indicates whether the value is a known member of the IngestFailureReason enum.
func (e IngestFailureReason) Valid() bool {
	switch e {
	case InternalFailure:
		return true
	case MalformedInput:
		return true
	case SafetyViolation:
		return true
	case UnsupportedFormat:
		return true
	case UnsupportedVersion:
		return true
	default:
		return false
	}
}

// Defines values for IngestOperationStatus.
const (
	IngestOperationStatusFailed     IngestOperationStatus = "failed"
	IngestOperationStatusNeedsKind  IngestOperationStatus = "needs_kind"
	IngestOperationStatusPending    IngestOperationStatus = "pending"
	IngestOperationStatusProcessing IngestOperationStatus = "processing"
	IngestOperationStatusSuccess    IngestOperationStatus = "success"
)

// Valid indicates whether the value is a known member of the IngestOperationStatus enum.
func (e IngestOperationStatus) Valid() bool {
	switch e {
	case IngestOperationStatusFailed:
		return true
	case IngestOperationStatusNeedsKind:
		return true
	case IngestOperationStatusPending:
		return true
	case IngestOperationStatusProcessing:
		return true
	case IngestOperationStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for MediaRole.
const (
	MediaRoleAvatar           MediaRole = "avatar"
	MediaRoleAvatarAlt        MediaRole = "avatar_alt"
	MediaRoleExpression       MediaRole = "expression"
	MediaRoleGallery          MediaRole = "gallery"
	MediaRolePerspectiveLayer MediaRole = "perspective_layer"
)

// Valid indicates whether the value is a known member of the MediaRole enum.
func (e MediaRole) Valid() bool {
	switch e {
	case MediaRoleAvatar:
		return true
	case MediaRoleAvatarAlt:
		return true
	case MediaRoleExpression:
		return true
	case MediaRoleGallery:
		return true
	case MediaRolePerspectiveLayer:
		return true
	default:
		return false
	}
}

// Defines values for NeedsKindKind.
const (
	NeedsKindKindCharacter   NeedsKindKind = "character"
	NeedsKindKindLessThannil NeedsKindKind = "<nil>"
	NeedsKindKindLorebook    NeedsKindKind = "lorebook"
	NeedsKindKindPreset      NeedsKindKind = "preset"
	NeedsKindKindTheme       NeedsKindKind = "theme"
)

// Valid indicates whether the value is a known member of the NeedsKindKind enum.
func (e NeedsKindKind) Valid() bool {
	switch e {
	case NeedsKindKindCharacter:
		return true
	case NeedsKindKindLessThannil:
		return true
	case NeedsKindKindLorebook:
		return true
	case NeedsKindKindPreset:
		return true
	case NeedsKindKindTheme:
		return true
	default:
		return false
	}
}

// Defines values for BeginDiscordParamsIntent.
const (
	Attach BeginDiscordParamsIntent = "attach"
	SignIn BeginDiscordParamsIntent = "sign-in"
)

// Valid indicates whether the value is a known member of the BeginDiscordParamsIntent enum.
func (e BeginDiscordParamsIntent) Valid() bool {
	switch e {
	case Attach:
		return true
	case SignIn:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	DiscordLinked bool                 `json:"discordLinked"`
	Email         *openapi_types.Email `json:"email"`
	EmailVerified bool                 `json:"emailVerified"`
	Handle        string               `json:"handle"`
	HasPassword   bool                 `json:"hasPassword"`
	Id            openapi_types.UUID   `json:"id"`
}

// AddMediaRequest defines model for AddMediaRequest.
type AddMediaRequest struct {
	Role AddMediaRequestRole `json:"role"`
}

// AddMediaRequestRole defines model for AddMediaRequest.Role.
type AddMediaRequestRole string

// Asset defines model for Asset.
type Asset struct {
	Blurb               string             `json:"blurb"`
	CreatedAt           time.Time          `json:"createdAt"`
	Discovery           AssetDiscovery     `json:"discovery"`
	Format              string             `json:"format"`
	Id                  openapi_types.UUID `json:"id"`
	IsNsfw              bool               `json:"isNsfw"`
	Kind                string             `json:"kind"`
	Name                string             `json:"name"`
	PassthroughPlatform *string            `json:"passthroughPlatform,omitempty"`
	Tags                []string           `json:"tags"`
}

// AssetDiscovery defines model for Asset.Discovery.
type AssetDiscovery string

// AssetList defines model for AssetList.
type AssetList struct {
	Items []Asset `json:"items"`
}

// ChangeEmailRequest defines model for ChangeEmailRequest.
type ChangeEmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// CompleteIngestRequest defines model for CompleteIngestRequest.
type CompleteIngestRequest struct {
	Kind CompleteIngestRequestKind `json:"kind"`
	Name string                    `json:"name"`
}

// CompleteIngestRequestKind defines model for CompleteIngestRequest.Kind.
type CompleteIngestRequestKind string

// CompletePasswordResetRequest defines model for CompletePasswordResetRequest.
type CompletePasswordResetRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// CreateAssetRequest defines model for CreateAssetRequest.
type CreateAssetRequest struct {
	Blurb     *string                      `json:"blurb,omitempty"`
	Confirmed bool                         `json:"confirmed"`
	Discovery *CreateAssetRequestDiscovery `json:"discovery,omitempty"`
	IsNsfw    *bool                        `json:"isNsfw,omitempty"`
	Name      *string                      `json:"name,omitempty"`
	Tags      *[]string                    `json:"tags,omitempty"`
}

// CreateAssetRequestDiscovery defines model for CreateAssetRequest.Discovery.
type CreateAssetRequestDiscovery string

// IngestFailure defines model for IngestFailure.
type IngestFailure struct {
	Message string              `json:"message"`
	Reason  IngestFailureReason `json:"reason"`
}

// IngestFailureReason defines model for IngestFailure.Reason.
type IngestFailureReason string

// IngestOperation defines model for IngestOperation.
type IngestOperation struct {
	Asset     *Asset                `json:"asset,omitempty"`
	Failure   *IngestFailure        `json:"failure,omitempty"`
	Id        openapi_types.UUID    `json:"id"`
	NeedsKind *NeedsKind            `json:"needsKind,omitempty"`
	Status    IngestOperationStatus `json:"status"`
	Url       string                `json:"url"`
}

// IngestOperationStatus defines model for IngestOperation.Status.
type IngestOperationStatus string

// Media defines model for Media.
type Media struct {
	AssetId           *openapi_types.UUID `json:"assetId"`
	DerivativeVersion int                 `json:"derivativeVersion"`
	Height            int                 `json:"height"`
	Id                openapi_types.UUID  `json:"id"`
	RevisionId        *openapi_types.UUID `json:"revisionId"`
	Role              MediaRole           `json:"role"`
	Width             int                 `json:"width"`
}

// MediaRole defines model for Media.Role.
type MediaRole string

// MediaList defines model for MediaList.
type MediaList struct {
	Items []Media `json:"items"`
}

// NeedsKind defines model for NeedsKind.
type NeedsKind struct {
	Kind *NeedsKindKind `json:"kind"`
	Name string         `json:"name"`
}

// NeedsKindKind defines model for NeedsKind.Kind.
type NeedsKindKind string

// PasswordRequest defines model for PasswordRequest.
type PasswordRequest struct {
	Password string `json:"password"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// Profile defines model for Profile.
type Profile struct {
	Handle string             `json:"handle"`
	Id     openapi_types.UUID `json:"id"`
}

// RenameHandleRequest defines model for RenameHandleRequest.
type RenameHandleRequest struct {
	Handle string `json:"handle"`
}

// SessionState defines model for SessionState.
type SessionState struct {
	User *Account `json:"user"`
}

// SignInRequest defines model for SignInRequest.
type SignInRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	Email    openapi_types.Email `json:"email"`
	Handle   string              `json:"handle"`
	Password string              `json:"password"`
}

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Token string `json:"token"`
}

// ListAssetsParams defines parameters for ListAssets.
type ListAssetsParams struct {
	Kind     *string   `form:"kind,omitempty" json:"kind,omitempty"`
	Platform *string   `form:"platform,omitempty" json:"platform,omitempty"`
	Tag      *[]string `form:"tag,omitempty" json:"tag,omitempty"`
	Facet    *[]string `form:"facet,omitempty" json:"facet,omitempty"`
	Limit    *int      `form:"limit,omitempty" json:"limit,omitempty"`

	// Before The made date of the last asset on the previous page. Send it with beforeId or not at all.
	Before *time.Time `form:"before,omitempty" json:"before,omitempty"`

	// BeforeId The id of that same asset
	BeforeId *openapi_types.UUID `form:"beforeId,omitempty" json:"beforeId,omitempty"`
}

// CreateAssetMultipartBody defines parameters for CreateAsset.
type CreateAssetMultipartBody struct {
	File     openapi_types.File `json:"file"`
	Metadata CreateAssetRequest `json:"metadata"`
}

// AddMediaMultipartBody defines parameters for AddMedia.
type AddMediaMultipartBody struct {
	File     openapi_types.File `json:"file"`
	Metadata AddMediaRequest    `json:"metadata"`
}

// BeginDiscordParams defines parameters for BeginDiscord.
type BeginDiscordParams struct {
	Intent *BeginDiscordParamsIntent `form:"intent,omitempty" json:"intent,omitempty"`
}

// BeginDiscordParamsIntent defines parameters for BeginDiscord.
type BeginDiscordParamsIntent string

// CompleteDiscordParams defines parameters for CompleteDiscord.
type CompleteDiscordParams struct {
	State string  `form:"state" json:"state"`
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// ChangeUnverifiedEmailJSONRequestBody defines body for ChangeUnverifiedEmail for application/json ContentType.
type ChangeUnverifiedEmailJSONRequestBody = ChangeEmailRequest

// RenameHandleJSONRequestBody defines body for RenameHandle for application/json ContentType.
type RenameHandleJSONRequestBody = RenameHandleRequest

// SetPasswordJSONRequestBody defines body for SetPassword for application/json ContentType.
type SetPasswordJSONRequestBody = PasswordRequest

// CreateAssetMultipartRequestBody defines body for CreateAsset for multipart/form-data ContentType.
type CreateAssetMultipartRequestBody CreateAssetMultipartBody

// AddMediaMultipartRequestBody defines body for AddMedia for multipart/form-data ContentType.
type AddMediaMultipartRequestBody AddMediaMultipartBody

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// CompletePasswordResetJSONRequestBody defines body for CompletePasswordReset for application/json ContentType.
type CompletePasswordResetJSONRequestBody = CompletePasswordResetRequest

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody = SignInRequest

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = SignUpRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest

// CompleteIngestJSONRequestBody defines body for CompleteIngest for application/json ContentType.
type CompleteIngestJSONRequestBody = CompleteIngestRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /download/{id})
	DownloadSource(c *gin.Context, id openapi_types.UUID)

	// (GET /media/{media_id}/{variant}/{derivative_version})
	GetMediaVariant(c *gin.Context, mediaId openapi_types.UUID, variant string, derivativeVersion int)

	// (DELETE /v1/account/discord)
	DetachDiscord(c *gin.Context)

	// (PATCH /v1/account/email)
	ChangeUnverifiedEmail(c *gin.Context)

	// (PATCH /v1/account/handle)
	RenameHandle(c *gin.Context)

	// (PUT /v1/account/password)
	SetPassword(c *gin.Context)

	// (GET /v1/assets)
	ListAssets(c *gin.Context, params ListAssetsParams)

	// (POST /v1/assets)
	CreateAsset(c *gin.Context)

	// (GET /v1/assets/{id}/media)
	ListMedia(c *gin.Context, id openapi_types.UUID)

	// (POST /v1/assets/{id}/media)
	AddMedia(c *gin.Context, id openapi_types.UUID)

	// (GET /v1/auth/discord)
	BeginDiscord(c *gin.Context, params BeginDiscordParams)

	// (GET /v1/auth/discord/callback)
	CompleteDiscord(c *gin.Context, params CompleteDiscordParams)

	// (POST /v1/auth/password-reset)
	RequestPasswordReset(c *gin.Context)

	// (POST /v1/auth/password-reset/complete)
	CompletePasswordReset(c *gin.Context)

	// (GET /v1/auth/session)
	GetSession(c *gin.Context)

	// (POST /v1/auth/sign-in)
	SignIn(c *gin.Context)

	// (POST /v1/auth/sign-out)
	SignOut(c *gin.Context)

	// (POST /v1/auth/sign-up)
	SignUp(c *gin.Context)

	// (POST /v1/auth/verify-email)
	VerifyEmail(c *gin.Context)

	// (GET /v1/ingests/{id})
	GetIngest(c *gin.Context, id openapi_types.UUID)

	// (PATCH /v1/ingests/{id})
	CompleteIngest(c *gin.Context, id openapi_types.UUID)

	// (GET /v1/profiles/{handle})
	GetProfile(c *gin.Context, handle string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// DownloadSource operation middleware
func (siw *ServerInterfaceWrapper) DownloadSource(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DownloadSource(c, id)
}

// GetMediaVariant operation middleware
func (siw *ServerInterfaceWrapper) GetMediaVariant(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "media_id" -------------
	var mediaId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "media_id", c.Param("media_id"), &mediaId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter media_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "variant" -------------
	var variant string

	err = runtime.BindStyledParameterWithOptions("simple", "variant", c.Param("variant"), &variant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter variant: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "derivative_version" -------------
	var derivativeVersion int

	err = runtime.BindStyledParameterWithOptions("simple", "derivative_version", c.Param("derivative_version"), &derivativeVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter derivative_version: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMediaVariant(c, mediaId, variant, derivativeVersion)
}

// DetachDiscord operation middleware
func (siw *ServerInterfaceWrapper) DetachDiscord(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DetachDiscord(c)
}

// ChangeUnverifiedEmail operation middleware
func (siw *ServerInterfaceWrapper) ChangeUnverifiedEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ChangeUnverifiedEmail(c)
}

// RenameHandle operation middleware
func (siw *ServerInterfaceWrapper) RenameHandle(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RenameHandle(c)
}

// SetPassword operation middleware
func (siw *ServerInterfaceWrapper) SetPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetPassword(c)
}

// ListAssets operation middleware
func (siw *ServerInterfaceWrapper) ListAssets(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAssetsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", c.Request.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter kind: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "platform", c.Request.URL.Query(), &params.Platform, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", c.Request.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tag: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "facet" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "facet", c.Request.URL.Query(), &params.Facet, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter facet: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", c.Request.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter before: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "beforeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "beforeId", c.Request.URL.Query(), &params.BeforeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter beforeId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAssets(c, params)
}

// CreateAsset operation middleware
func (siw *ServerInterfaceWrapper) CreateAsset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAsset(c)
}

// ListMedia operation middleware
func (siw *ServerInterfaceWrapper) ListMedia(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMedia(c, id)
}

// AddMedia operation middleware
func (siw *ServerInterfaceWrapper) AddMedia(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddMedia(c, id)
}

// BeginDiscord operation middleware
func (siw *ServerInterfaceWrapper) BeginDiscord(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params BeginDiscordParams

	// ------------- Optional query parameter "intent" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "intent", c.Request.URL.Query(), &params.Intent, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter intent: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BeginDiscord(c, params)
}

// CompleteDiscord operation middleware
func (siw *ServerInterfaceWrapper) CompleteDiscord(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteDiscordParams

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", c.Request.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", c.Request.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", c.Request.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter error: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteDiscord(c, params)
}

// RequestPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) RequestPasswordReset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestPasswordReset(c)
}

// CompletePasswordReset operation middleware
func (siw *ServerInterfaceWrapper) CompletePasswordReset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompletePasswordReset(c)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSession(c)
}

// SignIn operation middleware
func (siw *ServerInterfaceWrapper) SignIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignIn(c)
}

// SignOut operation middleware
func (siw *ServerInterfaceWrapper) SignOut(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignOut(c)
}

// SignUp operation middleware
func (siw *ServerInterfaceWrapper) SignUp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignUp(c)
}

// VerifyEmail operation middleware
func (siw *ServerInterfaceWrapper) VerifyEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VerifyEmail(c)
}

// GetIngest operation middleware
func (siw *ServerInterfaceWrapper) GetIngest(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetIngest(c, id)
}

// CompleteIngest operation middleware
func (siw *ServerInterfaceWrapper) CompleteIngest(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteIngest(c, id)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "handle" -------------
	var handle string

	err = runtime.BindStyledParameterWithOptions("simple", "handle", c.Param("handle"), &handle, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter handle: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfile(c, handle)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/v1/account/discord", wrapper.DetachDiscord)
	router.PATCH(options.BaseURL+"/v1/account/email", wrapper.ChangeUnverifiedEmail)
	router.PATCH(options.BaseURL+"/v1/account/handle", wrapper.RenameHandle)
	router.PUT(options.BaseURL+"/v1/account/password", wrapper.SetPassword)
	router.POST(options.BaseURL+"/v1/auth/sign-up", wrapper.SignUp)
	router.POST(options.BaseURL+"/v1/auth/sign-in", wrapper.SignIn)
	router.GET(options.BaseURL+"/v1/auth/discord", wrapper.BeginDiscord)
	router.GET(options.BaseURL+"/v1/auth/discord/callback", wrapper.CompleteDiscord)
	router.POST(options.BaseURL+"/v1/auth/sign-out", wrapper.SignOut)
	router.GET(options.BaseURL+"/v1/auth/session", wrapper.GetSession)
	router.POST(options.BaseURL+"/v1/auth/verify-email", wrapper.VerifyEmail)
	router.POST(options.BaseURL+"/v1/auth/password-reset", wrapper.RequestPasswordReset)
	router.POST(options.BaseURL+"/v1/auth/password-reset/complete", wrapper.CompletePasswordReset)
	router.GET(options.BaseURL+"/v1/profiles/:handle", wrapper.GetProfile)
	router.GET(options.BaseURL+"/v1/assets", wrapper.ListAssets)
	router.POST(options.BaseURL+"/v1/assets", wrapper.CreateAsset)
	router.GET(options.BaseURL+"/download/:id", wrapper.DownloadSource)
	router.GET(options.BaseURL+"/v1/assets/:id/media", wrapper.ListMedia)
	router.POST(options.BaseURL+"/v1/assets/:id/media", wrapper.AddMedia)
	router.GET(options.BaseURL+"/media/:media_id/:variant/:derivative_version", wrapper.GetMediaVariant)
	router.GET(options.BaseURL+"/v1/ingests/:id", wrapper.GetIngest)
	router.PATCH(options.BaseURL+"/v1/ingests/:id", wrapper.CompleteIngest)
}
