// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package http

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountRole.
const (
	Admin     AccountRole = "admin"
	Moderator AccountRole = "moderator"
	User      AccountRole = "user"
)

// Valid indicates whether the value is a known member of the AccountRole enum.
func (e AccountRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Moderator:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for AddMediaRequestRole.
const (
	AddMediaRequestRoleAvatar           AddMediaRequestRole = "avatar"
	AddMediaRequestRoleAvatarAlt        AddMediaRequestRole = "avatar_alt"
	AddMediaRequestRoleExpression       AddMediaRequestRole = "expression"
	AddMediaRequestRoleGallery          AddMediaRequestRole = "gallery"
	AddMediaRequestRolePerspectiveLayer AddMediaRequestRole = "perspective_layer"
)

// Valid indicates whether the value is a known member of the AddMediaRequestRole enum.
func (e AddMediaRequestRole) Valid() bool {
	switch e {
	case AddMediaRequestRoleAvatar:
		return true
	case AddMediaRequestRoleAvatarAlt:
		return true
	case AddMediaRequestRoleExpression:
		return true
	case AddMediaRequestRoleGallery:
		return true
	case AddMediaRequestRolePerspectiveLayer:
		return true
	default:
		return false
	}
}

// Defines values for AddableSectionGroup.
const (
	File   AddableSectionGroup = "file"
	Other  AddableSectionGroup = "other"
	Reader AddableSectionGroup = "reader"
	Work   AddableSectionGroup = "work"
)

// Valid indicates whether the value is a known member of the AddableSectionGroup enum.
func (e AddableSectionGroup) Valid() bool {
	switch e {
	case File:
		return true
	case Other:
		return true
	case Reader:
		return true
	case Work:
		return true
	default:
		return false
	}
}

// Defines values for ArrangeAssetBlocksRequestBlocksWidth.
const (
	ArrangeAssetBlocksRequestBlocksWidthFull      ArrangeAssetBlocksRequestBlocksWidth = "full"
	ArrangeAssetBlocksRequestBlocksWidthHalf      ArrangeAssetBlocksRequestBlocksWidth = "half"
	ArrangeAssetBlocksRequestBlocksWidthThird     ArrangeAssetBlocksRequestBlocksWidth = "third"
	ArrangeAssetBlocksRequestBlocksWidthTwoThirds ArrangeAssetBlocksRequestBlocksWidth = "two_thirds"
)

// Valid indicates whether the value is a known member of the ArrangeAssetBlocksRequestBlocksWidth enum.
func (e ArrangeAssetBlocksRequestBlocksWidth) Valid() bool {
	switch e {
	case ArrangeAssetBlocksRequestBlocksWidthFull:
		return true
	case ArrangeAssetBlocksRequestBlocksWidthHalf:
		return true
	case ArrangeAssetBlocksRequestBlocksWidthThird:
		return true
	case ArrangeAssetBlocksRequestBlocksWidthTwoThirds:
		return true
	default:
		return false
	}
}

// Defines values for AssetDiscovery.
const (
	AssetDiscoveryListed   AssetDiscovery = "listed"
	AssetDiscoveryUnlisted AssetDiscovery = "unlisted"
)

// Valid indicates whether the value is a known member of the AssetDiscovery enum.
func (e AssetDiscovery) Valid() bool {
	switch e {
	case AssetDiscoveryListed:
		return true
	case AssetDiscoveryUnlisted:
		return true
	default:
		return false
	}
}

// Defines values for AssetBlockAllowedLayouts.
const (
	AssetBlockAllowedLayoutsDuo       AssetBlockAllowedLayouts = "duo"
	AssetBlockAllowedLayoutsMainAside AssetBlockAllowedLayouts = "main-aside"
	AssetBlockAllowedLayoutsSingle    AssetBlockAllowedLayouts = "single"
	AssetBlockAllowedLayoutsStack2    AssetBlockAllowedLayouts = "stack-2"
	AssetBlockAllowedLayoutsStack3    AssetBlockAllowedLayouts = "stack-3"
	AssetBlockAllowedLayoutsTrio      AssetBlockAllowedLayouts = "trio"
)

// Valid indicates whether the value is a known member of the AssetBlockAllowedLayouts enum.
func (e AssetBlockAllowedLayouts) Valid() bool {
	switch e {
	case AssetBlockAllowedLayoutsDuo:
		return true
	case AssetBlockAllowedLayoutsMainAside:
		return true
	case AssetBlockAllowedLayoutsSingle:
		return true
	case AssetBlockAllowedLayoutsStack2:
		return true
	case AssetBlockAllowedLayoutsStack3:
		return true
	case AssetBlockAllowedLayoutsTrio:
		return true
	default:
		return false
	}
}

// Defines values for AssetBlockLayout.
const (
	AssetBlockLayoutDuo       AssetBlockLayout = "duo"
	AssetBlockLayoutMainAside AssetBlockLayout = "main-aside"
	AssetBlockLayoutSingle    AssetBlockLayout = "single"
	AssetBlockLayoutStack2    AssetBlockLayout = "stack-2"
	AssetBlockLayoutStack3    AssetBlockLayout = "stack-3"
	AssetBlockLayoutTrio      AssetBlockLayout = "trio"
)

// Valid indicates whether the value is a known member of the AssetBlockLayout enum.
func (e AssetBlockLayout) Valid() bool {
	switch e {
	case AssetBlockLayoutDuo:
		return true
	case AssetBlockLayoutMainAside:
		return true
	case AssetBlockLayoutSingle:
		return true
	case AssetBlockLayoutStack2:
		return true
	case AssetBlockLayoutStack3:
		return true
	case AssetBlockLayoutTrio:
		return true
	default:
		return false
	}
}

// Defines values for AssetBlockWidth.
const (
	AssetBlockWidthFull      AssetBlockWidth = "full"
	AssetBlockWidthHalf      AssetBlockWidth = "half"
	AssetBlockWidthThird     AssetBlockWidth = "third"
	AssetBlockWidthTwoThirds AssetBlockWidth = "two_thirds"
)

// Valid indicates whether the value is a known member of the AssetBlockWidth enum.
func (e AssetBlockWidth) Valid() bool {
	switch e {
	case AssetBlockWidthFull:
		return true
	case AssetBlockWidthHalf:
		return true
	case AssetBlockWidthThird:
		return true
	case AssetBlockWidthTwoThirds:
		return true
	default:
		return false
	}
}

// Defines values for AssetDetailDiscovery.
const (
	AssetDetailDiscoveryListed   AssetDetailDiscovery = "listed"
	AssetDetailDiscoveryUnlisted AssetDetailDiscovery = "unlisted"
)

// Valid indicates whether the value is a known member of the AssetDetailDiscovery enum.
func (e AssetDetailDiscovery) Valid() bool {
	switch e {
	case AssetDetailDiscoveryListed:
		return true
	case AssetDetailDiscoveryUnlisted:
		return true
	default:
		return false
	}
}

// Defines values for AssetDetailKind.
const (
	AssetDetailKindCharacter AssetDetailKind = "character"
	AssetDetailKindLorebook  AssetDetailKind = "lorebook"
	AssetDetailKindPreset    AssetDetailKind = "preset"
	AssetDetailKindTheme     AssetDetailKind = "theme"
)

// Valid indicates whether the value is a known member of the AssetDetailKind enum.
func (e AssetDetailKind) Valid() bool {
	switch e {
	case AssetDetailKindCharacter:
		return true
	case AssetDetailKindLorebook:
		return true
	case AssetDetailKindPreset:
		return true
	case AssetDetailKindTheme:
		return true
	default:
		return false
	}
}

// Defines values for AssetDetailLifecycle.
const (
	AssetDetailLifecycleDraft     AssetDetailLifecycle = "draft"
	AssetDetailLifecyclePublished AssetDetailLifecycle = "published"
)

// Valid indicates whether the value is a known member of the AssetDetailLifecycle enum.
func (e AssetDetailLifecycle) Valid() bool {
	switch e {
	case AssetDetailLifecycleDraft:
		return true
	case AssetDetailLifecyclePublished:
		return true
	default:
		return false
	}
}

// Defines values for AssetDetailVisibility.
const (
	AssetDetailVisibilityBlurred AssetDetailVisibility = "blurred"
	AssetDetailVisibilityHidden  AssetDetailVisibility = "hidden"
	AssetDetailVisibilityShown   AssetDetailVisibility = "shown"
)

// Valid indicates whether the value is a known member of the AssetDetailVisibility enum.
func (e AssetDetailVisibility) Valid() bool {
	switch e {
	case AssetDetailVisibilityBlurred:
		return true
	case AssetDetailVisibilityHidden:
		return true
	case AssetDetailVisibilityShown:
		return true
	default:
		return false
	}
}

// Defines values for AssetDiscoveryRequestDiscovery.
const (
	AssetDiscoveryRequestDiscoveryListed   AssetDiscoveryRequestDiscovery = "listed"
	AssetDiscoveryRequestDiscoveryUnlisted AssetDiscoveryRequestDiscovery = "unlisted"
)

// Valid indicates whether the value is a known member of the AssetDiscoveryRequestDiscovery enum.
func (e AssetDiscoveryRequestDiscovery) Valid() bool {
	switch e {
	case AssetDiscoveryRequestDiscoveryListed:
		return true
	case AssetDiscoveryRequestDiscoveryUnlisted:
		return true
	default:
		return false
	}
}

// Defines values for AssetElementDisplay.
const (
	AssetElementDisplayRich     AssetElementDisplay = "rich"
	AssetElementDisplayVerbatim AssetElementDisplay = "verbatim"
)

// Valid indicates whether the value is a known member of the AssetElementDisplay enum.
func (e AssetElementDisplay) Valid() bool {
	switch e {
	case AssetElementDisplayRich:
		return true
	case AssetElementDisplayVerbatim:
		return true
	default:
		return false
	}
}

// Defines values for AssetImageRole.
const (
	AssetImageRoleAvatar           AssetImageRole = "avatar"
	AssetImageRoleAvatarAlt        AssetImageRole = "avatar_alt"
	AssetImageRoleExpression       AssetImageRole = "expression"
	AssetImageRoleGallery          AssetImageRole = "gallery"
	AssetImageRolePerspectiveLayer AssetImageRole = "perspective_layer"
)

// Valid indicates whether the value is a known member of the AssetImageRole enum.
func (e AssetImageRole) Valid() bool {
	switch e {
	case AssetImageRoleAvatar:
		return true
	case AssetImageRoleAvatarAlt:
		return true
	case AssetImageRoleExpression:
		return true
	case AssetImageRoleGallery:
		return true
	case AssetImageRolePerspectiveLayer:
		return true
	default:
		return false
	}
}

// Defines values for AssetListEmptyState.
const (
	Catalog     AssetListEmptyState = "catalog"
	LessThannil AssetListEmptyState = "<nil>"
	NoMatches   AssetListEmptyState = "no_matches"
	Suppressed  AssetListEmptyState = "suppressed"
)

// Valid indicates whether the value is a known member of the AssetListEmptyState enum.
func (e AssetListEmptyState) Valid() bool {
	switch e {
	case Catalog:
		return true
	case LessThannil:
		return true
	case NoMatches:
		return true
	case Suppressed:
		return true
	default:
		return false
	}
}

// Defines values for AssetListVisibility.
const (
	AssetListVisibilityBlurred AssetListVisibility = "blurred"
	AssetListVisibilityHidden  AssetListVisibility = "hidden"
	AssetListVisibilityShown   AssetListVisibility = "shown"
)

// Valid indicates whether the value is a known member of the AssetListVisibility enum.
func (e AssetListVisibility) Valid() bool {
	switch e {
	case AssetListVisibilityBlurred:
		return true
	case AssetListVisibilityHidden:
		return true
	case AssetListVisibilityShown:
		return true
	default:
		return false
	}
}

// Defines values for BrowseAssetKind.
const (
	BrowseAssetKindCharacter BrowseAssetKind = "character"
	BrowseAssetKindLorebook  BrowseAssetKind = "lorebook"
	BrowseAssetKindPreset    BrowseAssetKind = "preset"
	BrowseAssetKindTheme     BrowseAssetKind = "theme"
)

// Valid indicates whether the value is a known member of the BrowseAssetKind enum.
func (e BrowseAssetKind) Valid() bool {
	switch e {
	case BrowseAssetKindCharacter:
		return true
	case BrowseAssetKindLorebook:
		return true
	case BrowseAssetKindPreset:
		return true
	case BrowseAssetKindTheme:
		return true
	default:
		return false
	}
}

// Defines values for BrowseAssetOwnerState.
const (
	BrowseAssetOwnerStateDraft    BrowseAssetOwnerState = "draft"
	BrowseAssetOwnerStateUnlisted BrowseAssetOwnerState = "unlisted"
	BrowseAssetOwnerStateWithheld BrowseAssetOwnerState = "withheld"
)

// Valid indicates whether the value is a known member of the BrowseAssetOwnerState enum.
func (e BrowseAssetOwnerState) Valid() bool {
	switch e {
	case BrowseAssetOwnerStateDraft:
		return true
	case BrowseAssetOwnerStateUnlisted:
		return true
	case BrowseAssetOwnerStateWithheld:
		return true
	default:
		return false
	}
}

// Defines values for CreateAssetRequestDiscovery.
const (
	CreateAssetRequestDiscoveryListed   CreateAssetRequestDiscovery = "listed"
	CreateAssetRequestDiscoveryUnlisted CreateAssetRequestDiscovery = "unlisted"
)

// Valid indicates whether the value is a known member of the CreateAssetRequestDiscovery enum.
func (e CreateAssetRequestDiscovery) Valid() bool {
	switch e {
	case CreateAssetRequestDiscoveryListed:
		return true
	case CreateAssetRequestDiscoveryUnlisted:
		return true
	default:
		return false
	}
}

// Defines values for DeletedAssetKind.
const (
	DeletedAssetKindCharacter DeletedAssetKind = "character"
	DeletedAssetKindLorebook  DeletedAssetKind = "lorebook"
	DeletedAssetKindPreset    DeletedAssetKind = "preset"
	DeletedAssetKindTheme     DeletedAssetKind = "theme"
)

// Valid indicates whether the value is a known member of the DeletedAssetKind enum.
func (e DeletedAssetKind) Valid() bool {
	switch e {
	case DeletedAssetKindCharacter:
		return true
	case DeletedAssetKindLorebook:
		return true
	case DeletedAssetKindPreset:
		return true
	case DeletedAssetKindTheme:
		return true
	default:
		return false
	}
}

// Defines values for ElementType.
const (
	DialogueSample ElementType = "dialogue_sample"
	EntryTable     ElementType = "entry_table"
	FieldList      ElementType = "field_list"
	ImageSet       ElementType = "image_set"
	LinkList       ElementType = "link_list"
	Prose          ElementType = "prose"
	TextSet        ElementType = "text_set"
)

// Valid indicates whether the value is a known member of the ElementType enum.
func (e ElementType) Valid() bool {
	switch e {
	case DialogueSample:
		return true
	case EntryTable:
		return true
	case FieldList:
		return true
	case ImageSet:
		return true
	case LinkList:
		return true
	case Prose:
		return true
	case TextSet:
		return true
	default:
		return false
	}
}

// Defines values for EntryTableContentEntriesPosition.
const (
	AfterCharacter  EntryTableContentEntriesPosition = "after_character"
	BeforeCharacter EntryTableContentEntriesPosition = "before_character"
)

// Valid indicates whether the value is a known member of the EntryTableContentEntriesPosition enum.
func (e EntryTableContentEntriesPosition) Valid() bool {
	switch e {
	case AfterCharacter:
		return true
	case BeforeCharacter:
		return true
	default:
		return false
	}
}

// Defines values for IngestFailureReason.
const (
	InternalFailure    IngestFailureReason = "internal_failure"
	MalformedInput     IngestFailureReason = "malformed_input"
	SafetyViolation    IngestFailureReason = "safety_violation"
	UnsupportedFormat  IngestFailureReason = "unsupported_format"
	UnsupportedVersion IngestFailureReason = "unsupported_version"
	WrongKind          IngestFailureReason = "wrong_kind"
)

// Valid indicates whether the value is a known member of the IngestFailureReason enum.
func (e IngestFailureReason) Valid() bool {
	switch e {
	case InternalFailure:
		return true
	case MalformedInput:
		return true
	case SafetyViolation:
		return true
	case UnsupportedFormat:
		return true
	case UnsupportedVersion:
		return true
	case WrongKind:
		return true
	default:
		return false
	}
}

// Defines values for IngestOperationStatus.
const (
	IngestOperationStatusFailed     IngestOperationStatus = "failed"
	IngestOperationStatusPending    IngestOperationStatus = "pending"
	IngestOperationStatusProcessing IngestOperationStatus = "processing"
	IngestOperationStatusSuccess    IngestOperationStatus = "success"
)

// Valid indicates whether the value is a known member of the IngestOperationStatus enum.
func (e IngestOperationStatus) Valid() bool {
	switch e {
	case IngestOperationStatusFailed:
		return true
	case IngestOperationStatusPending:
		return true
	case IngestOperationStatusProcessing:
		return true
	case IngestOperationStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ItemSize.
const (
	Large  ItemSize = "large"
	Medium ItemSize = "medium"
	Small  ItemSize = "small"
)

// Valid indicates whether the value is a known member of the ItemSize enum.
func (e ItemSize) Valid() bool {
	switch e {
	case Large:
		return true
	case Medium:
		return true
	case Small:
		return true
	default:
		return false
	}
}

// Defines values for LinkPollResultStatus.
const (
	LinkPollResultStatusLinked  LinkPollResultStatus = "linked"
	LinkPollResultStatusPending LinkPollResultStatus = "pending"
)

// Valid indicates whether the value is a known member of the LinkPollResultStatus enum.
func (e LinkPollResultStatus) Valid() bool {
	switch e {
	case LinkPollResultStatusLinked:
		return true
	case LinkPollResultStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for MediaRole.
const (
	MediaRoleAvatar           MediaRole = "avatar"
	MediaRoleAvatarAlt        MediaRole = "avatar_alt"
	MediaRoleExpression       MediaRole = "expression"
	MediaRoleGallery          MediaRole = "gallery"
	MediaRolePerspectiveLayer MediaRole = "perspective_layer"
)

// Valid indicates whether the value is a known member of the MediaRole enum.
func (e MediaRole) Valid() bool {
	switch e {
	case MediaRoleAvatar:
		return true
	case MediaRoleAvatarAlt:
		return true
	case MediaRoleExpression:
		return true
	case MediaRoleGallery:
		return true
	case MediaRolePerspectiveLayer:
		return true
	default:
		return false
	}
}

// Defines values for NsfwVisibilityRequestVisibility.
const (
	NsfwVisibilityRequestVisibilityBlurred NsfwVisibilityRequestVisibility = "blurred"
	NsfwVisibilityRequestVisibilityHidden  NsfwVisibilityRequestVisibility = "hidden"
	NsfwVisibilityRequestVisibilityShown   NsfwVisibilityRequestVisibility = "shown"
)

// Valid indicates whether the value is a known member of the NsfwVisibilityRequestVisibility enum.
func (e NsfwVisibilityRequestVisibility) Valid() bool {
	switch e {
	case NsfwVisibilityRequestVisibilityBlurred:
		return true
	case NsfwVisibilityRequestVisibilityHidden:
		return true
	case NsfwVisibilityRequestVisibilityShown:
		return true
	default:
		return false
	}
}

// Defines values for SaveAssetBlockRequestLayout.
const (
	SaveAssetBlockRequestLayoutDuo       SaveAssetBlockRequestLayout = "duo"
	SaveAssetBlockRequestLayoutMainAside SaveAssetBlockRequestLayout = "main-aside"
	SaveAssetBlockRequestLayoutSingle    SaveAssetBlockRequestLayout = "single"
	SaveAssetBlockRequestLayoutStack2    SaveAssetBlockRequestLayout = "stack-2"
	SaveAssetBlockRequestLayoutStack3    SaveAssetBlockRequestLayout = "stack-3"
	SaveAssetBlockRequestLayoutTrio      SaveAssetBlockRequestLayout = "trio"
)

// Valid indicates whether the value is a known member of the SaveAssetBlockRequestLayout enum.
func (e SaveAssetBlockRequestLayout) Valid() bool {
	switch e {
	case SaveAssetBlockRequestLayoutDuo:
		return true
	case SaveAssetBlockRequestLayoutMainAside:
		return true
	case SaveAssetBlockRequestLayoutSingle:
		return true
	case SaveAssetBlockRequestLayoutStack2:
		return true
	case SaveAssetBlockRequestLayoutStack3:
		return true
	case SaveAssetBlockRequestLayoutTrio:
		return true
	default:
		return false
	}
}

// Defines values for SaveAssetBlockRequestWidth.
const (
	SaveAssetBlockRequestWidthFull      SaveAssetBlockRequestWidth = "full"
	SaveAssetBlockRequestWidthHalf      SaveAssetBlockRequestWidth = "half"
	SaveAssetBlockRequestWidthThird     SaveAssetBlockRequestWidth = "third"
	SaveAssetBlockRequestWidthTwoThirds SaveAssetBlockRequestWidth = "two_thirds"
)

// Valid indicates whether the value is a known member of the SaveAssetBlockRequestWidth enum.
func (e SaveAssetBlockRequestWidth) Valid() bool {
	switch e {
	case SaveAssetBlockRequestWidthFull:
		return true
	case SaveAssetBlockRequestWidthHalf:
		return true
	case SaveAssetBlockRequestWidthThird:
		return true
	case SaveAssetBlockRequestWidthTwoThirds:
		return true
	default:
		return false
	}
}

// Defines values for SaveAssetElementDisplay.
const (
	SaveAssetElementDisplayRich     SaveAssetElementDisplay = "rich"
	SaveAssetElementDisplayVerbatim SaveAssetElementDisplay = "verbatim"
)

// Valid indicates whether the value is a known member of the SaveAssetElementDisplay enum.
func (e SaveAssetElementDisplay) Valid() bool {
	switch e {
	case SaveAssetElementDisplayRich:
		return true
	case SaveAssetElementDisplayVerbatim:
		return true
	default:
		return false
	}
}

// Defines values for Scope.
const (
	AssetReceive Scope = "asset:receive"
	LibrarySync  Scope = "library:sync"
)

// Valid indicates whether the value is a known member of the Scope enum.
func (e Scope) Valid() bool {
	switch e {
	case AssetReceive:
		return true
	case LibrarySync:
		return true
	default:
		return false
	}
}

// Defines values for GetMediaVariantParamsVariant.
const (
	Detail        GetMediaVariantParamsVariant = "detail"
	DetailBlurred GetMediaVariantParamsVariant = "detail_blurred"
	Grid          GetMediaVariantParamsVariant = "grid"
	GridBlurred   GetMediaVariantParamsVariant = "grid_blurred"
	Og            GetMediaVariantParamsVariant = "og"
	OgBlurred     GetMediaVariantParamsVariant = "og_blurred"
	Thumb         GetMediaVariantParamsVariant = "thumb"
	ThumbBlurred  GetMediaVariantParamsVariant = "thumb_blurred"
)

// Valid indicates whether the value is a known member of the GetMediaVariantParamsVariant enum.
func (e GetMediaVariantParamsVariant) Valid() bool {
	switch e {
	case Detail:
		return true
	case DetailBlurred:
		return true
	case Grid:
		return true
	case GridBlurred:
		return true
	case Og:
		return true
	case OgBlurred:
		return true
	case Thumb:
		return true
	case ThumbBlurred:
		return true
	default:
		return false
	}
}

// Defines values for ListAssetsParamsKind.
const (
	ListAssetsParamsKindCharacter ListAssetsParamsKind = "character"
	ListAssetsParamsKindLorebook  ListAssetsParamsKind = "lorebook"
	ListAssetsParamsKindPreset    ListAssetsParamsKind = "preset"
	ListAssetsParamsKindTheme     ListAssetsParamsKind = "theme"
)

// Valid indicates whether the value is a known member of the ListAssetsParamsKind enum.
func (e ListAssetsParamsKind) Valid() bool {
	switch e {
	case ListAssetsParamsKindCharacter:
		return true
	case ListAssetsParamsKindLorebook:
		return true
	case ListAssetsParamsKindPreset:
		return true
	case ListAssetsParamsKindTheme:
		return true
	default:
		return false
	}
}

// Defines values for ListAssetsParamsNsfw.
const (
	ListAssetsParamsNsfwBlurred ListAssetsParamsNsfw = "blurred"
	ListAssetsParamsNsfwHidden  ListAssetsParamsNsfw = "hidden"
	ListAssetsParamsNsfwShown   ListAssetsParamsNsfw = "shown"
)

// Valid indicates whether the value is a known member of the ListAssetsParamsNsfw enum.
func (e ListAssetsParamsNsfw) Valid() bool {
	switch e {
	case ListAssetsParamsNsfwBlurred:
		return true
	case ListAssetsParamsNsfwHidden:
		return true
	case ListAssetsParamsNsfwShown:
		return true
	default:
		return false
	}
}

// Defines values for GetAssetParamsNsfw.
const (
	GetAssetParamsNsfwBlurred GetAssetParamsNsfw = "blurred"
	GetAssetParamsNsfwHidden  GetAssetParamsNsfw = "hidden"
	GetAssetParamsNsfwShown   GetAssetParamsNsfw = "shown"
)

// Valid indicates whether the value is a known member of the GetAssetParamsNsfw enum.
func (e GetAssetParamsNsfw) Valid() bool {
	switch e {
	case GetAssetParamsNsfwBlurred:
		return true
	case GetAssetParamsNsfwHidden:
		return true
	case GetAssetParamsNsfwShown:
		return true
	default:
		return false
	}
}

// Defines values for BeginDiscordParamsIntent.
const (
	Attach BeginDiscordParamsIntent = "attach"
	SignIn BeginDiscordParamsIntent = "sign-in"
)

// Valid indicates whether the value is a known member of the BeginDiscordParamsIntent enum.
func (e BeginDiscordParamsIntent) Valid() bool {
	switch e {
	case Attach:
		return true
	case SignIn:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	DiscordLinked bool                 `json:"discordLinked"`
	Email         *openapi_types.Email `json:"email"`
	EmailVerified bool                 `json:"emailVerified"`
	Handle        string               `json:"handle"`
	HasPassword   bool                 `json:"hasPassword"`
	Id            openapi_types.UUID   `json:"id"`
	Role          AccountRole          `json:"role"`
}

// AccountRole defines model for Account.Role.
type AccountRole string

// AddAssetBlockRequest defines model for AddAssetBlockRequest.
type AddAssetBlockRequest struct {
	Definition string `json:"definition"`

	// ElementType What an element's data structure is, from the global vocabulary.
	ElementType ElementType `json:"elementType"`
}

// AddMediaRequest defines model for AddMediaRequest.
type AddMediaRequest struct {
	Role AddMediaRequestRole `json:"role"`
}

// AddMediaRequestRole defines model for AddMediaRequest.Role.
type AddMediaRequestRole string

// AddableSection One section the add tray offers. Where the content ends up is what the tray groups by, so a creator arrives at it by destination.
type AddableSection struct {
	// Choices The elements a creator may start the section with. One choice needs no question asking.
	Choices    []AddableSectionChoice `json:"choices"`
	Definition string                 `json:"definition"`
	Group      AddableSectionGroup    `json:"group"`
	GroupTitle string                 `json:"groupTitle"`
	Repeatable bool                   `json:"repeatable"`
	Summary    string                 `json:"summary"`
	Title      string                 `json:"title"`
}

// AddableSectionGroup defines model for AddableSection.Group.
type AddableSectionGroup string

// AddableSectionChoice defines model for AddableSectionChoice.
type AddableSectionChoice struct {
	Label string `json:"label"`

	// Type What an element's data structure is, from the global vocabulary.
	Type ElementType `json:"type"`
}

// ArrangeAssetBlocksRequest defines model for ArrangeAssetBlocksRequest.
type ArrangeAssetBlocksRequest struct {
	Blocks []struct {
		Hidden bool                                 `json:"hidden"`
		Id     openapi_types.UUID                   `json:"id"`
		Width  ArrangeAssetBlocksRequestBlocksWidth `json:"width"`
	} `json:"blocks"`
}

// ArrangeAssetBlocksRequestBlocksWidth defines model for ArrangeAssetBlocksRequest.Blocks.Width.
type ArrangeAssetBlocksRequestBlocksWidth string

// Asset defines model for Asset.
type Asset struct {
	Blurb     string             `json:"blurb"`
	CreatedAt time.Time          `json:"createdAt"`
	Discovery AssetDiscovery     `json:"discovery"`
	Format    string             `json:"format"`
	Id        openapi_types.UUID `json:"id"`
	IsNsfw    *bool              `json:"isNsfw"`
	Kind      string             `json:"kind"`
	Name      string             `json:"name"`
	Tags      []string           `json:"tags"`
}

// AssetDiscovery defines model for Asset.Discovery.
type AssetDiscovery string

// AssetBlock A titled container. Required, hideable, the layouts it allows and its default width are read from the kind catalog at render time, so this is what the catalog says today rather than what was true when the block was made.
type AssetBlock struct {
	// AllowedLayouts The layouts this block's current definition offers.
	AllowedLayouts []AssetBlockAllowedLayouts `json:"allowedLayouts"`
	Definition     string                     `json:"definition"`
	Elements       []AssetElement             `json:"elements"`
	Hidden         bool                       `json:"hidden"`
	Hideable       bool                       `json:"hideable"`
	Id             openapi_types.UUID         `json:"id"`

	// IsEmpty Whether every element in the block carries nothing. Computed for display and never stored.
	IsEmpty  bool             `json:"isEmpty"`
	Layout   AssetBlockLayout `json:"layout"`
	Position int              `json:"position"`
	Required bool             `json:"required"`

	// Title The creator's wording, or the definition's default where they wrote none.
	Title          string          `json:"title"`
	TitleIsDefault bool            `json:"titleIsDefault"`
	Width          AssetBlockWidth `json:"width"`
}

// AssetBlockAllowedLayouts defines model for AssetBlock.AllowedLayouts.
type AssetBlockAllowedLayouts string

// AssetBlockLayout defines model for AssetBlock.Layout.
type AssetBlockLayout string

// AssetBlockWidth defines model for AssetBlock.Width.
type AssetBlockWidth string

// AssetDetail defines model for AssetDetail.
type AssetDetail struct {
	// AddableSections The sections this kind can still be given, in catalog order. Present only while the owner is reading their own asset.
	AddableSections *[]AddableSection `json:"addableSections,omitempty"`

	// Blocks The asset's blocks in page order.
	Blocks []AssetBlock `json:"blocks"`

	// Blurb The catalog blurb the creator wrote for a person. Never the file's own description, which is a prompt written for a model.
	Blurb     string               `json:"blurb"`
	CreatedAt time.Time            `json:"createdAt"`
	Creator   string               `json:"creator"`
	Discovery AssetDetailDiscovery `json:"discovery"`

	// HasSourceFile Whether the asset carries a file a reader can download. An asset built from nothing carries none.
	HasSourceFile bool               `json:"hasSourceFile"`
	Id            openapi_types.UUID `json:"id"`

	// IsNsfw Null while a draft has not been asked the adult content question. Nothing answers it on the creator's behalf.
	IsNsfw *bool `json:"isNsfw"`

	// IsOwner Whether the reader owns the asset. The owner's page is the reader's page with its editing affordances, not a second visual state.
	IsOwner bool            `json:"isOwner"`
	Kind    AssetDetailKind `json:"kind"`

	// Lifecycle A draft resolves for its owner alone. Discovery applies to a published asset only.
	Lifecycle AssetDetailLifecycle `json:"lifecycle"`

	// Media The asset's images, cover first. Variant URLs already reflect the reader's preference, so a blurred reader is never handed a clear one.
	Media []AssetImage `json:"media"`
	Name  string       `json:"name"`

	// Preview The composed social preview for link unfurling. Null on a draft, which nothing unfurls.
	Preview *string `json:"preview"`

	// Readiness What publication is waiting on. Present only while the owner is reading their own draft.
	Readiness  *[]ReadinessItem      `json:"readiness,omitempty"`
	Tags       []AssetTag            `json:"tags"`
	Visibility AssetDetailVisibility `json:"visibility"`
	Withhold   *AssetWithhold        `json:"withhold,omitempty"`
}

// AssetDetailDiscovery defines model for AssetDetail.Discovery.
type AssetDetailDiscovery string

// AssetDetailKind defines model for AssetDetail.Kind.
type AssetDetailKind string

// AssetDetailLifecycle A draft resolves for its owner alone. Discovery applies to a published asset only.
type AssetDetailLifecycle string

// AssetDetailVisibility defines model for AssetDetail.Visibility.
type AssetDetailVisibility string

// AssetDiscoveryRequest defines model for AssetDiscoveryRequest.
type AssetDiscoveryRequest struct {
	Discovery AssetDiscoveryRequestDiscovery `json:"discovery"`
}

// AssetDiscoveryRequestDiscovery defines model for AssetDiscoveryRequest.Discovery.
type AssetDiscoveryRequestDiscovery string

// AssetElement One piece of content. Its role is what import and export read, and it travels with the element wherever the creator moves it.
type AssetElement struct {
	// Content The element type's own body. A reader switches on type to read it.
	Content json.RawMessage      `json:"content"`
	Display *AssetElementDisplay `json:"display,omitempty"`

	// Facts What the element says about its own data, such as how many entries a book holds and how many are switched on. Worked out on the way out and never stored, and never a token count.
	Facts   []string           `json:"facts"`
	Id      openapi_types.UUID `json:"id"`
	IsEmpty bool               `json:"isEmpty"`

	// ItemSize How large the images inside an element are drawn. It names what it controls, and no element type declares a measurement of its own.
	ItemSize *ItemSize `json:"itemSize,omitempty"`
	Label    string    `json:"label"`

	// Pinned A pinned element can be neither removed nor moved out of its block.
	Pinned bool `json:"pinned"`

	// Role Absent where the element has no import or export meaning.
	Role *string `json:"role,omitempty"`
	Slot string  `json:"slot"`

	// Type What an element's data structure is, from the global vocabulary.
	Type ElementType `json:"type"`
}

// AssetElementDisplay defines model for AssetElement.Display.
type AssetElementDisplay string

// AssetIdentityRequest defines model for AssetIdentityRequest.
type AssetIdentityRequest struct {
	// IsNsfw Null is the unanswered state, which only a draft may be in.
	IsNsfw *bool  `json:"isNsfw"`
	Name   string `json:"name"`
}

// AssetImage defines model for AssetImage.
type AssetImage struct {
	DetailUrl string             `json:"detailUrl"`
	Height    int                `json:"height"`
	Id        openapi_types.UUID `json:"id"`
	IsCover   bool               `json:"isCover"`
	Role      AssetImageRole     `json:"role"`
	ThumbUrl  string             `json:"thumbUrl"`
	Width     int                `json:"width"`
}

// AssetImageRole defines model for AssetImage.Role.
type AssetImageRole string

// AssetList defines model for AssetList.
type AssetList struct {
	EmptyState *AssetListEmptyState `json:"emptyState"`
	Facets     []BrowseFacet        `json:"facets"`
	Items      []BrowseAsset        `json:"items"`
	NextCursor *BrowseCursor        `json:"nextCursor,omitempty"`
	Platforms  []BrowseOption       `json:"platforms"`
	Suppressed int                  `json:"suppressed"`
	Total      int                  `json:"total"`
	Visibility AssetListVisibility  `json:"visibility"`
}

// AssetListEmptyState defines model for AssetList.EmptyState.
type AssetListEmptyState string

// AssetListVisibility defines model for AssetList.Visibility.
type AssetListVisibility string

// AssetTag defines model for AssetTag.
type AssetTag struct {
	// Label The creator's own text, shown as written.
	Label string `json:"label"`

	// Value The normalized form browse matches on.
	Value string `json:"value"`
}

// AssetWithhold defines model for AssetWithhold.
type AssetWithhold struct {
	Actor  string    `json:"actor"`
	At     time.Time `json:"at"`
	Reason string    `json:"reason"`
}

// BrowseAsset defines model for BrowseAsset.
type BrowseAsset struct {
	Cover   *BrowseCover       `json:"cover"`
	Creator string             `json:"creator"`
	Id      openapi_types.UUID `json:"id"`

	// IsNsfw Null on a draft whose creator has not answered the adult content question.
	IsNsfw *bool           `json:"isNsfw"`
	Kind   BrowseAssetKind `json:"kind"`
	Name   string          `json:"name"`

	// OwnerState Present only on the owner's own listing.
	OwnerState *BrowseAssetOwnerState `json:"ownerState,omitempty"`
	Withhold   *AssetWithhold         `json:"withhold,omitempty"`
}

// BrowseAssetKind defines model for BrowseAsset.Kind.
type BrowseAssetKind string

// BrowseAssetOwnerState Present only on the owner's own listing.
type BrowseAssetOwnerState string

// BrowseCover defines model for BrowseCover.
type BrowseCover struct {
	Height int    `json:"height"`
	Url    string `json:"url"`
	Width  int    `json:"width"`
}

// BrowseCursor defines model for BrowseCursor.
type BrowseCursor struct {
	Before   time.Time          `json:"before"`
	BeforeId openapi_types.UUID `json:"beforeId"`
}

// BrowseFacet defines model for BrowseFacet.
type BrowseFacet struct {
	Key     string         `json:"key"`
	Label   string         `json:"label"`
	Options []BrowseOption `json:"options"`
}

// BrowseOption defines model for BrowseOption.
type BrowseOption struct {
	Count    int    `json:"count"`
	Label    string `json:"label"`
	Selected bool   `json:"selected"`
	Value    string `json:"value"`
}

// ChangeEmailRequest defines model for ChangeEmailRequest.
type ChangeEmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// CompletePasswordResetRequest defines model for CompletePasswordResetRequest.
type CompletePasswordResetRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// CreateAssetRequest defines model for CreateAssetRequest.
type CreateAssetRequest struct {
	Blurb     *string                      `json:"blurb,omitempty"`
	Confirmed bool                         `json:"confirmed"`
	Discovery *CreateAssetRequestDiscovery `json:"discovery,omitempty"`
	IsNsfw    *bool                        `json:"isNsfw,omitempty"`
	Name      *string                      `json:"name,omitempty"`
	Tags      *[]string                    `json:"tags,omitempty"`
}

// CreateAssetRequestDiscovery defines model for CreateAssetRequest.Discovery.
type CreateAssetRequestDiscovery string

// DeletedAsset defines model for DeletedAsset.
type DeletedAsset struct {
	DeletedAt        time.Time          `json:"deletedAt"`
	Id               openapi_types.UUID `json:"id"`
	Kind             DeletedAssetKind   `json:"kind"`
	Name             string             `json:"name"`
	RecoverableUntil time.Time          `json:"recoverableUntil"`
}

// DeletedAssetKind defines model for DeletedAsset.Kind.
type DeletedAssetKind string

// DeletedAssetList defines model for DeletedAssetList.
type DeletedAssetList struct {
	Items []DeletedAsset `json:"items"`
}

// DialogueSampleContent defines model for DialogueSampleContent.
type DialogueSampleContent struct {
	Turns []struct {
		Speaker string `json:"speaker"`
		Text    string `json:"text"`
	} `json:"turns"`
}

// ElementType What an element's data structure is, from the global vocabulary.
type ElementType string

// EntryTableContent A lorebook. An entry is switched on by its keys, and how it behaves on the passes after the first is its own setting.
type EntryTableContent struct {
	Entries []struct {
		CaseSensitive *bool    `json:"caseSensitive,omitempty"`
		Constant      *bool    `json:"constant,omitempty"`
		Enabled       bool     `json:"enabled"`
		Keys          []string `json:"keys"`
		Name          *string  `json:"name,omitempty"`
		Order         *int     `json:"order,omitempty"`

		// Position Unset where the book leaves the choice to whatever reads it.
		Position  *EntryTableContentEntriesPosition `json:"position,omitempty"`
		Recursion *struct {
			DelayUntil *bool `json:"delayUntil,omitempty"`
			Exclude    *bool `json:"exclude,omitempty"`
			Prevent    *bool `json:"prevent,omitempty"`
		} `json:"recursion,omitempty"`
		SecondaryKeys *[]string `json:"secondaryKeys,omitempty"`
		Selective     *bool     `json:"selective,omitempty"`
		Text          string    `json:"text"`
	} `json:"entries"`
}

// EntryTableContentEntriesPosition Unset where the book leaves the choice to whatever reads it.
type EntryTableContentEntriesPosition string

// FieldListContent defines model for FieldListContent.
type FieldListContent struct {
	Fields []struct {
		Name  *string `json:"name,omitempty"`
		Value string  `json:"value"`
	} `json:"fields"`
}

// FileFieldPatch defines model for FileFieldPatch.
type FileFieldPatch struct {
	CharacterVersion        *string `json:"character_version,omitempty"`
	CreatorNotes            *string `json:"creator_notes,omitempty"`
	Description             *string `json:"description,omitempty"`
	FirstMes                *string `json:"first_mes,omitempty"`
	Personality             *string `json:"personality,omitempty"`
	PostHistoryInstructions *string `json:"post_history_instructions,omitempty"`
	Scenario                *string `json:"scenario,omitempty"`
	SystemPrompt            *string `json:"system_prompt,omitempty"`
}

// ImageSetContent An ordered list of images. An item carries its image and one optional free-text name, and its position is where it sits in the list.
type ImageSetContent struct {
	Images []struct {
		MediaId openapi_types.UUID `json:"mediaId"`
		Name    *string            `json:"name,omitempty"`
	} `json:"images"`
}

// IngestFailure defines model for IngestFailure.
type IngestFailure struct {
	Message string              `json:"message"`
	Reason  IngestFailureReason `json:"reason"`
}

// IngestFailureReason defines model for IngestFailure.Reason.
type IngestFailureReason string

// IngestOperation defines model for IngestOperation.
type IngestOperation struct {
	Asset   *Asset                `json:"asset,omitempty"`
	Failure *IngestFailure        `json:"failure,omitempty"`
	Id      openapi_types.UUID    `json:"id"`
	Status  IngestOperationStatus `json:"status"`
	Url     string                `json:"url"`
}

// IngestOperationStatus defines model for IngestOperation.Status.
type IngestOperationStatus string

// ItemSize How large the images inside an element are drawn. It names what it controls, and no element type declares a measurement of its own.
type ItemSize string

// LinkListContent defines model for LinkListContent.
type LinkListContent struct {
	Links []struct {
		Label *string `json:"label,omitempty"`
		Note  *string `json:"note,omitempty"`
		Url   string  `json:"url"`
	} `json:"links"`
}

// LinkPollResult defines model for LinkPollResult.
type LinkPollResult struct {
	Instance *LinkedInstance      `json:"instance,omitempty"`
	Status   LinkPollResultStatus `json:"status"`

	// Token The instance credential, sent once and never again. It does not expire and there is nothing to refresh.
	Token *string `json:"token,omitempty"`
}

// LinkPollResultStatus defines model for LinkPollResult.Status.
type LinkPollResultStatus string

// LinkRequest defines model for LinkRequest.
type LinkRequest struct {
	// DeviceCode Kept private by the client and sent when polling.
	DeviceCode string    `json:"deviceCode"`
	ExpiresAt  time.Time `json:"expiresAt"`

	// Interval Seconds to wait between polls.
	Interval int `json:"interval"`

	// UserCode Shown to the creator, who enters it on LumiHub.
	UserCode string `json:"userCode"`

	// VerificationUrl Where the creator enters the user code.
	VerificationUrl string `json:"verificationUrl"`

	// VerificationUrlComplete The same page with the code already filled in. A client running on the creator's own machine may open it.
	VerificationUrlComplete string `json:"verificationUrlComplete"`
}

// LinkedInstance defines model for LinkedInstance.
type LinkedInstance struct {
	Id         openapi_types.UUID `json:"id"`
	LastSeenAt *time.Time         `json:"lastSeenAt"`
	LinkedAt   time.Time          `json:"linkedAt"`
	Name       string             `json:"name"`

	// Prefix The start of the credential, so two links are told apart.
	Prefix    string     `json:"prefix"`
	RevokedAt *time.Time `json:"revokedAt"`
	Scopes    []Scope    `json:"scopes"`
}

// LinkedInstanceList defines model for LinkedInstanceList.
type LinkedInstanceList struct {
	Items []LinkedInstance `json:"items"`
}

// Media defines model for Media.
type Media struct {
	AssetId           openapi_types.UUID `json:"assetId"`
	DerivativeVersion int                `json:"derivativeVersion"`
	Height            int                `json:"height"`
	Id                openapi_types.UUID `json:"id"`
	Role              MediaRole          `json:"role"`
	Width             int                `json:"width"`
}

// MediaRole defines model for Media.Role.
type MediaRole string

// MediaList defines model for MediaList.
type MediaList struct {
	Items []Media `json:"items"`
}

// MoveAssetBlockContentRequest defines model for MoveAssetBlockContentRequest.
type MoveAssetBlockContentRequest struct {
	DestinationBlockId openapi_types.UUID `json:"destinationBlockId"`
}

// NsfwVisibilityRequest defines model for NsfwVisibilityRequest.
type NsfwVisibilityRequest struct {
	Visibility NsfwVisibilityRequestVisibility `json:"visibility"`
}

// NsfwVisibilityRequestVisibility defines model for NsfwVisibilityRequest.Visibility.
type NsfwVisibilityRequestVisibility string

// PasswordRequest defines model for PasswordRequest.
type PasswordRequest struct {
	Password string `json:"password"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// PendingLink defines model for PendingLink.
type PendingLink struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Name      string    `json:"name"`
	Scopes    []Scope   `json:"scopes"`
}

// PollLinkRequest defines model for PollLinkRequest.
type PollLinkRequest struct {
	DeviceCode string `json:"deviceCode"`
}

// Profile defines model for Profile.
type Profile struct {
	Handle string             `json:"handle"`
	Id     openapi_types.UUID `json:"id"`
}

// ProseContent defines model for ProseContent.
type ProseContent struct {
	Text string `json:"text"`
}

// PublishRefusal defines model for PublishRefusal.
type PublishRefusal struct {
	Error string `json:"error"`

	// Readiness The whole floor, so a refusal names every missing item at once.
	Readiness *[]ReadinessItem `json:"readiness,omitempty"`
}

// ReadinessItem One thing publication waits on, and whether the asset carries it.
type ReadinessItem struct {
	// BlockId The block a creator fills this in. Absent for a header field.
	BlockId *openapi_types.UUID `json:"blockId,omitempty"`
	Detail  string              `json:"detail"`
	Id      string              `json:"id"`
	Label   string              `json:"label"`
	Met     bool                `json:"met"`
}

// RenameHandleRequest defines model for RenameHandleRequest.
type RenameHandleRequest struct {
	Handle string `json:"handle"`
}

// SaveAssetBlockRequest defines model for SaveAssetBlockRequest.
type SaveAssetBlockRequest struct {
	Elements []SaveAssetElement          `json:"elements"`
	Layout   SaveAssetBlockRequestLayout `json:"layout"`

	// Title Null keeps the definition's current default wording.
	Title *string                    `json:"title"`
	Width SaveAssetBlockRequestWidth `json:"width"`
}

// SaveAssetBlockRequestLayout defines model for SaveAssetBlockRequest.Layout.
type SaveAssetBlockRequestLayout string

// SaveAssetBlockRequestWidth defines model for SaveAssetBlockRequest.Width.
type SaveAssetBlockRequestWidth string

// SaveAssetElement defines model for SaveAssetElement.
type SaveAssetElement struct {
	// Content The element type's own body.
	Content json.RawMessage          `json:"content"`
	Display *SaveAssetElementDisplay `json:"display,omitempty"`
	Id      openapi_types.UUID       `json:"id"`

	// ItemSize How large the images inside an element are drawn. It names what it controls, and no element type declares a measurement of its own.
	ItemSize *ItemSize `json:"itemSize,omitempty"`

	// Role Absent where the element has no import or export meaning.
	Role *string `json:"role,omitempty"`
	Slot string  `json:"slot"`

	// Type What an element's data structure is, from the global vocabulary.
	Type ElementType `json:"type"`
}

// SaveAssetElementDisplay defines model for SaveAssetElement.Display.
type SaveAssetElementDisplay string

// Scope asset:receive lets an instance receive assets sent to it. library:sync lets it report what it has installed.
type Scope string

// SessionState defines model for SessionState.
type SessionState struct {
	User *Account `json:"user"`
}

// SignInRequest defines model for SignInRequest.
type SignInRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	Email    openapi_types.Email `json:"email"`
	Handle   string              `json:"handle"`
	Password string              `json:"password"`
}

// StartAssetRequest The kind an asset is built as. Only kinds Illarin can build are accepted, so a creator is never handed an empty page.
type StartAssetRequest struct {
	Kind string `json:"kind"`
}

// StartLinkRequest defines model for StartLinkRequest.
type StartLinkRequest struct {
	// Name What the creator sees on the approval screen. Name the installation, not the product, so somebody with two of them can tell which is which.
	Name   string  `json:"name"`
	Scopes []Scope `json:"scopes"`
}

// TextSetContent defines model for TextSetContent.
type TextSetContent struct {
	Texts []struct {
		Name *string `json:"name,omitempty"`
		Text string  `json:"text"`
	} `json:"texts"`
}

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Token string `json:"token"`
}

// WithholdAssetRequest defines model for WithholdAssetRequest.
type WithholdAssetRequest struct {
	Reason string `json:"reason"`
}

// GetMediaVariantParams defines parameters for GetMediaVariant.
type GetMediaVariantParams struct {
	// Expires When the signature runs out. A draft's images are served against a short-lived signature at the same address they keep once published.
	Expires   *string `form:"expires,omitempty" json:"expires,omitempty"`
	Signature *string `form:"signature,omitempty" json:"signature,omitempty"`
}

// GetMediaVariantParamsVariant defines parameters for GetMediaVariant.
type GetMediaVariantParamsVariant string

// ListAssetsParams defines parameters for ListAssets.
type ListAssetsParams struct {
	Kind     *ListAssetsParamsKind `form:"kind,omitempty" json:"kind,omitempty"`
	Platform *string               `form:"platform,omitempty" json:"platform,omitempty"`

	// Creator Scope the listing to one creator's public profile.
	Creator *string `form:"creator,omitempty" json:"creator,omitempty"`

	// Q One search expression. Bare text matches names, creator handles and blurbs. Repeat tag: to require every tag; one author: qualifier may narrow the creator. Quote qualifier values that contain spaces.
	Q     *string   `form:"q,omitempty" json:"q,omitempty"`
	Facet *[]string `form:"facet,omitempty" json:"facet,omitempty"`

	// Nsfw The reader's presentation preference. Browse page URLs keep this preference out of their own query string.
	Nsfw  *ListAssetsParamsNsfw `form:"nsfw,omitempty" json:"nsfw,omitempty"`
	Limit *int                  `form:"limit,omitempty" json:"limit,omitempty"`

	// Before The made date of the last asset on the previous page. Send it with beforeId or not at all.
	Before *time.Time `form:"before,omitempty" json:"before,omitempty"`

	// BeforeId The id of that same asset
	BeforeId *openapi_types.UUID `form:"beforeId,omitempty" json:"beforeId,omitempty"`
}

// ListAssetsParamsKind defines parameters for ListAssets.
type ListAssetsParamsKind string

// ListAssetsParamsNsfw defines parameters for ListAssets.
type ListAssetsParamsNsfw string

// CreateAssetMultipartBody defines parameters for CreateAsset.
type CreateAssetMultipartBody struct {
	File     openapi_types.File `json:"file"`
	Metadata CreateAssetRequest `json:"metadata"`
}

// GetAssetParams defines parameters for GetAsset.
type GetAssetParams struct {
	// Nsfw The reader's presentation preference. Asset page URLs keep this preference out of their own query string.
	Nsfw *GetAssetParamsNsfw `form:"nsfw,omitempty" json:"nsfw,omitempty"`
}

// GetAssetParamsNsfw defines parameters for GetAsset.
type GetAssetParamsNsfw string

// AddMediaMultipartBody defines parameters for AddMedia.
type AddMediaMultipartBody struct {
	File     openapi_types.File `json:"file"`
	Metadata AddMediaRequest    `json:"metadata"`
}

// AddAssetRevisionMultipartBody defines parameters for AddAssetRevision.
type AddAssetRevisionMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// BeginDiscordParams defines parameters for BeginDiscord.
type BeginDiscordParams struct {
	Intent *BeginDiscordParamsIntent `form:"intent,omitempty" json:"intent,omitempty"`
}

// BeginDiscordParamsIntent defines parameters for BeginDiscord.
type BeginDiscordParamsIntent string

// CompleteDiscordParams defines parameters for CompleteDiscord.
type CompleteDiscordParams struct {
	State string  `form:"state" json:"state"`
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// ChangeUnverifiedEmailJSONRequestBody defines body for ChangeUnverifiedEmail for application/json ContentType.
type ChangeUnverifiedEmailJSONRequestBody = ChangeEmailRequest

// RenameHandleJSONRequestBody defines body for RenameHandle for application/json ContentType.
type RenameHandleJSONRequestBody = RenameHandleRequest

// SetNsfwVisibilityJSONRequestBody defines body for SetNsfwVisibility for application/json ContentType.
type SetNsfwVisibilityJSONRequestBody = NsfwVisibilityRequest

// SetPasswordJSONRequestBody defines body for SetPassword for application/json ContentType.
type SetPasswordJSONRequestBody = PasswordRequest

// CreateAssetJSONRequestBody defines body for CreateAsset for application/json ContentType.
type CreateAssetJSONRequestBody = StartAssetRequest

// CreateAssetMultipartRequestBody defines body for CreateAsset for multipart/form-data ContentType.
type CreateAssetMultipartRequestBody CreateAssetMultipartBody

// AddAssetBlockJSONRequestBody defines body for AddAssetBlock for application/json ContentType.
type AddAssetBlockJSONRequestBody = AddAssetBlockRequest

// ArrangeAssetBlocksJSONRequestBody defines body for ArrangeAssetBlocks for application/json ContentType.
type ArrangeAssetBlocksJSONRequestBody = ArrangeAssetBlocksRequest

// SaveAssetBlockJSONRequestBody defines body for SaveAssetBlock for application/json ContentType.
type SaveAssetBlockJSONRequestBody = SaveAssetBlockRequest

// MoveAssetBlockContentJSONRequestBody defines body for MoveAssetBlockContent for application/json ContentType.
type MoveAssetBlockContentJSONRequestBody = MoveAssetBlockContentRequest

// SetAssetDiscoveryJSONRequestBody defines body for SetAssetDiscovery for application/json ContentType.
type SetAssetDiscoveryJSONRequestBody = AssetDiscoveryRequest

// SetFilePatchJSONRequestBody defines body for SetFilePatch for application/json ContentType.
type SetFilePatchJSONRequestBody = FileFieldPatch

// SetAssetIdentityJSONRequestBody defines body for SetAssetIdentity for application/json ContentType.
type SetAssetIdentityJSONRequestBody = AssetIdentityRequest

// AddMediaMultipartRequestBody defines body for AddMedia for multipart/form-data ContentType.
type AddMediaMultipartRequestBody AddMediaMultipartBody

// AddAssetRevisionMultipartRequestBody defines body for AddAssetRevision for multipart/form-data ContentType.
type AddAssetRevisionMultipartRequestBody AddAssetRevisionMultipartBody

// WithholdAssetJSONRequestBody defines body for WithholdAsset for application/json ContentType.
type WithholdAssetJSONRequestBody = WithholdAssetRequest

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// CompletePasswordResetJSONRequestBody defines body for CompletePasswordReset for application/json ContentType.
type CompletePasswordResetJSONRequestBody = CompletePasswordResetRequest

// SignInJSONRequestBody defines body for SignIn for application/json ContentType.
type SignInJSONRequestBody = SignInRequest

// SignUpJSONRequestBody defines body for SignUp for application/json ContentType.
type SignUpJSONRequestBody = SignUpRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest

// PollLinkRequestJSONRequestBody defines body for PollLinkRequest for application/json ContentType.
type PollLinkRequestJSONRequestBody = PollLinkRequest

// StartLinkRequestJSONRequestBody defines body for StartLinkRequest for application/json ContentType.
type StartLinkRequestJSONRequestBody = StartLinkRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /download/{id})
	DownloadSource(c *gin.Context, id openapi_types.UUID)

	// (GET /download/{id}/{target})
	DownloadExport(c *gin.Context, id openapi_types.UUID, target string)

	// (GET /media/{media_id}/{variant}/{derivative_version})
	GetMediaVariant(c *gin.Context, mediaId openapi_types.UUID, variant GetMediaVariantParamsVariant, derivativeVersion int, params GetMediaVariantParams)

	// (DELETE /v1/account/discord)
	DetachDiscord(c *gin.Context)

	// (PATCH /v1/account/email)
	ChangeUnverifiedEmail(c *gin.Context)

	// (PATCH /v1/account/handle)
	RenameHandle(c *gin.Context)

	// (PUT /v1/account/nsfw-visibility)
	SetNsfwVisibility(c *gin.Context)

	// (PUT /v1/account/password)
	SetPassword(c *gin.Context)

	// (GET /v1/assets)
	ListAssets(c *gin.Context, params ListAssetsParams)

	// (POST /v1/assets)
	CreateAsset(c *gin.Context)

	// (DELETE /v1/assets/{id})
	DeleteAsset(c *gin.Context, id openapi_types.UUID)

	// (GET /v1/assets/{id})
	GetAsset(c *gin.Context, id openapi_types.UUID, params GetAssetParams)

	// (POST /v1/assets/{id}/blocks)
	AddAssetBlock(c *gin.Context, id openapi_types.UUID)

	// (PUT /v1/assets/{id}/blocks)
	ArrangeAssetBlocks(c *gin.Context, id openapi_types.UUID)

	// (DELETE /v1/assets/{id}/blocks/{blockId})
	RemoveAssetBlock(c *gin.Context, id openapi_types.UUID, blockId openapi_types.UUID)

	// (PUT /v1/assets/{id}/blocks/{blockId})
	SaveAssetBlock(c *gin.Context, id openapi_types.UUID, blockId openapi_types.UUID)

	// (POST /v1/assets/{id}/blocks/{blockId}/move-and-remove)
	MoveAssetBlockContent(c *gin.Context, id openapi_types.UUID, blockId openapi_types.UUID)

	// (PUT /v1/assets/{id}/discovery)
	SetAssetDiscovery(c *gin.Context, id openapi_types.UUID)

	// (PUT /v1/assets/{id}/file-patch)
	SetFilePatch(c *gin.Context, id openapi_types.UUID)

	// (PUT /v1/assets/{id}/identity)
	SetAssetIdentity(c *gin.Context, id openapi_types.UUID)

	// (GET /v1/assets/{id}/media)
	ListMedia(c *gin.Context, id openapi_types.UUID)

	// (POST /v1/assets/{id}/media)
	AddMedia(c *gin.Context, id openapi_types.UUID)

	// (POST /v1/assets/{id}/publish)
	PublishAsset(c *gin.Context, id openapi_types.UUID)

	// (POST /v1/assets/{id}/restore)
	RestoreAsset(c *gin.Context, id openapi_types.UUID)

	// (POST /v1/assets/{id}/revisions)
	AddAssetRevision(c *gin.Context, id openapi_types.UUID)

	// (DELETE /v1/assets/{id}/withhold)
	ClearAssetWithhold(c *gin.Context, id openapi_types.UUID)

	// (PUT /v1/assets/{id}/withhold)
	WithholdAsset(c *gin.Context, id openapi_types.UUID)

	// (GET /v1/auth/discord)
	BeginDiscord(c *gin.Context, params BeginDiscordParams)

	// (GET /v1/auth/discord/callback)
	CompleteDiscord(c *gin.Context, params CompleteDiscordParams)

	// (POST /v1/auth/password-reset)
	RequestPasswordReset(c *gin.Context)

	// (POST /v1/auth/password-reset/complete)
	CompletePasswordReset(c *gin.Context)

	// (GET /v1/auth/session)
	GetSession(c *gin.Context)

	// (POST /v1/auth/sign-in)
	SignIn(c *gin.Context)

	// (POST /v1/auth/sign-out)
	SignOut(c *gin.Context)

	// (POST /v1/auth/sign-up)
	SignUp(c *gin.Context)

	// (POST /v1/auth/verify-email)
	VerifyEmail(c *gin.Context)

	// (GET /v1/ingests/{id})
	GetIngest(c *gin.Context, id openapi_types.UUID)

	// (GET /v1/instances)
	ListInstances(c *gin.Context)

	// (GET /v1/instances/me)
	GetInstance(c *gin.Context)

	// (DELETE /v1/instances/{id})
	RevokeInstance(c *gin.Context, id openapi_types.UUID)

	// (POST /v1/link/poll)
	PollLinkRequest(c *gin.Context)

	// (POST /v1/link/requests)
	StartLinkRequest(c *gin.Context)

	// (GET /v1/link/requests/{userCode})
	GetLinkRequest(c *gin.Context, userCode string)

	// (POST /v1/link/requests/{userCode}/approve)
	ApproveLinkRequest(c *gin.Context, userCode string)

	// (GET /v1/profiles/{handle})
	GetProfile(c *gin.Context, handle string)

	// (GET /v1/profiles/{handle}/deleted)
	ListDeletedAssets(c *gin.Context, handle string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// DownloadSource operation middleware
func (siw *ServerInterfaceWrapper) DownloadSource(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DownloadSource(c, id)
}

// DownloadExport operation middleware
func (siw *ServerInterfaceWrapper) DownloadExport(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "target" -------------
	var target string

	err = runtime.BindStyledParameterWithOptions("simple", "target", c.Param("target"), &target, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter target: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DownloadExport(c, id, target)
}

// GetMediaVariant operation middleware
func (siw *ServerInterfaceWrapper) GetMediaVariant(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "media_id" -------------
	var mediaId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "media_id", c.Param("media_id"), &mediaId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter media_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "variant" -------------
	var variant GetMediaVariantParamsVariant

	err = runtime.BindStyledParameterWithOptions("simple", "variant", c.Param("variant"), &variant, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter variant: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "derivative_version" -------------
	var derivativeVersion int

	err = runtime.BindStyledParameterWithOptions("simple", "derivative_version", c.Param("derivative_version"), &derivativeVersion, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter derivative_version: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMediaVariantParams

	// ------------- Optional query parameter "expires" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "expires", c.Request.URL.Query(), &params.Expires, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter expires: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "signature" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "signature", c.Request.URL.Query(), &params.Signature, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter signature: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMediaVariant(c, mediaId, variant, derivativeVersion, params)
}

// DetachDiscord operation middleware
func (siw *ServerInterfaceWrapper) DetachDiscord(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DetachDiscord(c)
}

// ChangeUnverifiedEmail operation middleware
func (siw *ServerInterfaceWrapper) ChangeUnverifiedEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ChangeUnverifiedEmail(c)
}

// RenameHandle operation middleware
func (siw *ServerInterfaceWrapper) RenameHandle(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RenameHandle(c)
}

// SetNsfwVisibility operation middleware
func (siw *ServerInterfaceWrapper) SetNsfwVisibility(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetNsfwVisibility(c)
}

// SetPassword operation middleware
func (siw *ServerInterfaceWrapper) SetPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetPassword(c)
}

// ListAssets operation middleware
func (siw *ServerInterfaceWrapper) ListAssets(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAssetsParams

	// ------------- Optional query parameter "kind" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "kind", c.Request.URL.Query(), &params.Kind, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter kind: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "platform" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "platform", c.Request.URL.Query(), &params.Platform, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter platform: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "creator" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "creator", c.Request.URL.Query(), &params.Creator, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter creator: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", c.Request.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "facet" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "facet", c.Request.URL.Query(), &params.Facet, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter facet: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "nsfw" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "nsfw", c.Request.URL.Query(), &params.Nsfw, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter nsfw: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", c.Request.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter before: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "beforeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "beforeId", c.Request.URL.Query(), &params.BeforeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter beforeId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAssets(c, params)
}

// CreateAsset operation middleware
func (siw *ServerInterfaceWrapper) CreateAsset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAsset(c)
}

// DeleteAsset operation middleware
func (siw *ServerInterfaceWrapper) DeleteAsset(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAsset(c, id)
}

// GetAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAsset(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssetParams

	// ------------- Optional query parameter "nsfw" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "nsfw", c.Request.URL.Query(), &params.Nsfw, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter nsfw: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAsset(c, id, params)
}

// AddAssetBlock operation middleware
func (siw *ServerInterfaceWrapper) AddAssetBlock(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddAssetBlock(c, id)
}

// ArrangeAssetBlocks operation middleware
func (siw *ServerInterfaceWrapper) ArrangeAssetBlocks(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ArrangeAssetBlocks(c, id)
}

// RemoveAssetBlock operation middleware
func (siw *ServerInterfaceWrapper) RemoveAssetBlock(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "blockId" -------------
	var blockId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "blockId", c.Param("blockId"), &blockId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter blockId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveAssetBlock(c, id, blockId)
}

// SaveAssetBlock operation middleware
func (siw *ServerInterfaceWrapper) SaveAssetBlock(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "blockId" -------------
	var blockId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "blockId", c.Param("blockId"), &blockId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter blockId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveAssetBlock(c, id, blockId)
}

// MoveAssetBlockContent operation middleware
func (siw *ServerInterfaceWrapper) MoveAssetBlockContent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "blockId" -------------
	var blockId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "blockId", c.Param("blockId"), &blockId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter blockId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.MoveAssetBlockContent(c, id, blockId)
}

// SetAssetDiscovery operation middleware
func (siw *ServerInterfaceWrapper) SetAssetDiscovery(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAssetDiscovery(c, id)
}

// SetFilePatch operation middleware
func (siw *ServerInterfaceWrapper) SetFilePatch(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetFilePatch(c, id)
}

// SetAssetIdentity operation middleware
func (siw *ServerInterfaceWrapper) SetAssetIdentity(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetAssetIdentity(c, id)
}

// ListMedia operation middleware
func (siw *ServerInterfaceWrapper) ListMedia(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMedia(c, id)
}

// AddMedia operation middleware
func (siw *ServerInterfaceWrapper) AddMedia(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddMedia(c, id)
}

// PublishAsset operation middleware
func (siw *ServerInterfaceWrapper) PublishAsset(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublishAsset(c, id)
}

// RestoreAsset operation middleware
func (siw *ServerInterfaceWrapper) RestoreAsset(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RestoreAsset(c, id)
}

// AddAssetRevision operation middleware
func (siw *ServerInterfaceWrapper) AddAssetRevision(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddAssetRevision(c, id)
}

// ClearAssetWithhold operation middleware
func (siw *ServerInterfaceWrapper) ClearAssetWithhold(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ClearAssetWithhold(c, id)
}

// WithholdAsset operation middleware
func (siw *ServerInterfaceWrapper) WithholdAsset(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.WithholdAsset(c, id)
}

// BeginDiscord operation middleware
func (siw *ServerInterfaceWrapper) BeginDiscord(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params BeginDiscordParams

	// ------------- Optional query parameter "intent" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "intent", c.Request.URL.Query(), &params.Intent, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter intent: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.BeginDiscord(c, params)
}

// CompleteDiscord operation middleware
func (siw *ServerInterfaceWrapper) CompleteDiscord(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CompleteDiscordParams

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", c.Request.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "code", c.Request.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "error" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "error", c.Request.URL.Query(), &params.Error, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter error: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteDiscord(c, params)
}

// RequestPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) RequestPasswordReset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RequestPasswordReset(c)
}

// CompletePasswordReset operation middleware
func (siw *ServerInterfaceWrapper) CompletePasswordReset(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompletePasswordReset(c)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSession(c)
}

// SignIn operation middleware
func (siw *ServerInterfaceWrapper) SignIn(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignIn(c)
}

// SignOut operation middleware
func (siw *ServerInterfaceWrapper) SignOut(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignOut(c)
}

// SignUp operation middleware
func (siw *ServerInterfaceWrapper) SignUp(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SignUp(c)
}

// VerifyEmail operation middleware
func (siw *ServerInterfaceWrapper) VerifyEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.VerifyEmail(c)
}

// GetIngest operation middleware
func (siw *ServerInterfaceWrapper) GetIngest(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetIngest(c, id)
}

// ListInstances operation middleware
func (siw *ServerInterfaceWrapper) ListInstances(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListInstances(c)
}

// GetInstance operation middleware
func (siw *ServerInterfaceWrapper) GetInstance(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetInstance(c)
}

// RevokeInstance operation middleware
func (siw *ServerInterfaceWrapper) RevokeInstance(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeInstance(c, id)
}

// PollLinkRequest operation middleware
func (siw *ServerInterfaceWrapper) PollLinkRequest(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PollLinkRequest(c)
}

// StartLinkRequest operation middleware
func (siw *ServerInterfaceWrapper) StartLinkRequest(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartLinkRequest(c)
}

// GetLinkRequest operation middleware
func (siw *ServerInterfaceWrapper) GetLinkRequest(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userCode" -------------
	var userCode string

	err = runtime.BindStyledParameterWithOptions("simple", "userCode", c.Param("userCode"), &userCode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userCode: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLinkRequest(c, userCode)
}

// ApproveLinkRequest operation middleware
func (siw *ServerInterfaceWrapper) ApproveLinkRequest(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userCode" -------------
	var userCode string

	err = runtime.BindStyledParameterWithOptions("simple", "userCode", c.Param("userCode"), &userCode, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userCode: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ApproveLinkRequest(c, userCode)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "handle" -------------
	var handle string

	err = runtime.BindStyledParameterWithOptions("simple", "handle", c.Param("handle"), &handle, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter handle: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfile(c, handle)
}

// ListDeletedAssets operation middleware
func (siw *ServerInterfaceWrapper) ListDeletedAssets(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "handle" -------------
	var handle string

	err = runtime.BindStyledParameterWithOptions("simple", "handle", c.Param("handle"), &handle, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter handle: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDeletedAssets(c, handle)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/v1/account/discord", wrapper.DetachDiscord)
	router.PATCH(options.BaseURL+"/v1/account/email", wrapper.ChangeUnverifiedEmail)
	router.PATCH(options.BaseURL+"/v1/account/handle", wrapper.RenameHandle)
	router.PUT(options.BaseURL+"/v1/account/password", wrapper.SetPassword)
	router.PUT(options.BaseURL+"/v1/account/nsfw-visibility", wrapper.SetNsfwVisibility)
	router.POST(options.BaseURL+"/v1/auth/sign-up", wrapper.SignUp)
	router.POST(options.BaseURL+"/v1/auth/sign-in", wrapper.SignIn)
	router.GET(options.BaseURL+"/v1/auth/discord", wrapper.BeginDiscord)
	router.GET(options.BaseURL+"/v1/auth/discord/callback", wrapper.CompleteDiscord)
	router.POST(options.BaseURL+"/v1/auth/sign-out", wrapper.SignOut)
	router.GET(options.BaseURL+"/v1/auth/session", wrapper.GetSession)
	router.POST(options.BaseURL+"/v1/auth/verify-email", wrapper.VerifyEmail)
	router.POST(options.BaseURL+"/v1/auth/password-reset", wrapper.RequestPasswordReset)
	router.POST(options.BaseURL+"/v1/auth/password-reset/complete", wrapper.CompletePasswordReset)
	router.POST(options.BaseURL+"/v1/link/requests", wrapper.StartLinkRequest)
	router.POST(options.BaseURL+"/v1/link/poll", wrapper.PollLinkRequest)
	router.GET(options.BaseURL+"/v1/link/requests/:userCode", wrapper.GetLinkRequest)
	router.POST(options.BaseURL+"/v1/link/requests/:userCode/approve", wrapper.ApproveLinkRequest)
	router.GET(options.BaseURL+"/v1/instances", wrapper.ListInstances)
	router.GET(options.BaseURL+"/v1/instances/me", wrapper.GetInstance)
	router.DELETE(options.BaseURL+"/v1/instances/:id", wrapper.RevokeInstance)
	router.GET(options.BaseURL+"/v1/profiles/:handle", wrapper.GetProfile)
	router.GET(options.BaseURL+"/v1/assets", wrapper.ListAssets)
	router.POST(options.BaseURL+"/v1/assets", wrapper.CreateAsset)
	router.DELETE(options.BaseURL+"/v1/assets/:id", wrapper.DeleteAsset)
	router.GET(options.BaseURL+"/v1/assets/:id", wrapper.GetAsset)
	router.POST(options.BaseURL+"/v1/assets/:id/revisions", wrapper.AddAssetRevision)
	router.DELETE(options.BaseURL+"/v1/assets/:id/blocks/:blockId", wrapper.RemoveAssetBlock)
	router.PUT(options.BaseURL+"/v1/assets/:id/blocks/:blockId", wrapper.SaveAssetBlock)
	router.POST(options.BaseURL+"/v1/assets/:id/blocks", wrapper.AddAssetBlock)
	router.PUT(options.BaseURL+"/v1/assets/:id/blocks", wrapper.ArrangeAssetBlocks)
	router.POST(options.BaseURL+"/v1/assets/:id/blocks/:blockId/move-and-remove", wrapper.MoveAssetBlockContent)
	router.PUT(options.BaseURL+"/v1/assets/:id/file-patch", wrapper.SetFilePatch)
	router.POST(options.BaseURL+"/v1/assets/:id/restore", wrapper.RestoreAsset)
	router.PUT(options.BaseURL+"/v1/assets/:id/identity", wrapper.SetAssetIdentity)
	router.POST(options.BaseURL+"/v1/assets/:id/publish", wrapper.PublishAsset)
	router.PUT(options.BaseURL+"/v1/assets/:id/discovery", wrapper.SetAssetDiscovery)
	router.GET(options.BaseURL+"/v1/profiles/:handle/deleted", wrapper.ListDeletedAssets)
	router.DELETE(options.BaseURL+"/v1/assets/:id/withhold", wrapper.ClearAssetWithhold)
	router.PUT(options.BaseURL+"/v1/assets/:id/withhold", wrapper.WithholdAsset)
	router.GET(options.BaseURL+"/download/:id", wrapper.DownloadSource)
	router.GET(options.BaseURL+"/download/:id/:target", wrapper.DownloadExport)
	router.GET(options.BaseURL+"/v1/assets/:id/media", wrapper.ListMedia)
	router.POST(options.BaseURL+"/v1/assets/:id/media", wrapper.AddMedia)
	router.GET(options.BaseURL+"/media/:media_id/:variant/:derivative_version", wrapper.GetMediaVariant)
	router.GET(options.BaseURL+"/v1/ingests/:id", wrapper.GetIngest)
}
