// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID                pgtype.UUID
	Kind              string
	CurrentRevisionID pgtype.UUID
	OwnerID           pgtype.UUID
	Name              string
	Blurb             string
	Tags              []string
	CoverMediaID      pgtype.UUID
	IsNsfw            pgtype.Bool
	Discovery         string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IndexedAt         pgtype.Timestamptz
	WithheldAt        pgtype.Timestamptz
	WithheldBy        pgtype.UUID
	WithheldReason    pgtype.Text
	DeletedAt         pgtype.Timestamptz
	RecoverableUntil  pgtype.Timestamptz
	Lifecycle         string
}

type AssetBlock struct {
	ID         pgtype.UUID
	AssetID    pgtype.UUID
	Definition string
	Title      pgtype.Text
	Position   int32
	Hidden     bool
	Layout     string
	Width      string
	Elements   []byte
}

type AssetFacet struct {
	RevisionID pgtype.UUID
	Key        string
	Value      string
}

type AssetMedium struct {
	ID          pgtype.UUID
	AssetID     pgtype.UUID
	Role        string
	Width       pgtype.Int4
	Height      pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	BlobID      pgtype.UUID
	IsExtracted bool
	IsCurrent   bool
}

type AssetRevision struct {
	ID                  pgtype.UUID
	AssetID             pgtype.UUID
	Revision            int32
	MediaType           string
	CreatedAt           pgtype.Timestamptz
	BlobID              pgtype.UUID
	Format              string
	PassthroughPlatform pgtype.Text
}

type Blob struct {
	ID         pgtype.UUID
	Sha256     []byte
	ByteSize   int64
	StorageKey string
}

type BlobSweepMark struct {
	BlobID   pgtype.UUID
	MarkedAt pgtype.Timestamptz
}

type BlobTombstone struct {
	Sha256     []byte
	ReasonCode string
	PurgedAt   pgtype.Timestamptz
	ActorID    pgtype.UUID
}

type DownloadEvent struct {
	ID                 int64
	AssetID            pgtype.UUID
	RevisionID         pgtype.UUID
	ExportTarget       string
	HandedOffAt        pgtype.Timestamptz
	AuthorizationClass string
	Discovery          string
}

type EmailVerificationToken struct {
	TokenHash []byte
	UserID    pgtype.UUID
	Email     string
	ExpiresAt pgtype.Timestamptz
}

type FileFieldPatch struct {
	AssetID    pgtype.UUID
	RevisionID pgtype.UUID
	Field      string
	Value      string
	Provenance string
}

type IngestOperation struct {
	ID             pgtype.UUID
	OwnerID        pgtype.UUID
	BlobID         pgtype.UUID
	Filename       string
	Status         string
	Kind           pgtype.Text
	Name           pgtype.Text
	Blurb          pgtype.Text
	Tags           []string
	IsNsfw         pgtype.Bool
	Discovery      string
	AssetID        pgtype.UUID
	FailureReason  pgtype.Text
	Attempts       int32
	AvailableAt    pgtype.Timestamptz
	LeaseToken     pgtype.UUID
	LeaseExpiresAt pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	TargetAssetID  pgtype.UUID
}

type LinkCodeAttempt struct {
	UserID      pgtype.UUID
	Failures    int32
	WindowStart pgtype.Timestamptz
}

type LinkRequest struct {
	DeviceCodeHash []byte
	UserCode       string
	ClientName     string
	Scopes         []string
	ApprovedBy     pgtype.UUID
	ApprovedAt     pgtype.Timestamptz
	RedeemedAt     pgtype.Timestamptz
	LastPolledAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type LinkedInstance struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	TokenHash   []byte
	TokenPrefix string
	Scopes      []string
	LinkedAt    pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type OauthIdentity struct {
	UserID        pgtype.UUID
	Provider      string
	Subject       string
	ProviderEmail pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type OauthState struct {
	TokenHash []byte
	Intent    string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type PasswordResetToken struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type RetiredHandle struct {
	Handle string
}

type Session struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID                             pgtype.UUID
	Username                       string
	Email                          pgtype.Text
	PasswordHash                   pgtype.Text
	EmailVerifiedAt                pgtype.Timestamptz
	EmailSource                    pgtype.Text
	CreatedAt                      pgtype.Timestamptz
	UpdatedAt                      pgtype.Timestamptz
	NsfwVisibility                 string
	ShowNsfwContributionsOnProfile bool
	Role                           string
}
