// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID                pgtype.UUID
	Kind              string
	Platform          pgtype.Text
	Format            string
	FormatVersion     string
	CurrentRevisionID pgtype.UUID
	OwnerID           pgtype.UUID
	Name              string
	Description       string
	Tags              []string
	PreviewMediaID    pgtype.UUID
	IsNsfw            bool
	Publication       string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IndexedAt         pgtype.Timestamptz
}

type AssetFacet struct {
	AssetID    pgtype.UUID
	RevisionID pgtype.UUID
	Key        string
	Value      string
}

type AssetMedium struct {
	ID         pgtype.UUID
	AssetID    pgtype.UUID
	RevisionID pgtype.UUID
	Role       string
	StorageKey string
	Width      pgtype.Int4
	Height     pgtype.Int4
	CreatedAt  pgtype.Timestamptz
}

type AssetRevision struct {
	ID          pgtype.UUID
	AssetID     pgtype.UUID
	Revision    int32
	ContentHash string
	ByteSize    int64
	StorageKey  string
	MediaType   string
	CreatedAt   pgtype.Timestamptz
}
