// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assetByID = `-- name: AssetByID :one
select a.id, a.kind, revision.passthrough_platform, revision.format,
       a.name, a.blurb, a.tags, a.is_nsfw, a.discovery,
       a.current_revision_id, a.created_at
  from assets a
  join asset_revisions revision on revision.id = a.current_revision_id
 where a.id = $1
`

type AssetByIDRow struct {
	ID                  pgtype.UUID
	Kind                string
	PassthroughPlatform pgtype.Text
	Format              string
	Name                string
	Blurb               string
	Tags                []string
	IsNsfw              bool
	Discovery           string
	CurrentRevisionID   pgtype.UUID
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) AssetByID(ctx context.Context, id pgtype.UUID) (AssetByIDRow, error) {
	row := q.db.QueryRow(ctx, assetByID, id)
	var i AssetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PassthroughPlatform,
		&i.Format,
		&i.Name,
		&i.Blurb,
		&i.Tags,
		&i.IsNsfw,
		&i.Discovery,
		&i.CurrentRevisionID,
		&i.CreatedAt,
	)
	return i, err
}

const assetPage = `-- name: AssetPage :one
select a.id, a.kind, a.name, a.blurb, a.tags, a.is_nsfw, a.discovery, a.created_at,
       coalesce(owner.username, 'unknown') as creator
  from assets a
  left join users owner on owner.id = a.owner_id
 where a.id = $1
   and a.withheld_at is null
   and a.deleted_at is null
`

type AssetPageRow struct {
	ID        pgtype.UUID
	Kind      string
	Name      string
	Blurb     string
	Tags      []string
	IsNsfw    bool
	Discovery string
	CreatedAt pgtype.Timestamptz
	Creator   string
}

// Unlisted is missing from this predicate on purpose. A stranger holding the
// link gets a normal answer.
func (q *Queries) AssetPage(ctx context.Context, id pgtype.UUID) (AssetPageRow, error) {
	row := q.db.QueryRow(ctx, assetPage, id)
	var i AssetPageRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.Blurb,
		&i.Tags,
		&i.IsNsfw,
		&i.Discovery,
		&i.CreatedAt,
		&i.Creator,
	)
	return i, err
}

const assetPageMedia = `-- name: AssetPageMedia :many
select media.id, media.role, media.width, media.height
  from assets a
  join asset_media media
    on media.asset_id = a.id or media.revision_id = a.current_revision_id
 where a.id = $1
   and media.width is not null
   and media.height is not null
 order by case media.role
            when 'avatar' then 1
            when 'avatar_alt' then 2
            when 'gallery' then 3
            when 'expression' then 4
            else 5
          end,
          media.created_at desc, media.id desc
`

type AssetPageMediaRow struct {
	ID     pgtype.UUID
	Role   string
	Width  pgtype.Int4
	Height pgtype.Int4
}

// The role order matches BrowseAssets, so the first image is the card's cover.
func (q *Queries) AssetPageMedia(ctx context.Context, id pgtype.UUID) ([]AssetPageMediaRow, error) {
	rows, err := q.db.Query(ctx, assetPageMedia, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetPageMediaRow
	for rows.Next() {
		var i AssetPageMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const blobLocation = `-- name: BlobLocation :one
select storage_key, byte_size from blobs where id = $1
`

type BlobLocationRow struct {
	StorageKey string
	ByteSize   int64
}

func (q *Queries) BlobLocation(ctx context.Context, id pgtype.UUID) (BlobLocationRow, error) {
	row := q.db.QueryRow(ctx, blobLocation, id)
	var i BlobLocationRow
	err := row.Scan(&i.StorageKey, &i.ByteSize)
	return i, err
}

const browseAssets = `-- name: BrowseAssets :many
select a.id, a.name, coalesce(owner.username, 'unknown') as creator,
       a.kind, a.is_nsfw, a.created_at,
       cover.id as cover_id, cover.width as cover_width, cover.height as cover_height
  from assets a
  join asset_revisions revision on revision.id = a.current_revision_id
  left join users owner on owner.id = a.owner_id
  left join lateral (
      select media.id, media.width, media.height
        from asset_media media
       where (media.asset_id = a.id or media.revision_id = a.current_revision_id)
         and media.width is not null and media.height is not null
       order by case media.role
                  when 'avatar' then 1
                  when 'avatar_alt' then 2
                  when 'gallery' then 3
                  when 'expression' then 4
                  else 5
                end,
                media.created_at desc, media.id desc
       limit 1
  ) cover on true
 where a.discovery = 'listed'
   and a.withheld_at is null
   and a.deleted_at is null
   and ($1::text = '' or a.kind = $1::text)
   and ($2::text <> 'hidden' or not a.is_nsfw)
   and ($3::text = ''
        or $3::text = 'raw'
        or revision.format = any($4::text[])
        or (revision.format = 'unknown'
            and revision.passthrough_platform = $3::text))
   and (cardinality($5::text[]) = 0 or not exists (
        select 1
          from (select unnest($5::text[]) as key,
                       unnest($6::text[]) as value) selected
         where not exists (
             select 1 from asset_facets stored
              where stored.revision_id = a.current_revision_id
                and stored.key = selected.key and stored.value = selected.value
         )
   ))
   and ($7::text = ''
        or position($7::text in lower(a.name)) > 0
        or position($7::text in lower(a.blurb)) > 0
        or position($7::text in lower(coalesce(owner.username, ''))) > 0)
   and ($8::text = '' or lower(coalesce(owner.username, '')) = $8::text)
   and (cardinality($9::text[]) = 0 or not exists (
        select 1 from unnest($9::text[]) wanted(tag)
         where not exists (
             select 1 from unnest(a.tags) stored(tag)
              where lower(btrim(stored.tag)) = wanted.tag
         )
   ))
   and ($10::timestamptz is null
        or (a.created_at, a.id)
           < ($10::timestamptz, $11::uuid))
 order by a.created_at desc, a.id desc
 limit $12
`

type BrowseAssetsParams struct {
	Kind           string
	NsfwVisibility string
	Platform       string
	Formats        []string
	FacetKeys      []string
	FacetValues    []string
	SearchText     string
	Author         string
	Tags           []string
	Before         pgtype.Timestamptz
	BeforeID       pgtype.UUID
	PageSize       int32
}

type BrowseAssetsRow struct {
	ID          pgtype.UUID
	Name        string
	Creator     string
	Kind        string
	IsNsfw      bool
	CreatedAt   pgtype.Timestamptz
	CoverID     pgtype.UUID
	CoverWidth  pgtype.Int4
	CoverHeight pgtype.Int4
}

func (q *Queries) BrowseAssets(ctx context.Context, arg BrowseAssetsParams) ([]BrowseAssetsRow, error) {
	rows, err := q.db.Query(ctx, browseAssets,
		arg.Kind,
		arg.NsfwVisibility,
		arg.Platform,
		arg.Formats,
		arg.FacetKeys,
		arg.FacetValues,
		arg.SearchText,
		arg.Author,
		arg.Tags,
		arg.Before,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BrowseAssetsRow
	for rows.Next() {
		var i BrowseAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Creator,
			&i.Kind,
			&i.IsNsfw,
			&i.CreatedAt,
			&i.CoverID,
			&i.CoverWidth,
			&i.CoverHeight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearPendingEmailCopies = `-- name: ClearPendingEmailCopies :exec
update users
   set email = null, email_source = null, updated_at = now()
 where email = $1 and id <> $2 and email_verified_at is null
`

type ClearPendingEmailCopiesParams struct {
	Email pgtype.Text
	ID    pgtype.UUID
}

func (q *Queries) ClearPendingEmailCopies(ctx context.Context, arg ClearPendingEmailCopiesParams) error {
	_, err := q.db.Exec(ctx, clearPendingEmailCopies, arg.Email, arg.ID)
	return err
}

const countBrowseAssets = `-- name: CountBrowseAssets :one
select count(*)
  from assets a
  join asset_revisions revision on revision.id = a.current_revision_id
  left join users owner on owner.id = a.owner_id
 where a.discovery = 'listed'
   and a.withheld_at is null
   and a.deleted_at is null
   and ($1::text = '' or a.kind = $1::text)
   and ($2::text <> 'hidden' or not a.is_nsfw)
   and ($3::text = ''
        or $3::text = 'raw'
        or revision.format = any($4::text[])
        or (revision.format = 'unknown'
            and revision.passthrough_platform = $3::text))
   and (cardinality($5::text[]) = 0 or not exists (
        select 1
          from (select unnest($5::text[]) as key,
                       unnest($6::text[]) as value) selected
         where not exists (
             select 1 from asset_facets stored
              where stored.revision_id = a.current_revision_id
                and stored.key = selected.key and stored.value = selected.value
         )
   ))
   and ($7::text = ''
        or position($7::text in lower(a.name)) > 0
        or position($7::text in lower(a.blurb)) > 0
        or position($7::text in lower(coalesce(owner.username, ''))) > 0)
   and ($8::text = '' or lower(coalesce(owner.username, '')) = $8::text)
   and (cardinality($9::text[]) = 0 or not exists (
        select 1 from unnest($9::text[]) wanted(tag)
         where not exists (
             select 1 from unnest(a.tags) stored(tag)
              where lower(btrim(stored.tag)) = wanted.tag
         )
   ))
`

type CountBrowseAssetsParams struct {
	Kind           string
	NsfwVisibility string
	Platform       string
	Formats        []string
	FacetKeys      []string
	FacetValues    []string
	SearchText     string
	Author         string
	Tags           []string
}

func (q *Queries) CountBrowseAssets(ctx context.Context, arg CountBrowseAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBrowseAssets,
		arg.Kind,
		arg.NsfwVisibility,
		arg.Platform,
		arg.Formats,
		arg.FacetKeys,
		arg.FacetValues,
		arg.SearchText,
		arg.Author,
		arg.Tags,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuppressedBrowseAssets = `-- name: CountSuppressedBrowseAssets :one
select count(*)
  from assets a
  join asset_revisions revision on revision.id = a.current_revision_id
  left join users owner on owner.id = a.owner_id
 where a.discovery = 'listed'
   and a.withheld_at is null
   and a.deleted_at is null
   and ($1::text = '' or a.kind = $1::text)
   and ($2::text = ''
        or $2::text = 'raw'
        or revision.format = any($3::text[])
        or (revision.format = 'unknown'
            and revision.passthrough_platform = $2::text))
   and (cardinality($4::text[]) = 0 or not exists (
        select 1
          from (select unnest($4::text[]) as key,
                       unnest($5::text[]) as value) selected
         where not exists (
             select 1 from asset_facets stored
              where stored.revision_id = a.current_revision_id
                and stored.key = selected.key and stored.value = selected.value
         )
   ))
   and ($6::text = ''
        or position($6::text in lower(a.name)) > 0
        or position($6::text in lower(a.blurb)) > 0
        or position($6::text in lower(coalesce(owner.username, ''))) > 0)
   and ($7::text = '' or lower(coalesce(owner.username, '')) = $7::text)
   and (cardinality($8::text[]) = 0 or not exists (
        select 1 from unnest($8::text[]) wanted(tag)
         where not exists (
             select 1 from unnest(a.tags) stored(tag)
              where lower(btrim(stored.tag)) = wanted.tag
         )
   ))
   and a.is_nsfw
`

type CountSuppressedBrowseAssetsParams struct {
	Kind        string
	Platform    string
	Formats     []string
	FacetKeys   []string
	FacetValues []string
	SearchText  string
	Author      string
	Tags        []string
}

func (q *Queries) CountSuppressedBrowseAssets(ctx context.Context, arg CountSuppressedBrowseAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppressedBrowseAssets,
		arg.Kind,
		arg.Platform,
		arg.Formats,
		arg.FacetKeys,
		arg.FacetValues,
		arg.SearchText,
		arg.Author,
		arg.Tags,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const currentRevisionLocation = `-- name: CurrentRevisionLocation :one
select r.blob_id, r.media_type
  from assets a
  join asset_revisions r on r.id = a.current_revision_id
 where a.id = $1
`

type CurrentRevisionLocationRow struct {
	BlobID    pgtype.UUID
	MediaType string
}

func (q *Queries) CurrentRevisionLocation(ctx context.Context, id pgtype.UUID) (CurrentRevisionLocationRow, error) {
	row := q.db.QueryRow(ctx, currentRevisionLocation, id)
	var i CurrentRevisionLocationRow
	err := row.Scan(&i.BlobID, &i.MediaType)
	return i, err
}

const deleteOAuthIdentitiesForUser = `-- name: DeleteOAuthIdentitiesForUser :exec
delete from oauth_identities
 where user_id = $1 and provider = 'discord'
`

func (q *Queries) DeleteOAuthIdentitiesForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthIdentitiesForUser, userID)
	return err
}

const deletePasswordResetForUser = `-- name: DeletePasswordResetForUser :exec
delete from password_reset_tokens where user_id = $1
`

func (q *Queries) DeletePasswordResetForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetForUser, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteVerificationTokensForEmail = `-- name: DeleteVerificationTokensForEmail :exec
delete from email_verification_tokens where email = $1
`

func (q *Queries) DeleteVerificationTokensForEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteVerificationTokensForEmail, email)
	return err
}

const deleteVerificationTokensForUser = `-- name: DeleteVerificationTokensForUser :exec
delete from email_verification_tokens where user_id = $1
`

func (q *Queries) DeleteVerificationTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationTokensForUser, userID)
	return err
}

const discordSubjectsForUser = `-- name: DiscordSubjectsForUser :many
select subject
  from oauth_identities
 where user_id = $1 and provider = 'discord'
 order by subject
`

func (q *Queries) DiscordSubjectsForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, discordSubjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subject string
		if err := rows.Scan(&subject); err != nil {
			return nil, err
		}
		items = append(items, subject)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const handleUnavailable = `-- name: HandleUnavailable :one
select exists (
    select 1 from users where username = $1
    union all
    select 1 from retired_handles where handle = $1
)
`

func (q *Queries) HandleUnavailable(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, handleUnavailable, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAsset = `-- name: InsertAsset :one
insert into assets
  (id, kind, owner_id, name, blurb, tags, is_nsfw, discovery, created_at)
values ($1, $2, $3, $4, $5, $6, $7, $8,
        coalesce($9::timestamptz, now()))
returning created_at
`

type InsertAssetParams struct {
	ID        pgtype.UUID
	Kind      string
	OwnerID   pgtype.UUID
	Name      string
	Blurb     string
	Tags      []string
	IsNsfw    bool
	Discovery string
	CreatedAt pgtype.Timestamptz
}

// indexed_at is left to its default so nothing a caller sends can reach it.
func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertAsset,
		arg.ID,
		arg.Kind,
		arg.OwnerID,
		arg.Name,
		arg.Blurb,
		arg.Tags,
		arg.IsNsfw,
		arg.Discovery,
		arg.CreatedAt,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const insertDiscordUser = `-- name: InsertDiscordUser :one
insert into users (id, username, email, email_verified_at, email_source)
values ($1, $2, $3, $4, case when $3::text is null then null else 'discord' end)
returning id, username, email, email_verified_at
`

type InsertDiscordUserParams struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

type InsertDiscordUserRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) InsertDiscordUser(ctx context.Context, arg InsertDiscordUserParams) (InsertDiscordUserRow, error) {
	row := q.db.QueryRow(ctx, insertDiscordUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.EmailVerifiedAt,
	)
	var i InsertDiscordUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const insertEmailVerificationToken = `-- name: InsertEmailVerificationToken :exec
insert into email_verification_tokens (token_hash, user_id, email, expires_at)
values ($1, $2, $3, $4)
`

type InsertEmailVerificationTokenParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
	Email     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertEmailVerificationToken(ctx context.Context, arg InsertEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, insertEmailVerificationToken,
		arg.TokenHash,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
	)
	return err
}

const insertFacet = `-- name: InsertFacet :exec
insert into asset_facets (revision_id, key, value)
values ($1, $2, $3)
on conflict do nothing
`

type InsertFacetParams struct {
	RevisionID pgtype.UUID
	Key        string
	Value      string
}

func (q *Queries) InsertFacet(ctx context.Context, arg InsertFacetParams) error {
	_, err := q.db.Exec(ctx, insertFacet, arg.RevisionID, arg.Key, arg.Value)
	return err
}

const insertOAuthIdentity = `-- name: InsertOAuthIdentity :exec
insert into oauth_identities (user_id, provider, subject, provider_email)
values ($1, $2, $3, $4)
`

type InsertOAuthIdentityParams struct {
	UserID        pgtype.UUID
	Provider      string
	Subject       string
	ProviderEmail pgtype.Text
}

func (q *Queries) InsertOAuthIdentity(ctx context.Context, arg InsertOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, insertOAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.ProviderEmail,
	)
	return err
}

const insertOAuthState = `-- name: InsertOAuthState :exec
insert into oauth_states (token_hash, intent, user_id, expires_at)
values ($1, $2, $3, $4)
`

type InsertOAuthStateParams struct {
	TokenHash []byte
	Intent    string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertOAuthState(ctx context.Context, arg InsertOAuthStateParams) error {
	_, err := q.db.Exec(ctx, insertOAuthState,
		arg.TokenHash,
		arg.Intent,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const insertPasswordReset = `-- name: InsertPasswordReset :exec
insert into password_reset_tokens (token_hash, user_id, expires_at)
values ($1, $2, $3)
`

type InsertPasswordResetParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertPasswordReset(ctx context.Context, arg InsertPasswordResetParams) error {
	_, err := q.db.Exec(ctx, insertPasswordReset, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const insertRetiredHandle = `-- name: InsertRetiredHandle :exec
insert into retired_handles (handle) values ($1)
`

func (q *Queries) InsertRetiredHandle(ctx context.Context, handle string) error {
	_, err := q.db.Exec(ctx, insertRetiredHandle, handle)
	return err
}

const insertRevision = `-- name: InsertRevision :exec
insert into asset_revisions
  (id, asset_id, revision, blob_id, media_type, format, passthrough_platform)
values ($1, $2, $3, $4, $5, $6, $7)
`

type InsertRevisionParams struct {
	ID                  pgtype.UUID
	AssetID             pgtype.UUID
	Revision            int32
	BlobID              pgtype.UUID
	MediaType           string
	Format              string
	PassthroughPlatform pgtype.Text
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) error {
	_, err := q.db.Exec(ctx, insertRevision,
		arg.ID,
		arg.AssetID,
		arg.Revision,
		arg.BlobID,
		arg.MediaType,
		arg.Format,
		arg.PassthroughPlatform,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
insert into sessions (token_hash, user_id, expires_at)
values ($1, $2, $3)
`

type InsertSessionParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const insertUser = `-- name: InsertUser :one
insert into users (id, username, email, password_hash, email_source)
values ($1, $2, $3, $4, 'creator')
returning id, username, email, email_verified_at
`

type InsertUserParams struct {
	ID           pgtype.UUID
	Username     string
	Email        pgtype.Text
	PasswordHash pgtype.Text
}

type InsertUserRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
with facet_pairs as (
  select unnest($5::text[]) as k, unnest($6::text[]) as v
)
select a.id, a.kind, revision.passthrough_platform, revision.format,
       a.name, a.blurb, a.tags, a.is_nsfw, a.discovery,
       a.current_revision_id, a.created_at
  from assets a
  join asset_revisions revision on revision.id = a.current_revision_id
 where a.discovery = 'listed'
   and a.withheld_at is null
   and a.deleted_at is null
   and ($1 = '' or a.kind = $1)
   and (not $2::boolean or revision.passthrough_platform is not distinct from $3)
   and ($4::text[] is null or a.tags @> $4)
   and (array_length($5::text[], 1) is null or (
         select count(*) from asset_facets af
          where af.revision_id = a.current_revision_id
            and (af.key, af.value) in (
                  select k, v from facet_pairs
            )
       ) = array_length($5::text[], 1))
   and ($8::timestamptz is null
        or (a.created_at, a.id)
           < ($8::timestamptz, $9::uuid))
 order by a.created_at desc, a.id desc
 limit $7
`

type ListAssetsParams struct {
	Column1             interface{}
	Column2             bool
	PassthroughPlatform pgtype.Text
	Column4             []string
	Column5             []string
	Column6             []string
	Limit               int32
	Before              pgtype.Timestamptz
	BeforeID            pgtype.UUID
}

type ListAssetsRow struct {
	ID                  pgtype.UUID
	Kind                string
	PassthroughPlatform pgtype.Text
	Format              string
	Name                string
	Blurb               string
	Tags                []string
	IsNsfw              bool
	Discovery           string
	CurrentRevisionID   pgtype.UUID
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.Column1,
		arg.Column2,
		arg.PassthroughPlatform,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Before,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsRow
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.PassthroughPlatform,
			&i.Format,
			&i.Name,
			&i.Blurb,
			&i.Tags,
			&i.IsNsfw,
			&i.Discovery,
			&i.CurrentRevisionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEmail = `-- name: LockEmail :one
select 1 from pg_advisory_xact_lock(
    hashtextextended('lumihub-email:' || $1::text, 0)
)
`

func (q *Queries) LockEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, lockEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lockHandle = `-- name: LockHandle :one
select 1 from pg_advisory_xact_lock(
    hashtextextended('lumihub-handle:' || $1::text, 0)
)
`

func (q *Queries) LockHandle(ctx context.Context, handle string) (int32, error) {
	row := q.db.QueryRow(ctx, lockHandle, handle)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lockOAuthIdentity = `-- name: LockOAuthIdentity :one
select 1 from pg_advisory_xact_lock(
    hashtextextended('lumihub-oauth:' || $1::text || ':' ||
                     $2::text, 0)
)
`

type LockOAuthIdentityParams struct {
	Provider string
	Subject  string
}

func (q *Queries) LockOAuthIdentity(ctx context.Context, arg LockOAuthIdentityParams) (int32, error) {
	row := q.db.QueryRow(ctx, lockOAuthIdentity, arg.Provider, arg.Subject)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lockOAuthUser = `-- name: LockOAuthUser :one
select 1 from pg_advisory_xact_lock(
    hashtextextended('lumihub-oauth-user:' || $1::uuid::text, 0)
)
`

func (q *Queries) LockOAuthUser(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, lockOAuthUser, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const nSFWVisibilityBySessionHash = `-- name: NSFWVisibilityBySessionHash :one
select u.nsfw_visibility
  from sessions session
  join users u on u.id = session.user_id
 where session.token_hash = $1 and session.expires_at > now()
`

func (q *Queries) NSFWVisibilityBySessionHash(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, nSFWVisibilityBySessionHash, tokenHash)
	var nsfw_visibility string
	err := row.Scan(&nsfw_visibility)
	return nsfw_visibility, err
}

const profileByHandle = `-- name: ProfileByHandle :one
select id, username from users where username = $1
`

type ProfileByHandleRow struct {
	ID       pgtype.UUID
	Username string
}

func (q *Queries) ProfileByHandle(ctx context.Context, username string) (ProfileByHandleRow, error) {
	row := q.db.QueryRow(ctx, profileByHandle, username)
	var i ProfileByHandleRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const replacePassword = `-- name: ReplacePassword :exec
update users
   set password_hash = $2, updated_at = now()
 where id = $1
`

type ReplacePasswordParams struct {
	ID           pgtype.UUID
	PasswordHash pgtype.Text
}

func (q *Queries) ReplacePassword(ctx context.Context, arg ReplacePasswordParams) error {
	_, err := q.db.Exec(ctx, replacePassword, arg.ID, arg.PasswordHash)
	return err
}

const setCurrentRevision = `-- name: SetCurrentRevision :exec
update assets set current_revision_id = $2, updated_at = now() where id = $1
`

type SetCurrentRevisionParams struct {
	ID                pgtype.UUID
	CurrentRevisionID pgtype.UUID
}

func (q *Queries) SetCurrentRevision(ctx context.Context, arg SetCurrentRevisionParams) error {
	_, err := q.db.Exec(ctx, setCurrentRevision, arg.ID, arg.CurrentRevisionID)
	return err
}

const setFirstPassword = `-- name: SetFirstPassword :one
update users
   set password_hash = $2, updated_at = now()
 where id = $1 and password_hash is null
returning id, username, email, email_verified_at
`

type SetFirstPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash pgtype.Text
}

type SetFirstPasswordRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) SetFirstPassword(ctx context.Context, arg SetFirstPasswordParams) (SetFirstPasswordRow, error) {
	row := q.db.QueryRow(ctx, setFirstPassword, arg.ID, arg.PasswordHash)
	var i SetFirstPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const setNSFWVisibilityBySessionHash = `-- name: SetNSFWVisibilityBySessionHash :execrows
update users u
   set nsfw_visibility = $1, updated_at = now()
  from sessions session
 where session.user_id = u.id and session.token_hash = $2
   and session.expires_at > now()
`

type SetNSFWVisibilityBySessionHashParams struct {
	NsfwVisibility string
	TokenHash      []byte
}

func (q *Queries) SetNSFWVisibilityBySessionHash(ctx context.Context, arg SetNSFWVisibilityBySessionHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNSFWVisibilityBySessionHash, arg.NsfwVisibility, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeOAuthState = `-- name: TakeOAuthState :one
delete from oauth_states
 where token_hash = $1 and expires_at > now()
returning intent, user_id
`

type TakeOAuthStateRow struct {
	Intent string
	UserID pgtype.UUID
}

func (q *Queries) TakeOAuthState(ctx context.Context, tokenHash []byte) (TakeOAuthStateRow, error) {
	row := q.db.QueryRow(ctx, takeOAuthState, tokenHash)
	var i TakeOAuthStateRow
	err := row.Scan(&i.Intent, &i.UserID)
	return i, err
}

const takePasswordReset = `-- name: TakePasswordReset :one
delete from password_reset_tokens
 where token_hash = $1 and expires_at > now()
returning user_id
`

func (q *Queries) TakePasswordReset(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, takePasswordReset, tokenHash)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const updateDiscordEmail = `-- name: UpdateDiscordEmail :one
update users
   set email = $2, email_verified_at = now(), email_source = 'discord', updated_at = now()
 where id = $1
   and (email is null or email_source = 'discord')
returning id, username, email, email_verified_at, email_source
`

type UpdateDiscordEmailParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

type UpdateDiscordEmailRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	EmailSource     pgtype.Text
}

func (q *Queries) UpdateDiscordEmail(ctx context.Context, arg UpdateDiscordEmailParams) (UpdateDiscordEmailRow, error) {
	row := q.db.QueryRow(ctx, updateDiscordEmail, arg.ID, arg.Email)
	var i UpdateDiscordEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.EmailSource,
	)
	return i, err
}

const updateOAuthIdentityEmail = `-- name: UpdateOAuthIdentityEmail :exec
update oauth_identities
   set provider_email = $3, updated_at = now()
 where provider = $1 and subject = $2
`

type UpdateOAuthIdentityEmailParams struct {
	Provider      string
	Subject       string
	ProviderEmail pgtype.Text
}

func (q *Queries) UpdateOAuthIdentityEmail(ctx context.Context, arg UpdateOAuthIdentityEmailParams) error {
	_, err := q.db.Exec(ctx, updateOAuthIdentityEmail, arg.Provider, arg.Subject, arg.ProviderEmail)
	return err
}

const updateUnverifiedEmail = `-- name: UpdateUnverifiedEmail :one
update users
   set email = $2, email_source = 'creator', updated_at = now()
 where id = $1 and email_verified_at is null
returning id, username, email, email_verified_at
`

type UpdateUnverifiedEmailParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

type UpdateUnverifiedEmailRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUnverifiedEmail(ctx context.Context, arg UpdateUnverifiedEmailParams) (UpdateUnverifiedEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUnverifiedEmail, arg.ID, arg.Email)
	var i UpdateUnverifiedEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const updateUserHandle = `-- name: UpdateUserHandle :one
update users set username = $2, updated_at = now() where id = $1
returning id, username, email, email_verified_at
`

type UpdateUserHandleParams struct {
	ID       pgtype.UUID
	Username string
}

type UpdateUserHandleRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUserHandle(ctx context.Context, arg UpdateUserHandleParams) (UpdateUserHandleRow, error) {
	row := q.db.QueryRow(ctx, updateUserHandle, arg.ID, arg.Username)
	var i UpdateUserHandleRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const upsertBlob = `-- name: UpsertBlob :one
insert into blobs (id, sha256, byte_size, storage_key)
values ($1, $2, $3, $4)
on conflict (sha256) do update set sha256 = excluded.sha256
returning id, sha256, byte_size, storage_key
`

type UpsertBlobParams struct {
	ID         pgtype.UUID
	Sha256     []byte
	ByteSize   int64
	StorageKey string
}

func (q *Queries) UpsertBlob(ctx context.Context, arg UpsertBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, upsertBlob,
		arg.ID,
		arg.Sha256,
		arg.ByteSize,
		arg.StorageKey,
	)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.ByteSize,
		&i.StorageKey,
	)
	return i, err
}

const userByOAuthIdentity = `-- name: UserByOAuthIdentity :one
select u.id, u.username, u.email, u.email_verified_at, u.email_source,
       case when u.password_hash is null then false else true end as has_password
  from oauth_identities oi
  join users u on u.id = oi.user_id
 where oi.provider = $1 and oi.subject = $2
`

type UserByOAuthIdentityParams struct {
	Provider string
	Subject  string
}

type UserByOAuthIdentityRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	EmailSource     pgtype.Text
	HasPassword     bool
}

func (q *Queries) UserByOAuthIdentity(ctx context.Context, arg UserByOAuthIdentityParams) (UserByOAuthIdentityRow, error) {
	row := q.db.QueryRow(ctx, userByOAuthIdentity, arg.Provider, arg.Subject)
	var i UserByOAuthIdentityRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.EmailSource,
		&i.HasPassword,
	)
	return i, err
}

const userBySessionHash = `-- name: UserBySessionHash :one
select u.id, u.username, u.email, u.email_verified_at,
       case when u.password_hash is null then false else true end as has_password,
       exists (
           select 1 from oauth_identities oi
            where oi.user_id = u.id and oi.provider = 'discord'
       ) as discord_linked
  from sessions s
  join users u on u.id = s.user_id
 where s.token_hash = $1 and s.expires_at > now()
`

type UserBySessionHashRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	HasPassword     bool
	DiscordLinked   bool
}

func (q *Queries) UserBySessionHash(ctx context.Context, tokenHash []byte) (UserBySessionHashRow, error) {
	row := q.db.QueryRow(ctx, userBySessionHash, tokenHash)
	var i UserBySessionHashRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.HasPassword,
		&i.DiscordLinked,
	)
	return i, err
}

const userForDiscordAttach = `-- name: UserForDiscordAttach :one
select id, username, email, email_verified_at, email_source,
       case when password_hash is null then false else true end as has_password
  from users
 where id = $1
 for update
`

type UserForDiscordAttachRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	EmailSource     pgtype.Text
	HasPassword     bool
}

func (q *Queries) UserForDiscordAttach(ctx context.Context, id pgtype.UUID) (UserForDiscordAttachRow, error) {
	row := q.db.QueryRow(ctx, userForDiscordAttach, id)
	var i UserForDiscordAttachRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.EmailSource,
		&i.HasPassword,
	)
	return i, err
}

const userHandleForUpdate = `-- name: UserHandleForUpdate :one
select username from users where id = $1 for update
`

func (q *Queries) UserHandleForUpdate(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, userHandleForUpdate, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const usersForSignIn = `-- name: UsersForSignIn :many
select u.id, u.username, u.email, u.email_verified_at, u.password_hash,
       exists (
           select 1 from oauth_identities oi
            where oi.user_id = u.id and oi.provider = 'discord'
       ) as discord_linked
  from users u
 where u.email = $1 and u.password_hash is not null
`

type UsersForSignInRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	PasswordHash    pgtype.Text
	DiscordLinked   bool
}

func (q *Queries) UsersForSignIn(ctx context.Context, email pgtype.Text) ([]UsersForSignInRow, error) {
	rows, err := q.db.Query(ctx, usersForSignIn, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersForSignInRow
	for rows.Next() {
		var i UsersForSignInRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.PasswordHash,
			&i.DiscordLinked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verificationByHash = `-- name: VerificationByHash :one
select user_id, email
  from email_verification_tokens
 where token_hash = $1 and expires_at > now()
 for update
`

type VerificationByHashRow struct {
	UserID pgtype.UUID
	Email  string
}

func (q *Queries) VerificationByHash(ctx context.Context, tokenHash []byte) (VerificationByHashRow, error) {
	row := q.db.QueryRow(ctx, verificationByHash, tokenHash)
	var i VerificationByHashRow
	err := row.Scan(&i.UserID, &i.Email)
	return i, err
}

const verificationEmailByHash = `-- name: VerificationEmailByHash :one
select email
  from email_verification_tokens
 where token_hash = $1 and expires_at > now()
`

func (q *Queries) VerificationEmailByHash(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, verificationEmailByHash, tokenHash)
	var email string
	err := row.Scan(&email)
	return email, err
}

const verifiedEmailBelongsToDiscordAccount = `-- name: VerifiedEmailBelongsToDiscordAccount :one
select exists (
    select 1
      from users u
      join oauth_identities oi on oi.user_id = u.id and oi.provider = 'discord'
     where u.email = $1 and u.email_verified_at is not null
)
`

func (q *Queries) VerifiedEmailBelongsToDiscordAccount(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, verifiedEmailBelongsToDiscordAccount, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifiedEmailExists = `-- name: VerifiedEmailExists :one
select exists (
    select 1 from users where email = $1 and email_verified_at is not null
)
`

func (q *Queries) VerifiedEmailExists(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, verifiedEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifiedUserIDByEmail = `-- name: VerifiedUserIDByEmail :one
select id from users where email = $1 and email_verified_at is not null
`

func (q *Queries) VerifiedUserIDByEmail(ctx context.Context, email pgtype.Text) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifiedUserIDByEmail, email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
with verified as (
    update users
       set email_verified_at = now(), updated_at = now()
     where users.id = $1 and users.email = $2 and users.email_verified_at is null
    returning users.id, users.username, users.email,
              users.email_verified_at, users.password_hash
)
select v.id, v.username, v.email, v.email_verified_at,
       case when v.password_hash is null then false else true end as has_password,
       exists (
           select 1 from oauth_identities oi
            where oi.user_id = v.id and oi.provider = 'discord'
       ) as discord_linked
  from verified v
`

type VerifyUserEmailParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

type VerifyUserEmailRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	HasPassword     bool
	DiscordLinked   bool
}

func (q *Queries) VerifyUserEmail(ctx context.Context, arg VerifyUserEmailParams) (VerifyUserEmailRow, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, arg.ID, arg.Email)
	var i VerifyUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.HasPassword,
		&i.DiscordLinked,
	)
	return i, err
}
