// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blobLocation = `-- name: BlobLocation :one
select storage_key, byte_size from blobs where id = $1
`

type BlobLocationRow struct {
	StorageKey string
	ByteSize   int64
}

func (q *Queries) BlobLocation(ctx context.Context, id pgtype.UUID) (BlobLocationRow, error) {
	row := q.db.QueryRow(ctx, blobLocation, id)
	var i BlobLocationRow
	err := row.Scan(&i.StorageKey, &i.ByteSize)
	return i, err
}

const clearPendingEmailCopies = `-- name: ClearPendingEmailCopies :exec
update users
   set email = null, email_source = null, updated_at = now()
 where email = $1 and id <> $2 and email_verified_at is null
`

type ClearPendingEmailCopiesParams struct {
	Email pgtype.Text
	ID    pgtype.UUID
}

func (q *Queries) ClearPendingEmailCopies(ctx context.Context, arg ClearPendingEmailCopiesParams) error {
	_, err := q.db.Exec(ctx, clearPendingEmailCopies, arg.Email, arg.ID)
	return err
}

const currentRevisionLocation = `-- name: CurrentRevisionLocation :one
select r.blob_id, r.media_type
  from assets a
  join asset_revisions r on r.id = a.current_revision_id
 where a.id = $1
`

type CurrentRevisionLocationRow struct {
	BlobID    pgtype.UUID
	MediaType string
}

func (q *Queries) CurrentRevisionLocation(ctx context.Context, id pgtype.UUID) (CurrentRevisionLocationRow, error) {
	row := q.db.QueryRow(ctx, currentRevisionLocation, id)
	var i CurrentRevisionLocationRow
	err := row.Scan(&i.BlobID, &i.MediaType)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
delete from sessions where token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteVerificationTokensForEmail = `-- name: DeleteVerificationTokensForEmail :exec
delete from email_verification_tokens where email = $1
`

func (q *Queries) DeleteVerificationTokensForEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteVerificationTokensForEmail, email)
	return err
}

const deleteVerificationTokensForUser = `-- name: DeleteVerificationTokensForUser :exec
delete from email_verification_tokens where user_id = $1
`

func (q *Queries) DeleteVerificationTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationTokensForUser, userID)
	return err
}

const handleUnavailable = `-- name: HandleUnavailable :one
select exists (
    select 1 from users where username = $1
    union all
    select 1 from retired_handles where handle = $1
)
`

func (q *Queries) HandleUnavailable(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, handleUnavailable, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAsset = `-- name: InsertAsset :one
insert into assets
  (id, kind, owner_id, name, description, tags, is_nsfw, discovery, created_at)
values ($1, $2, $3, $4, $5, $6, $7, $8,
        coalesce($9::timestamptz, now()))
returning created_at
`

type InsertAssetParams struct {
	ID          pgtype.UUID
	Kind        string
	OwnerID     pgtype.UUID
	Name        string
	Description string
	Tags        []string
	IsNsfw      bool
	Discovery   string
	CreatedAt   pgtype.Timestamptz
}

// indexed_at is left to its default so nothing a caller sends can reach it.
func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertAsset,
		arg.ID,
		arg.Kind,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.IsNsfw,
		arg.Discovery,
		arg.CreatedAt,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const insertEmailVerificationToken = `-- name: InsertEmailVerificationToken :exec
insert into email_verification_tokens (token_hash, user_id, email, expires_at)
values ($1, $2, $3, $4)
`

type InsertEmailVerificationTokenParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
	Email     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertEmailVerificationToken(ctx context.Context, arg InsertEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, insertEmailVerificationToken,
		arg.TokenHash,
		arg.UserID,
		arg.Email,
		arg.ExpiresAt,
	)
	return err
}

const insertFacet = `-- name: InsertFacet :exec
insert into asset_facets (revision_id, key, value)
values ($1, $2, $3)
on conflict do nothing
`

type InsertFacetParams struct {
	RevisionID pgtype.UUID
	Key        string
	Value      string
}

func (q *Queries) InsertFacet(ctx context.Context, arg InsertFacetParams) error {
	_, err := q.db.Exec(ctx, insertFacet, arg.RevisionID, arg.Key, arg.Value)
	return err
}

const insertRetiredHandle = `-- name: InsertRetiredHandle :exec
insert into retired_handles (handle) values ($1)
`

func (q *Queries) InsertRetiredHandle(ctx context.Context, handle string) error {
	_, err := q.db.Exec(ctx, insertRetiredHandle, handle)
	return err
}

const insertRevision = `-- name: InsertRevision :exec
insert into asset_revisions
  (id, asset_id, revision, blob_id, media_type, format, passthrough_platform)
values ($1, $2, $3, $4, $5, $6, $7)
`

type InsertRevisionParams struct {
	ID                  pgtype.UUID
	AssetID             pgtype.UUID
	Revision            int32
	BlobID              pgtype.UUID
	MediaType           string
	Format              string
	PassthroughPlatform pgtype.Text
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) error {
	_, err := q.db.Exec(ctx, insertRevision,
		arg.ID,
		arg.AssetID,
		arg.Revision,
		arg.BlobID,
		arg.MediaType,
		arg.Format,
		arg.PassthroughPlatform,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
insert into sessions (token_hash, user_id, expires_at)
values ($1, $2, $3)
`

type InsertSessionParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const insertUser = `-- name: InsertUser :one
insert into users (id, username, email, password_hash, email_source)
values ($1, $2, $3, $4, 'creator')
returning id, username, email, email_verified_at
`

type InsertUserParams struct {
	ID           pgtype.UUID
	Username     string
	Email        pgtype.Text
	PasswordHash pgtype.Text
}

type InsertUserRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
with facet_pairs as (
  select unnest($5::text[]) as k, unnest($6::text[]) as v
)
select a.id, a.kind, revision.passthrough_platform, revision.format,
       a.name, a.description, a.tags, a.is_nsfw, a.discovery,
       a.current_revision_id, a.created_at
  from assets a
  join asset_revisions revision on revision.id = a.current_revision_id
 where a.discovery = 'listed'
   and a.withheld_at is null
   and a.deleted_at is null
   and ($1 = '' or a.kind = $1)
   and (not $2::boolean or revision.passthrough_platform is not distinct from $3)
   and ($4::text[] is null or a.tags @> $4)
   and (array_length($5::text[], 1) is null or (
         select count(*) from asset_facets af
          where af.revision_id = a.current_revision_id
            and (af.key, af.value) in (
                  select k, v from facet_pairs
            )
       ) = array_length($5::text[], 1))
   and ($8::timestamptz is null
        or (a.created_at, a.id)
           < ($8::timestamptz, $9::uuid))
 order by a.created_at desc, a.id desc
 limit $7
`

type ListAssetsParams struct {
	Column1             interface{}
	Column2             bool
	PassthroughPlatform pgtype.Text
	Column4             []string
	Column5             []string
	Column6             []string
	Limit               int32
	Before              pgtype.Timestamptz
	BeforeID            pgtype.UUID
}

type ListAssetsRow struct {
	ID                  pgtype.UUID
	Kind                string
	PassthroughPlatform pgtype.Text
	Format              string
	Name                string
	Description         string
	Tags                []string
	IsNsfw              bool
	Discovery           string
	CurrentRevisionID   pgtype.UUID
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.Column1,
		arg.Column2,
		arg.PassthroughPlatform,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Before,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsRow
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.PassthroughPlatform,
			&i.Format,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.IsNsfw,
			&i.Discovery,
			&i.CurrentRevisionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEmail = `-- name: LockEmail :one
select 1 from pg_advisory_xact_lock(
    hashtextextended('lumihub-email:' || $1::text, 0)
)
`

func (q *Queries) LockEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, lockEmail, email)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const lockHandle = `-- name: LockHandle :one
select 1 from pg_advisory_xact_lock(
    hashtextextended('lumihub-handle:' || $1::text, 0)
)
`

func (q *Queries) LockHandle(ctx context.Context, handle string) (int32, error) {
	row := q.db.QueryRow(ctx, lockHandle, handle)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const profileByHandle = `-- name: ProfileByHandle :one
select id, username from users where username = $1
`

type ProfileByHandleRow struct {
	ID       pgtype.UUID
	Username string
}

func (q *Queries) ProfileByHandle(ctx context.Context, username string) (ProfileByHandleRow, error) {
	row := q.db.QueryRow(ctx, profileByHandle, username)
	var i ProfileByHandleRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const setCurrentRevision = `-- name: SetCurrentRevision :exec
update assets set current_revision_id = $2, updated_at = now() where id = $1
`

type SetCurrentRevisionParams struct {
	ID                pgtype.UUID
	CurrentRevisionID pgtype.UUID
}

func (q *Queries) SetCurrentRevision(ctx context.Context, arg SetCurrentRevisionParams) error {
	_, err := q.db.Exec(ctx, setCurrentRevision, arg.ID, arg.CurrentRevisionID)
	return err
}

const updateUnverifiedEmail = `-- name: UpdateUnverifiedEmail :one
update users
   set email = $2, email_source = 'creator', updated_at = now()
 where id = $1 and email_verified_at is null
returning id, username, email, email_verified_at
`

type UpdateUnverifiedEmailParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

type UpdateUnverifiedEmailRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUnverifiedEmail(ctx context.Context, arg UpdateUnverifiedEmailParams) (UpdateUnverifiedEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUnverifiedEmail, arg.ID, arg.Email)
	var i UpdateUnverifiedEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const updateUserHandle = `-- name: UpdateUserHandle :one
update users set username = $2, updated_at = now() where id = $1
returning id, username, email, email_verified_at
`

type UpdateUserHandleParams struct {
	ID       pgtype.UUID
	Username string
}

type UpdateUserHandleRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUserHandle(ctx context.Context, arg UpdateUserHandleParams) (UpdateUserHandleRow, error) {
	row := q.db.QueryRow(ctx, updateUserHandle, arg.ID, arg.Username)
	var i UpdateUserHandleRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const upsertBlob = `-- name: UpsertBlob :one
insert into blobs (id, sha256, byte_size, storage_key)
values ($1, $2, $3, $4)
on conflict (sha256) do update set sha256 = excluded.sha256
returning id, sha256, byte_size, storage_key
`

type UpsertBlobParams struct {
	ID         pgtype.UUID
	Sha256     []byte
	ByteSize   int64
	StorageKey string
}

func (q *Queries) UpsertBlob(ctx context.Context, arg UpsertBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, upsertBlob,
		arg.ID,
		arg.Sha256,
		arg.ByteSize,
		arg.StorageKey,
	)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.ByteSize,
		&i.StorageKey,
	)
	return i, err
}

const userBySessionHash = `-- name: UserBySessionHash :one
select u.id, u.username, u.email, u.email_verified_at
  from sessions s
  join users u on u.id = s.user_id
 where s.token_hash = $1 and s.expires_at > now()
`

type UserBySessionHashRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) UserBySessionHash(ctx context.Context, tokenHash []byte) (UserBySessionHashRow, error) {
	row := q.db.QueryRow(ctx, userBySessionHash, tokenHash)
	var i UserBySessionHashRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}

const userHandleForUpdate = `-- name: UserHandleForUpdate :one
select username from users where id = $1 for update
`

func (q *Queries) UserHandleForUpdate(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, userHandleForUpdate, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const usersForSignIn = `-- name: UsersForSignIn :many
select id, username, email, email_verified_at, password_hash
  from users
 where email = $1 and password_hash is not null
`

type UsersForSignInRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
	PasswordHash    pgtype.Text
}

func (q *Queries) UsersForSignIn(ctx context.Context, email pgtype.Text) ([]UsersForSignInRow, error) {
	rows, err := q.db.Query(ctx, usersForSignIn, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersForSignInRow
	for rows.Next() {
		var i UsersForSignInRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verificationByHash = `-- name: VerificationByHash :one
select user_id, email
  from email_verification_tokens
 where token_hash = $1 and expires_at > now()
 for update
`

type VerificationByHashRow struct {
	UserID pgtype.UUID
	Email  string
}

func (q *Queries) VerificationByHash(ctx context.Context, tokenHash []byte) (VerificationByHashRow, error) {
	row := q.db.QueryRow(ctx, verificationByHash, tokenHash)
	var i VerificationByHashRow
	err := row.Scan(&i.UserID, &i.Email)
	return i, err
}

const verificationEmailByHash = `-- name: VerificationEmailByHash :one
select email
  from email_verification_tokens
 where token_hash = $1 and expires_at > now()
`

func (q *Queries) VerificationEmailByHash(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, verificationEmailByHash, tokenHash)
	var email string
	err := row.Scan(&email)
	return email, err
}

const verifiedEmailExists = `-- name: VerifiedEmailExists :one
select exists (
    select 1 from users where email = $1 and email_verified_at is not null
)
`

func (q *Queries) VerifiedEmailExists(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, verifiedEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
update users
   set email_verified_at = now(), updated_at = now()
 where id = $1 and email = $2 and email_verified_at is null
returning id, username, email, email_verified_at
`

type VerifyUserEmailParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

type VerifyUserEmailRow struct {
	ID              pgtype.UUID
	Username        string
	Email           pgtype.Text
	EmailVerifiedAt pgtype.Timestamptz
}

func (q *Queries) VerifyUserEmail(ctx context.Context, arg VerifyUserEmailParams) (VerifyUserEmailRow, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, arg.ID, arg.Email)
	var i VerifyUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerifiedAt,
	)
	return i, err
}
