// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blobLocation = `-- name: BlobLocation :one
select storage_key, byte_size from blobs where id = $1
`

type BlobLocationRow struct {
	StorageKey string
	ByteSize   int64
}

func (q *Queries) BlobLocation(ctx context.Context, id pgtype.UUID) (BlobLocationRow, error) {
	row := q.db.QueryRow(ctx, blobLocation, id)
	var i BlobLocationRow
	err := row.Scan(&i.StorageKey, &i.ByteSize)
	return i, err
}

const currentRevisionLocation = `-- name: CurrentRevisionLocation :one
select r.blob_id, r.media_type
  from assets a
  join asset_revisions r on r.id = a.current_revision_id
 where a.id = $1
`

type CurrentRevisionLocationRow struct {
	BlobID    pgtype.UUID
	MediaType string
}

func (q *Queries) CurrentRevisionLocation(ctx context.Context, id pgtype.UUID) (CurrentRevisionLocationRow, error) {
	row := q.db.QueryRow(ctx, currentRevisionLocation, id)
	var i CurrentRevisionLocationRow
	err := row.Scan(&i.BlobID, &i.MediaType)
	return i, err
}

const deleteBlob = `-- name: DeleteBlob :one
delete from blobs where id = $1 returning storage_key
`

func (q *Queries) DeleteBlob(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteBlob, id)
	var storage_key string
	err := row.Scan(&storage_key)
	return storage_key, err
}

const insertAsset = `-- name: InsertAsset :one
insert into assets
  (id, kind, platform, format, format_version, owner_id,
   name, description, tags, is_nsfw, publication, created_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
        coalesce($12::timestamptz, now()))
returning created_at
`

type InsertAssetParams struct {
	ID            pgtype.UUID
	Kind          string
	Platform      pgtype.Text
	Format        string
	FormatVersion string
	OwnerID       pgtype.UUID
	Name          string
	Description   string
	Tags          []string
	IsNsfw        bool
	Publication   string
	CreatedAt     pgtype.Timestamptz
}

// indexed_at is left to its default so nothing a caller sends can reach it.
func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertAsset,
		arg.ID,
		arg.Kind,
		arg.Platform,
		arg.Format,
		arg.FormatVersion,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.IsNsfw,
		arg.Publication,
		arg.CreatedAt,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const insertFacet = `-- name: InsertFacet :exec
insert into asset_facets (asset_id, revision_id, key, value)
values ($1, $2, $3, $4)
on conflict do nothing
`

type InsertFacetParams struct {
	AssetID    pgtype.UUID
	RevisionID pgtype.UUID
	Key        string
	Value      string
}

func (q *Queries) InsertFacet(ctx context.Context, arg InsertFacetParams) error {
	_, err := q.db.Exec(ctx, insertFacet,
		arg.AssetID,
		arg.RevisionID,
		arg.Key,
		arg.Value,
	)
	return err
}

const insertRevision = `-- name: InsertRevision :exec
insert into asset_revisions
  (id, asset_id, revision, blob_id, media_type)
values ($1, $2, $3, $4, $5)
`

type InsertRevisionParams struct {
	ID        pgtype.UUID
	AssetID   pgtype.UUID
	Revision  int32
	BlobID    pgtype.UUID
	MediaType string
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) error {
	_, err := q.db.Exec(ctx, insertRevision,
		arg.ID,
		arg.AssetID,
		arg.Revision,
		arg.BlobID,
		arg.MediaType,
	)
	return err
}

const listAssets = `-- name: ListAssets :many
with facet_pairs as (
  select unnest($5::text[]) as k, unnest($6::text[]) as v
)
select a.id, a.kind, a.platform, a.format, a.format_version,
       a.name, a.description, a.tags, a.is_nsfw, a.publication,
       a.current_revision_id, a.created_at
  from assets a
 where a.publication = 'public'
   and ($1 = '' or a.kind = $1)
   and (not $2::boolean or a.platform is not distinct from $3)
   and ($4::text[] is null or a.tags @> $4)
   and (array_length($5::text[], 1) is null or (
         select count(*) from asset_facets af
          where af.asset_id = a.id
            and (af.key, af.value) in (
                  select k, v from facet_pairs
            )
       ) = array_length($5::text[], 1))
   and ($8::timestamptz is null
        or (a.created_at, a.id)
           < ($8::timestamptz, $9::uuid))
 order by a.created_at desc, a.id desc
 limit $7
`

type ListAssetsParams struct {
	Column1  interface{}
	Column2  bool
	Platform pgtype.Text
	Column4  []string
	Column5  []string
	Column6  []string
	Limit    int32
	Before   pgtype.Timestamptz
	BeforeID pgtype.UUID
}

type ListAssetsRow struct {
	ID                pgtype.UUID
	Kind              string
	Platform          pgtype.Text
	Format            string
	FormatVersion     string
	Name              string
	Description       string
	Tags              []string
	IsNsfw            bool
	Publication       string
	CurrentRevisionID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]ListAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.Column1,
		arg.Column2,
		arg.Platform,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Before,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsRow
	for rows.Next() {
		var i ListAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Platform,
			&i.Format,
			&i.FormatVersion,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.IsNsfw,
			&i.Publication,
			&i.CurrentRevisionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCurrentRevision = `-- name: SetCurrentRevision :exec
update assets set current_revision_id = $2, updated_at = now() where id = $1
`

type SetCurrentRevisionParams struct {
	ID                pgtype.UUID
	CurrentRevisionID pgtype.UUID
}

func (q *Queries) SetCurrentRevision(ctx context.Context, arg SetCurrentRevisionParams) error {
	_, err := q.db.Exec(ctx, setCurrentRevision, arg.ID, arg.CurrentRevisionID)
	return err
}

const upsertBlob = `-- name: UpsertBlob :one
insert into blobs (id, sha256, byte_size, storage_key)
values ($1, $2, $3, $4)
on conflict (sha256) do update set sha256 = excluded.sha256
returning id, sha256, byte_size, storage_key
`

type UpsertBlobParams struct {
	ID         pgtype.UUID
	Sha256     []byte
	ByteSize   int64
	StorageKey string
}

func (q *Queries) UpsertBlob(ctx context.Context, arg UpsertBlobParams) (Blob, error) {
	row := q.db.QueryRow(ctx, upsertBlob,
		arg.ID,
		arg.Sha256,
		arg.ByteSize,
		arg.StorageKey,
	)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.ByteSize,
		&i.StorageKey,
	)
	return i, err
}
