#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
if [[ "$ENV_FILE" == ".env" ]]; then
  ENV_FILE="$SCRIPT_DIR/.env"
fi
SECRET_DIR="$SCRIPT_DIR/.production-secrets"
mkdir -p "$SECRET_DIR"
chmod 0700 "$SECRET_DIR"
umask 077

banner "Illarin production setup"

stage "Illarin: domain and VPS values"
say "These values become the VPS production settings. The local copy stays gitignored."
ask ILLARIN_DOMAIN "Public hostname, without https://:"
ILLARIN_DOMAIN="${ILLARIN_DOMAIN#https://}"
ILLARIN_DOMAIN="${ILLARIN_DOMAIN%/}"
ask PRODUCTION_HOST "OVH VPS hostname or IP address:"
ask PRODUCTION_USER "Existing sudo-capable VPS user [deploy]:"
PRODUCTION_USER="${PRODUCTION_USER:-deploy}"
ask PRODUCTION_SSH_PORT "VPS SSH port [22]:"
PRODUCTION_SSH_PORT="${PRODUCTION_SSH_PORT:-22}"
ask NPMPLUS_DASHBOARD_URL "Your existing NPMPlus dashboard URL:"
ask DISCORD_CLIENT_ID "Discord application client ID, or Enter to leave it disabled:"
ask_secret DISCORD_CLIENT_SECRET "Discord application client secret, or Enter to leave it disabled:"

POSTGRES_PASSWORD="$(_existing POSTGRES_PASSWORD || true)"
if [[ -z "$POSTGRES_PASSWORD" ]]; then
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
fi
LINKING_HMAC_KEY="$(_existing LINKING_HMAC_KEY || true)"
if [[ -z "$LINKING_HMAC_KEY" ]]; then
  LINKING_HMAC_KEY="$(openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n')"
fi

write_env ILLARIN_IMAGE_REGISTRY "ghcr.io/sillyfrogster"
write_env ILLARIN_DATA_DIR "/srv/illarin"
write_env ILLARIN_SECRETS_DIR "/etc/illarin/secrets"
write_env ILLARIN_GATEWAY_BIND "127.0.0.1"
write_env ILLARIN_GATEWAY_PORT "8000"
write_env NPMPLUS_NETWORK ""
write_env SITE_URL "https://$ILLARIN_DOMAIN"
write_env POSTGRES_DB "illarin"
write_env POSTGRES_USER "illarin"
write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
write_env DATABASE_URL "postgres://illarin:$POSTGRES_PASSWORD@db:5432/illarin"
write_env LINKING_HMAC_KEY "$LINKING_HMAC_KEY"
write_env DISCORD_CLIENT_ID "$DISCORD_CLIENT_ID"
write_env DISCORD_CLIENT_SECRET "$DISCORD_CLIENT_SECRET"
write_env BACKUPS_ENABLED "false"
write_env DEPLOY_MIN_FREE_MB "2048"
chmod 0600 "$ENV_FILE"

stage "Microsoft 365: register the mail application"
say "Illarin sends account email through Microsoft Graph as one mailbox."
open_url "https://entra.microsoft.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade"
step "Select New registration and name it Illarin Production Mail."
step "Choose Accounts in this organizational directory only and leave Redirect URI empty."
step "On Overview, copy the Directory (tenant) ID and Application (client) ID."
ask MICROSOFT_365_TENANT_ID "Directory tenant ID:"
ask MICROSOFT_365_CLIENT_ID "Application client ID:"
step "Open Enterprise applications, select Illarin Production Mail, and copy its Object ID."
ask MICROSOFT_365_SERVICE_PRINCIPAL_OBJECT_ID "Enterprise application Object ID:"
step "Back in App registrations, remove any API permissions. Do not add the organization-wide Graph Mail.Send permission."
step "Open Certificates & secrets, create a client secret, record its expiry, and copy the Value now."
ask_secret MICROSOFT_365_CLIENT_SECRET "Client secret Value:"
ask MICROSOFT_365_CLIENT_SECRET_EXPIRES "Client secret expiry date (YYYY-MM-DD):"
ask MICROSOFT_365_MAILBOX "Microsoft 365 sender mailbox:"

MICROSOFT_SECRET_FILE="$SECRET_DIR/microsoft-365-client-secret"
printf '%s' "$MICROSOFT_365_CLIENT_SECRET" >"$MICROSOFT_SECRET_FILE"
chmod 0600 "$MICROSOFT_SECRET_FILE"
write_env MICROSOFT_365_TENANT_ID "$MICROSOFT_365_TENANT_ID"
write_env MICROSOFT_365_CLIENT_ID "$MICROSOFT_365_CLIENT_ID"
write_env MICROSOFT_365_MAILBOX "$MICROSOFT_365_MAILBOX"
write_env MICROSOFT_365_SERVICE_PRINCIPAL_OBJECT_ID "$MICROSOFT_365_SERVICE_PRINCIPAL_OBJECT_ID"
write_env MICROSOFT_365_CLIENT_SECRET_EXPIRES "$MICROSOFT_365_CLIENT_SECRET_EXPIRES"
note "The client secret is in $MICROSOFT_SECRET_FILE, not the environment file."

stage "Exchange Online: limit Mail.Send to one mailbox"
say "An Exchange Administrator runs these commands in Exchange Online PowerShell."
open_url "https://learn.microsoft.com/en-us/exchange/permissions-exo/application-rbac"
step "Open PowerShell, install or update ExchangeOnlineManagement, then connect as an Exchange Administrator."
printf '\n'
note "Install-Module ExchangeOnlineManagement -Scope CurrentUser"
note "Connect-ExchangeOnline"
note "New-ServicePrincipal -AppId '$MICROSOFT_365_CLIENT_ID' -ObjectId '$MICROSOFT_365_SERVICE_PRINCIPAL_OBJECT_ID' -DisplayName 'Illarin Production Mail'"
note "New-ManagementScope -Name 'Illarin sender mailbox' -RecipientRestrictionFilter \"PrimarySmtpAddress -eq '$MICROSOFT_365_MAILBOX'\""
note "New-ManagementRoleAssignment -Name 'Illarin mailbox Mail.Send' -App '$MICROSOFT_365_SERVICE_PRINCIPAL_OBJECT_ID' -Role 'Application Mail.Send' -CustomResourceScope 'Illarin sender mailbox'"
note "Test-ServicePrincipalAuthorization -Identity '$MICROSOFT_365_SERVICE_PRINCIPAL_OBJECT_ID' -Resource '$MICROSOFT_365_MAILBOX' | Format-Table"
printf '\n'
step "Confirm the test shows Application Mail.Send with InScope set to True."
warn "Do not also grant Mail.Send in Entra. Entra and Exchange grants are additive, which would remove the mailbox limit."
if ! confirm "Did the scoped authorization test return InScope=True?"; then
  SKIPPED+=("Exchange Online mailbox-scoped Application Mail.Send assignment")
fi

stage "Datadog: collect host, container, and log data"
open_url "https://app.datadoghq.com/organization-settings/api-keys"
step "Create an API key named Illarin production and copy it."
ask_secret DD_API_KEY "Datadog API key:"
ask DD_SITE "Datadog site [datadoghq.com]:"
DD_SITE="${DD_SITE:-datadoghq.com}"
write_env DD_API_KEY "$DD_API_KEY"
write_env DD_SITE "$DD_SITE"
write_env DD_HOSTNAME "illarin-production"
note "The Compose stack collects host metrics, container state, and all container logs."

stage "GitHub: protect and authorize production deployment"
DEPLOY_KEY="$SECRET_DIR/github-deploy-ed25519"
if [[ ! -f "$DEPLOY_KEY" ]]; then
  ssh-keygen -q -t ed25519 -N "" -C "illarin-github-deploy" -f "$DEPLOY_KEY"
fi
step "Verify the VPS SSH host fingerprint against the fingerprint shown in the OVH console or on the VPS."
PRODUCTION_HOST_KEYS="$(ssh-keyscan -p "$PRODUCTION_SSH_PORT" -H -t ed25519 "$PRODUCTION_HOST" 2>/dev/null || true)"
if [[ -z "$PRODUCTION_HOST_KEYS" ]]; then
  ask PRODUCTION_HOST_KEYS "Paste the verified ssh-keyscan known_hosts line:"
else
  printf '%s\n' "$PRODUCTION_HOST_KEYS" >"$SECRET_DIR/production-known-hosts"
  ssh-keygen -lf "$SECRET_DIR/production-known-hosts" || true
  if ! confirm "Does this fingerprint match the VPS host key?"; then
    ask PRODUCTION_HOST_KEYS "Paste the verified known_hosts line instead:"
  fi
fi

set_secret PRODUCTION_HOST "$PRODUCTION_HOST"
set_secret PRODUCTION_USER "$PRODUCTION_USER"
set_secret PRODUCTION_SSH_PORT "$PRODUCTION_SSH_PORT"
set_secret PRODUCTION_SSH_KEY "$(<"$DEPLOY_KEY")"
set_secret PRODUCTION_HOST_KEYS "$PRODUCTION_HOST_KEYS"
set_var PRODUCTION_URL "https://$ILLARIN_DOMAIN"
open_url "https://github.com/Sillyfrogster/LumiHub/settings/environments"
step "Create an environment named production and restrict its deployment branch to master."
step "Add a required reviewer if your GitHub plan exposes that control."

stage "OVH VPS: install the generated production settings"
say "Copy four generated files to the VPS, then let the bootstrap install them safely."
note "scp -P $PRODUCTION_SSH_PORT '$ENV_FILE' '$MICROSOFT_SECRET_FILE' '$DEPLOY_KEY.pub' '$SCRIPT_DIR/bootstrap-vps.sh' '$PRODUCTION_USER@$PRODUCTION_HOST:/tmp/'"
step "Run that scp command from this project on your computer."
note "ssh -p $PRODUCTION_SSH_PORT '$PRODUCTION_USER@$PRODUCTION_HOST' \"sudo /tmp/bootstrap-vps.sh '$PRODUCTION_USER' '/tmp/$(basename "$ENV_FILE")' '/tmp/$(basename "$MICROSOFT_SECRET_FILE")' '/tmp/$(basename "$DEPLOY_KEY").pub'\""
step "Run that ssh command, then sign out and back in so Docker group membership applies."
step "Remove the copied environment and Microsoft secret files from /tmp after bootstrap succeeds."
if ! confirm "Did the VPS bootstrap finish successfully?"; then
  SKIPPED+=("VPS bootstrap")
fi

stage "NPMPlus and Gcore: connect the public hostname"
say "NPMPlus remains the TLS edge. Illarin's nginx remains an internal application gateway."
step "Read the detected target with: cat /etc/illarin/npmplus-target"
ask NPMPLUS_FORWARD_HOST "Detected forward host:"
ask NPMPLUS_FORWARD_PORT "Detected forward port:"
open_url "$NPMPLUS_DASHBOARD_URL"
step "Create one Proxy Host for $ILLARIN_DOMAIN using HTTP to $NPMPLUS_FORWARD_HOST:$NPMPLUS_FORWARD_PORT."
step "Request or select its certificate, then enable Force SSL and HTTP/2."
step "In Gcore DNS, keep the record DNS-only and point its A record to $PRODUCTION_HOST."
note "NPMPlus owns certificates. The repo nginx owns /api, /media, /download, and private blob routing."

stage "First deployment and verification"
say "Merge this work to master first. CI must pass and Publish images must finish before deployment."
open_url "https://github.com/Sillyfrogster/LumiHub/actions/workflows/deploy-production.yml"
step "Choose Run workflow on master. Approve the production environment if GitHub asks."
step "After it finishes, open https://$ILLARIN_DOMAIN/api/healthz and expect ok."
step "Create a test account and confirm the Microsoft 365 mailbox sends its verification email."
step "In Datadog, confirm the illarin-production host and the API, web, gateway, and Postgres containers appear."
warn "Off-box backups are disabled because no backup storage exists yet. This is recorded work, not a completed safeguard."
SKIPPED+=("off-box backups: purchase storage, configure restic, rehearse a restore, then set BACKUPS_ENABLED=true")

finish
